### ISSUE TITLE
Host key verification failed 的问题

### ISSUE THREAD

**Issue by sofire** [meolu/walle-web#100]
如果服务器没有用帐号连接过，第一次连接的时候，会提示：
Are you sure you want to continue connecting (yes/no)? yes

如果不输入yes，则部署的时候会出错。错误提示是：
2016-02-01 18:05:50 -- Host key verification failed.
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(600) [sender=3.0.6]

需要修改文件：
components/Folder.php   65行

```
$command = sprintf('rsync -avzq --rsh="ssh -p %s" %s %s %s%s:%s'
```
添加字符串：-q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no

即改成:
```
$command = sprintf('rsync -avzq --rsh="ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p %s" %s %s %s%s:%s',
```

**Comment by meolu** [comment]
感谢，已更新到master
