### ISSUE TITLE
执行flask db upgrade 后提示Can`t connet to local MYSQL server through socket "/var/lib/mysql/mysql.sock"

### ISSUE THREAD

**Issue by yjiu1990** [meolu/walle-web#1011]
**问题**：错误信息
样例：执行flask db upgrade 后提示Can`t connet to local MYSQL server through socket "/var/lib/mysql/mysql.sock",

**解决**：
可将mysql.sock做一个软连接，比如mysql.sock文件在/usr/local/mysql/mysqld.sock，则执行ln -s /usr/local/mysqld.sock /var/lib/mysql/mysql.sock 即可

**Comment by balingmo403** [comment]
这种小问题怎么能算个bug呢？两个问题想问作者，1.啥时候支持python3，2.在头条上班很闲吗？明显的工作不饱和吗！

**Comment by sports98** [comment]
说真的，看完jenkins感觉这个项目想追上不容易啊。。。。

**Comment by ZouHongxue** [comment]
> 说真的，看完jenkins感觉这个项目想追上不容易啊。。。。

任重而道远，大佬多支持

**Comment by ZouHongxue** [comment]
> 这种小问题怎么能算个bug呢？两个问题想问作者，1.啥时候支持python3，2.在头条上班很闲吗？明显的工作不饱和吗！

作者大佬已经累得N个月没处理开源了，理解万岁。
