### ISSUE TITLE
无法正确识别COMPOSER_HOME环境变量

### ISSUE THREAD

**Issue by changs1986** [meolu/walle-web#1018]
**问题描述**
无法正确识别COMPOSER_HOME环境变量，环境变量已经系统配置了，貌似是Connection.run的时候无法读取本地环境的环境变量？希望能给予反馈，谢谢

**问题描述**
[www@127.0.0.1]$ cp -rf /tmp/git/5 5_42_20190929_164300
[www@127.0.0.1]$ composer install --no-dev -o

[RuntimeException]
The HOME or COMPOSER_HOME environment variable must be set for composer to
run correctly

**截图**
![image](https://user-images.githubusercontent.com/3759737/65829521-1505e800-e2d9-11e9-8a48-744b2c7fd06a.png)

**运行环境**
 - OS: CentOS 7.x
 - 版本 2.0.1

**Comment by ZouHongxue** [comment]
walle在执行deploy时有三种: sudo, local 和remote。
请检查下启动walle的用户是否可以在宿主机直接执行这个命令，
如果这个命令是在目标机器上执行的，请测试使用ssh配置登录目标机的用户是否可以执行。
