### ISSUE TITLE
在测试环境可以支持多分支合并吗，类拟阿里的发布系统

### ISSUE THREAD

**Issue by kedumin** [meolu/walle-web#102]
Hi,哥们！晚上试了一下瓦力的系统非常棒，希望能增加一个功能不知道是否方便支持。
在测试环境提交发布单的时候，可以选择多个项目的分支。因为平时开发会多人协同，大家在不同的分支上面，然后测试环境只有一个，每次只能部署一个分支，就需要把其它分支的代码合并过来，这个比较麻烦，而且搞的不好最终大家都到这个合并的分支上去开发的。

所以：是否方便在测试环境提测的时候，可以选择多个分支，瓦力在部署的时候，创建一个新分支，然后多个分支与master分支合并，使用这个新分支去部署。
然后这个测试环境的发布，是可以重复部署的，每次部署都把这几个分支的最新代码合并过来。

**Comment by meolu** [comment]
说的这个分支就是develop分支，首先得说的是walle去merge多个分支成到develop分支是可能会出现冲突的，冲突出现必须手工处理。

团队协作讲究流程的统一，也就是说如果使用git作为版本管理，就需要一套统一的git工作流（git-flow），可以查下具体博文，我也曾经写过一篇[《技术团队代码管理和部署》](http://blog.huamanshu.com/?date=2015-09-19)。

简单介绍下解决这个非技术问题的思路。你需要一个测试环境的分支，也就是develop分支。开发者一般处于feature分支，在此分支上把一个需求开发完毕，并且自测通过了，再提code review和 merge request，等待合并到develop分支。更专业来说，后面的事儿就由QA来处理了，什么时候重新部署develop分支到测试环境，由她来决定（因为QA可能有正在验收develop分支的其它功能，如果你这个时候强行更新，会破坏环境，打乱他的工作）。重新部署后验收发现了bug，给你提bug单时，你可以在此develop分支基础上切一个fix的分支做修正，合并也类似feature分支一样，需要review和merge。

为什么要这样做？因为我们要保证develop他承担的角色意义，它必须是自测通过的，code review通过可以上测试环境的，等待最后QA验收的，否则就不要提merge request合并到develop，用劣质的代码影响别人的工作。

理解和同意不？

**Comment by kedumin** [comment]
首先感谢哥们这么迅速的回复，对于git-flow的流程我是认可的，但针到不同的公司在流程上个人认为可以有更好的优化空间。

我们是个创业公司，团队成员大部分来自BAT,公司没有QA所有功能开发自测，人少事多每个人都会独立负责一些需求，对于生产环境我们希望做到一周发布一二次，但是对于测试环境每天都会有好多次更新，且都是由开发同学自主操作。

介于我们的需求和我们以前在阿里的工作经历(阿里的二代发布系统我都有参与)。我们还是希望测试环境可以有多个分支跟主干合并[主干拉出一个新分支用来做这个操作](合并过程中有冲突由人工解决)。这样要提测的代码都可以自主上测试环境。我们的业务主要是app相关的，所以测试环境需要经常更新代码重新部署给客户端同学联调。如果有多分支合并的功能，开发同学只要提交代码，然后在瓦力平台上点一下重新部署就可以部署最新的代码了，协同效率高。

另外：对于仿真环境代码是不合并主干的，因为在仿真环境(我们叫预发)也是不稳定的，很多开发环境不方便测的功能需要去仿真环境上测试。测试通过后才能发布。发布完成后才能把代码合并主干，同时打出tag用于后续回滚。
