### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by smile-wang** [meolu/walle-web#1020]
**问题描述**
导入数据无法正常进行

**问题描述**
   mod = imp.load_source(module_id, path, fp)
  File "migrations/env.py", line 90, in <module>
    run_migrations_online()
  File "migrations/env.py", line 83, in run_migrations_online
    raise exception
sqlalchemy.exc.InternalError: (pymysql.err.InternalError) (1067, u"Invalid default value for 'created_at'") [SQL: u"CREATE TABLE `environments` (\n              `id` int(10) NOT NULL AUTO_INCREMENT COMMENT '',\n              `name` varchar(100) DEFAULT 'master' COMMENT '',\n              `space_id` int(10) NOT NULL DEFAULT '0' COMMENT '',\n              `status` tinyint(1) DEFAULT '1' COMMENT '',\n              `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '',\n              `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',\n              PRIMARY KEY (`id`)\n            ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='';"] (Background on this error at: http://sqlalche.me/e/2j85)
Migration:                 [ fail ]

python 2.75

**Comment by ZouHongxue** [comment]
将Exception中的SQL去除\n执行没有问题，确认下是否是数据库版本问题。
我测试用的数据库版本: Server version: 8.0.12 Homebrew。
推荐数据库版本: https://www.walle-web.io/docs/dependency.html
![image](https://user-images.githubusercontent.com/20573881/67629031-de58c880-f8aa-11e9-9241-21c525225981.png)
