### ISSUE TITLE
第一次使用，部署java项目，通过maven投建，上线返回/bin/bash: /usr/local/maven/bin/mvn: No such file or directory

### ISSUE THREAD

**Issue by gpqhl0071** [meolu/walle-web#1021]
**问题描述**
通过docker-compose方式部署，参考：https://walle-web.io/docs/installation_docker.html

项目管理配置如下图

![1](https://user-images.githubusercontent.com/8787216/66741045-2f2df180-eea7-11e9-801b-0902716e5669.png)

进行上线操作的时候，提示
`[root@127.0.0.1]$ cd /opt/walle_home/codebase/ && cp -rf /opt/walle_home/codebase/1 1_9_20191014_171313
[root@127.0.0.1]$ ${MVN_HOME}/bin/mvn clean install -Dmaven.test.skip=true
/bin/bash: /usr/local/maven/bin/mvn: No such file or directory
[root@127.0.0.1]$ cd /opt/walle_home/codebase/ && rm -rf 1_9_*
`
![2](https://user-images.githubusercontent.com/8787216/66741065-3c4ae080-eea7-11e9-9a98-13d5297269f5.png)

其中docker-compose.yml和你参考文档中一样，未进行任何修改，请问应该如何解决？

**Comment by ZouHongxue** [comment]
测试没有问题，确认你的maven安装路径是否正确。在deploy后置任务中应该是宿主机(安装walle)需要这个环境，不确定的话最好把目标机器也设置好maven。
![image](https://user-images.githubusercontent.com/20573881/67628996-20cdd580-f8aa-11e9-9181-73a3711a0541.png)

**Comment by CXLYJ** [comment]
映射的路径没错但是还是有这个问题怎么解决呢？
![image](https://user-images.githubusercontent.com/25575673/78328816-a91b7980-75b2-11ea-98da-e3c220261258.png)
