### ISSUE TITLE
高级任务-Deploy前置任务有执行却没有起效

### ISSUE THREAD

**Issue by 444136347** [meolu/walle-web#1023]
![1571306350902](https://user-images.githubusercontent.com/22359201/66999027-dc9f4000-f107-11e9-9db2-d65de0b7b5a8.jpg)
![1571306355880](https://user-images.githubusercontent.com/22359201/66999030-ddd06d00-f107-11e9-9205-4f8b6298b71c.jpg)
waller2.0.1已经正式部署且可以进行上线。
但是高级任务-Deploy前置任务有执行却没有起效
![图片](https://user-images.githubusercontent.com/22359201/66999325-5c2d0f00-f108-11e9-83cf-eb5bae29e453.png)

**Comment by 444136347** [comment]
自问自答系列：
把deploy前置任务方到高级任务-releases
后置任务即可

**Comment by ZouHongxue** [comment]
nice job
