### ISSUE TITLE
The directory is not writable by the Web process:

### ISSUE THREAD

**Issue by smalleyes** [meolu/walle-web#103]
Invalid Configuration: The directory is not writable by the Web process: /var/www/html/walle-web/web/assets 
权限问题，
[xmc@server-124 web]$ ps auxf|grep php
root      5718  0.0  2.8 477048 28660 ?        Ss   13:56   0:00 php-fpm: master process (/etc/php-fpm.conf)
xmc       5719  0.0  1.8 479620 18964 ?        S    13:56   0:00  \_ php-fpm: pool www
xmc       5720  0.0  2.2 483200 22544 ?        S    13:56   0:00  \_ php-fpm: pool www
xmc       5721  0.0  2.2 483200 22544 ?        S    13:56   0:00  \_ php-fpm: pool www
xmc       5722  0.0  2.0 482224 21044 ?        S    13:56   0:00  \_ php-fpm: pool www
xmc       5723  0.0  1.8 479620 18964 ?        S    13:56   0:00  \_ php-fpm: pool www

[xmc@server-124 web]$ ll
总用量 20
drwxrwxrwx. 2 xmc xmc 4096 2月  16 16:50 ace
drwxrwxrwx. 2 xmc xmc    6 2月  17 11:05 assets
drwxrwxrwx. 9 xmc xmc   92 2月  16 16:50 dist
-rwxrwxrwx. 1 xmc xmc 4286 2月  16 16:50 favicon.ico
-rwxrwxrwx. 1 xmc xmc  387 2月  17 10:30 index.php
-rw-rw-r--. 1 xmc xmc  337 2月  17 11:37 test.php
各种更改目录权限都报这个错误，在xmc用户下用命令行执行都是有权限的。奇怪

**Comment by meolu** [comment]
如果是在1.0版本的话，可以直接`./yii walle/setup`重置权限

**Comment by sailong** [comment]
我的也是同样的错误，怎么改权限都一样！
你的这个问题解决了嘛？
请求帮助~~~

**Comment by smalleyes** [comment]
之前没有解决，今天试了下进去了，不过执行检测的时候又报如下错误：
**宿主机代码检出检测出错，请确认php进程用户xmc有代码存储仓库/var/www/repertory读写权限，并且把ssh-key加入git的deploy-keys列表。详细错误：

目标机器部署出错，请确认php进程xmc用户ssh-key加入目标机器的xmc用户ssh-key信任列表，且xmc有目标机器发布版本库/var/www/code写入权限。详细错误：172.16.2.128 : **

php-fpm 属于xmc用户和用户组

目录都执行了
chown -Rf xmc:xmc /var/www/repertory
chmod -Rf 777 /var/www/repertory

chown -Rf xmc:xmc /var/www/code
chmod -Rf 777 /var/www/code

并且ssh-key宿主机与目标机都添加了
ssh -T git@gitlab都可以正常，真是见鬼了

下终端下可以直接免密码执行git操作

系统fedora 23 
nginx version: nginx/1.8.0
PHP 5.6.18 (fpm-fcgi) (built: Feb  4 2016 12:06:59)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

**Comment by smalleyes** [comment]
建议群主可以建个交流群

**Comment by smalleyes** [comment]
https://doc.huamanshu.com/%E7%93%A6%E5%8A%9B/6.FAQ/%E6%A3%80%E6%B5%8B%E5%87%BA%E9%94%99.html
算了，估计再过一阵子在看就可以了

**Comment by meolu** [comment]
有群的：482939318

**Comment by showfilv** [comment]
我也一样我把权限全改成777都不行。
