### ISSUE TITLE
执行到Rsync 时貌似假死

### ISSUE THREAD

**Issue by MustangZhong** [meolu/walle-web#104]
Executing: $ rsync -avzq --rsh="ssh -p 22" --exclude='.svn' /data/wwwroot/。。。。

到这一步时无法完成

**Comment by meolu** [comment]
应该是同步文件时间过长，php nginx超时了，加大php nginx超时时间

**Comment by devtoby** [comment]
@meolu 提个建议，可以考虑将发布过程用异步方式执行，前台页面定时拉取状态

**Comment by meolu** [comment]
嗯，正在做，下一版本就有
