### ISSUE TITLE
安装失败 求助

### ISSUE THREAD

**Issue by aspfate** [meolu/walle-web#108]
使用的是master分支
代码已经同步到最新
执行`composer install --prefer-dist --no-dev --optimize-autoloader -vvvv`
报错
 [RuntimeException]
  The openssl extension is required for SSL/TLS protection but is not available. If you can not enab
  le the openssl extension, you can disable this error, at your own risk, by setting the 'disable-tl
  s' option to true.
不知道这个是不是必须的

执行 `./yii walle/setup`
报错

create dir 创建目录...
mkdiring dir: /tmp/walle/
set writable 设置可写权限...
Setting writable: /var/www/html/runtime
Setting writable: /var/www/html/web/assets
Setting writable: /tmp/walle/
set executable 设置可执行权限...
Setting executable: /var/www/html/yii
update database 更新数据库: yii migrate/up ...
Yii Migration Tool (based on Yii v2.0.7-dev)

Error: could not find driver

**Comment by meolu** [comment]
php没有pdo_mysql扩展，安装就好
