### ISSUE TITLE
目前使用的symlink作为回滚和发布，可能对使用OPcache的用户是有影响的

### ISSUE THREAD

**Issue by devtoby** [meolu/walle-web#109]
因为目前OPcache的缓存机制，再加上PHP的Realpath Cache，就导致更新symlink后，OPcache无法发现变更，导致发布在一定时间内不生效，或者有时有效有时无效。

**Comment by littlehz** [comment]
生产环境建议：
1、opcache.validate_timestamps = 0，即关闭 opcache 文件更新检查
2、发布代码，高级任务里，发布完成后执行 curl 调用 web(php-fpm) 下的php， opcache_reset();
3、不要使用 文件session、文件缓存之类的。

**Comment by devtoby** [comment]
@littlehz 2可能并不行，据我所知Opcache使用的并非共享内存，这样的操纵对fpm来说只会更新其中一个进程，因此其他的fpm进程可能还会不生效

**Comment by littlehz** [comment]
@devtoby 没问题的，php-fpm下执行 opcache_reset()，所有 php-fpm 进程生效。

**Comment by littlehz** [comment]
php-fpm 进程与 php-cli 进程独立

**Comment by littlehz** [comment]
补充，如果升级到 nginx 1.9 以上版本，需要修改 fastcgi 参数

将
`fastcgi_param  SCRIPT_FILENAME    $document_root$fastcgi_script_name;`
改为
`fastcgi_param  SCRIPT_FILENAME    $realpath_root$fastcgi_script_name;`
