### ISSUE TITLE
BUG 依赖冲突，无法安装

### ISSUE THREAD

**Issue by wykdg** [meolu/walle-web#1096]
**问题描述**
目前的master版本，执行admin.sh 安装环境冲突

**问题描述**
日志堆栈贴上来。
ERROR: Could not find a version that satisfies the requirement gitdb>=4.0.1 (from gitdb2>=2.0.0->GitPython==2.1.11->-r ./requirements/prod.txt (line 43)) (from versions: 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4)
ERROR: No matching distribution found for gitdb>=4.0.1 (from gitdb2>=2.0.0->GitPython==2.1.11->-r ./requirements/prod.txt (line 43))

**截图**
拖拽到此处即可上传

**运行环境**
 - OS: [e.g. Centos 7.0]
 - 版本 [e.g. 6e96e619] 

去除版本号后安装成功，安装了2.1.15.希望能够修正一下这个。

**Comment by linux724** [comment]
嗯，我安装也报错了，后来换成https://github.com/openspug/spug 这个了。

**Comment by gogoqiu** [comment]
pip install virtualenv
改成
 pip3 install virtualenv
pip install -r ./requirements/prod.txt -i http://pypi.douban.com/simple --trusted-host pypi.douban.com
改成
pip3 install -r ./requirements/prod.txt -i http://pypi.douban.com/simple --trusted-host pypi.douban.com
nohup python ${APP} >> logs/runtime.log 2>&1 &
改成
nohup python3 ${APP} >> logs/runtime.log 2>&1 &
可以解决依赖问题，不过页面提示后台服务未启动

**Comment by gogoqiu** [comment]
pip3 install gitpython
ok!!!

**Comment by pptfz** [comment]
@gogoqiu 使用pip3确实是能解决依赖问题，但是后续启动walle2一定会失败，始终报错如下
```
Traceback (most recent call last):
  File "waller.py", line 5, in <module>
    from flask.helpers import get_debug_flag
ImportError: No module named flask.helpers
```
并且目前这个问题无解

**Comment by ZouHongxue** [comment]
已修复 https://github.com/meolu/walle-web/pull/1129
