### ISSUE TITLE
 启动成功，使用出现“后台服务未启动”的情况，请问怎么解决

### ISSUE THREAD

**Issue by webzly** [meolu/walle-web#1111]
sh admin.sh start 启动成功
Starting walle
----------------
Start walle:                 [ ok ]
runtime:  logs/runtime.log 
error:  logs/error.log 

访问页面出现：
后台服务未启动
请检查日志或者点官网链接查看帮助

查看network 发现 api/相关接口出现502错误，经查看服务端5000端口未启动，重启nginx也没有用，请问怎么解决。

nginx 配置如下：
upstream webservers {
    server 0.0.0.0:5000 weight=1; # 负载设置
}

server {
    listen       8088;
    server_name  124.156.9.8; # 域名设置
    access_log   /usr/local/nginx/logs/walle.log main;
    index index.html index.htm; # 日志目录

    location / {
        try_files $uri $uri/ /index.html;
        add_header access-control-allow-origin *;
        root /data/www/walle-web/fe; # 前端代码已集成到walle-web，即walle-web/fe的绝对路径
    }

    location ^~ /api/ {
        add_header access-control-allow-origin *;
        proxy_pass      http://webservers;
        proxy_set_header X-Forwarded-Host $host:$server_port;
        proxy_set_header  X-Real-IP  $remote_addr;
        proxy_set_header    Origin        $host:$server_port;
        proxy_set_header    Referer       $host:$server_port;
    }

    location ^~ /socket.io/ {
        add_header access-control-allow-origin *;
        proxy_pass      http://webservers;
        proxy_set_header X-Forwarded-Host $host:$server_port;
        proxy_set_header  X-Real-IP  $remote_addr;
        proxy_set_header    Origin        $host:$server_port;
        proxy_set_header    Referer       $host:$server_port;
        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;

        # WebScoket Support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}

**Comment by linux724** [comment]
https://github.com/openspug/spug 这个平台比瓦力更好用，可以了解一下。

**Comment by lipeng77** [comment]
我也遇到了，还是没解决

**Comment by webzly** [comment]
> 我也遇到了，还是没解决
不知道什么原因，我将 ip 访问方式 换成 域名的方式之后，可以正常访问了

nginx配置文件中server_name  和 walle/config/settings_prod.py 文件中的HOST保持一致。host文件也要指定域名

**Comment by webzly** [comment]
> https://github.com/openspug/spug 这个平台比瓦力更好用，可以了解一下。

谢谢啦，问题已经解决了

**Comment by lipeng77** [comment]
是保持的，只是启动的时候 ，waller.py报错，说ImportError: No module named flask.helpers,
但是我已经安装了flask.helpers










--


此
    敬

李鹏
QQ：578831699
手机（微信）：18600837595

Email：comet77@163.com




在 2020-05-08 11:14:40，"webzly" <notifications@github.com> 写道：

我也遇到了，还是没解决
不知道什么原因，我将 ip 访问方式 换成 域名的方式之后，可以正常访问了

nginx配置文件中server_name 和 walle/config/settings_prod.py 文件中的HOST保持一致。host文件也要指定域名

**Comment by lipeng77** [comment]
Traceback (most recent call last):
  File "waller.py", line 5, in <module>
    from flask.helpers import get_debug_flag
ImportError: No module named flask.helpers

**Comment by webzly** [comment]
> 是保持的，只是启动的时候 ，waller.py报错，说ImportError: No module named flask.helpers, 但是我已经安装了flask.helpers
> […](#)
> -- 此 敬 李鹏 QQ：578831699 手机（微信）：18600837595 Email：comet77@163.com 在 2020-05-08 11:14:40，"webzly" <notifications@github.com> 写道： 我也遇到了，还是没解决 不知道什么原因，我将 ip 访问方式 换成 域名的方式之后，可以正常访问了 nginx配置文件中server_name 和 walle/config/settings_prod.py 文件中的HOST保持一致。host文件也要指定域名 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.



init的时候有报错吗？


安装的时候我也遇到了这个错误，我重新安装了flask的依赖包，pip install flask

**Comment by webzly** [comment]
> No module named flask.helpers

是 pip install flask-helpers

**Comment by lipeng77** [comment]
安装的时候没有，就是在start,restart的时候，数据迁移什么都是好的。




在 2020-05-08 11:28:27，"webzly" <notifications@github.com> 写道：

是保持的，只是启动的时候 ，waller.py报错，说ImportError: No module named flask.helpers, 但是我已经安装了flask.helpers
…
-- 此 敬 李鹏 QQ：578831699 手机（微信）：18600837595 Email：comet77@163.com 在 2020-05-08 11:14:40，"webzly" notifications@github.com 写道： 我也遇到了，还是没解决 不知道什么原因，我将 ip 访问方式 换成 域名的方式之后，可以正常访问了 nginx配置文件中server_name 和 walle/config/settings_prod.py 文件中的HOST保持一致。host文件也要指定域名 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

init的时候有报错吗？

安装的时候我也遇到了这个错误，我重新安装了flask的依赖包，pip install flask

**Comment by lipeng77** [comment]
At 2020-05-08 11:31:28, "webzly" <notifications@github.com> wrote:

No module named flask.helpers

是 pip install flask-helpers

**Comment by webzly** [comment]
> pip install flask-helpers

pip list 确保有这个依赖包，然后重新初始化和数据迁移试试

**Comment by lipeng77** [comment]
依赖都有，等下我重新安装一下试试，谢谢啊















在 2020-05-08 11:42:04，"webzly" <notifications@github.com> 写道：

pip install flask-helpers

pip list 确保有这个依赖包，然后重新初始化和数据迁移试试

**Comment by lsqpy** [comment]
> > https://github.com/openspug/spug 这个平台比瓦力更好用，可以了解一下。
> 
> 谢谢啦，问题已经解决了

怎么解决的老兄
