### ISSUE TITLE
作者不维护了吗？安装就没成功过。那么多iss需要处理。

### ISSUE THREAD

**Issue by feng99** [meolu/walle-web#1113]
那个admin.sh一运行就报错。(T＿T)

**Comment by linux724** [comment]
看起来很久没更新了。
可以了解一下Spug开源项目：https://github.com/openspug/spug

**Comment by feng99** [comment]
> 看起来很久没更新了。
> 可以了解一下Spug开源项目：https://github.com/openspug/spug

嗯 我也试试看    能部署代码  能回滚   比jenkins轻量级就行.
