### ISSUE TITLE
提交部署页面会报错

### ISSUE THREAD

**Issue by wor1d** [meolu/walle-web#112]
报错的内容是这样的，对PHP不是很熟。
simplexml_load_string(): Entity: line 1: parser error : Start tag expected, '<' not found

**Comment by wor1d** [comment]
是否有可能是因为获取svn log 的时候中文导致的报错？

**Comment by meolu** [comment]
php通过shell获取svn的xml格式log，看下svn版本

**Comment by wor1d** [comment]
version 1.8.10 (r1615264)
我在shell执行命令时显示正常的，但是在log中是有乱码的。
这个会有影响的吗？

**Comment by wor1d** [comment]
我把获取提交记录count，改成1后。依旧报错，下面是日志。推测应该不是中文编码问题。
<?xml version="1.0" encoding="UTF-8"?>
<log>
<logentry
   revision="3508">
<author>***</author>
<date>2016-02-26T07:32:11.358616Z</date>
<msg>zzhweb</msg>
</logentry>
</log>

**Comment by wor1d** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<log>
<logentry
    revision="3508">
<author>zzh</author>
<date>2016-02-26T07:32:11.358616Z</date>
<msg>zzhweb</msg>
</logentry>
</log>

**Comment by wor1d** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<log>
<logentry
   revision="3508">
<author>***</author>
<date>2016-02-26T07:32:11.358616Z</date>
<msg>zzhweb</msg>
</logentry>
</log>`

**Comment by meolu** [comment]
`tail -f /tmp/walle/最新日志`，重新获取看下

**Comment by yanmengxiang** [comment]
我也遇到这个问题，我的原因是缺少中文语言包，安装下中文语言包就ok了，ubuntu环境下！
