### ISSUE TITLE
BUG 安装报错 (sh admin.sh init)

### ISSUE THREAD

**Issue by WeGiao** [meolu/walle-web#1125]
**问题描述**

在`centos7`下，执行 `sh admin.sh init` 报错，如下: 

```
ERROR: Could not find a version that satisfies the requirement gitdb>=4.0.1 (from gitdb2>=2.0.0->GitPython==2.1.11->-r ./requirements/prod.txt (line 43)) (from versions: 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4)
ERROR: No matching distribution found for gitdb>=4.0.1 (from gitdb2>=2.0.0->GitPython==2.1.11->-r ./requirements/prod.txt (line 43))

```

> 错误：找不到满足gitdb> = 4.0.1的版本（来自gitdb2> = 2.0.0-> GitPython == 2.1.11->-r ./requirements/prod.txt（第43行））（从版本：0.5.0、0.5.1、0.5.2、0.5.3、0.5.4、0.6.0、0.6.1、0.6.2、0.6.3、0.6.4）
错误：找不到gitdb> = 4.0.1的匹配分布（来自gitdb2> = 2.0.0-> GitPython == 2.1.11->-r ./requirements/prod.txt（第43行））

**截图**
![image](https://user-images.githubusercontent.com/26691978/88452443-50d5f380-ce91-11ea-9383-8a5145673bed.png)

**运行环境**
 - OS: [e.g. CentOS 7.8.2003(Py2.7.5)]

**Comment by Alenx58** [comment]
@WeGiao 该问题已经解决，请更新代码
