### ISSUE TITLE
解决walle2.1版本 执行sh admin.sh init 命令  gitdb模块无法安装问题

### ISSUE THREAD

**Issue by BILLFuYiWei** [meolu/walle-web#1126]
**问题**：错误信息
执行sh admin.sh init 提示:  ERROR: Could not find a version that satisfies the requirement gitdb>=4.0.1 (from gitdb2>=2.0.0->GitPython==2.1.11->-r ./requirements/prod.txt (line 43)) (from versions: 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4)
ERROR: No matching distribution found for gitdb>=4.0.1 (from gitdb2>=2.0.0->GitPython==2.1.11->-r ./requirements/prod.txt (line 43))
![image](https://user-images.githubusercontent.com/67575144/89399538-34657100-d745-11ea-8b29-38d05c7d87b3.png)

**解决**：
解决 pip install gitdb2==2.0.6

**Comment by Alenx58** [comment]
@BILLFuYiWei 该问题已解决

**Comment by ZouHongxue** [comment]
附 https://github.com/meolu/walle-web/pull/1129
