### ISSUE TITLE
安装后访问后报403

### ISSUE THREAD

**Issue by scm20008** [meolu/walle-web#113]
composer install --prefer-dist --no-dev --optimize-autoloader -vvvv
# 执行上面的命令后，报如下错：

Package guzzle/common is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/stream is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle instead.

@meolu

**Comment by scm20008** [comment]
后面下载vendor.tgz解压后，并启动apache2服务后，出现没有权限的页面，如下：
![2016-03-01_120503](https://cloud.githubusercontent.com/assets/639305/13417347/ea8e5b50-dfa5-11e5-99e6-1c98ee6a056e.png)

@meolu

**Comment by meolu** [comment]
guzzle是依赖的依赖，为第三方引入的。忽略也没什么问题

**Comment by meolu** [comment]
403看下apache日志是什么原因？

**Comment by scm20008** [comment]
[Tue Mar 01 12:31:37.537069 2016] [so:warn] [pid 7432] AH01574: module php5_module is already loaded, skipping
[Tue Mar 01 12:31:37.583400 2016] [mpm_prefork:notice] [pid 7433] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.14 configured -- resuming normal operations
[Tue Mar 01 12:31:37.583469 2016] [core:notice] [pid 7433] AH00094: Command line: '/usr/sbin/apache2'

@meolu 也看不出什么原因

**Comment by xiezhao** [comment]
我也apache也是 403， 换成 nginx，页面跳转总是跳错误，直接从 index.php 跳到 /web/site/login.php. 而这个login.php明明在 views/site/login.php ，无语了，浪费了半天的时间了，有什么解决办法吗？

**Comment by meolu** [comment]
apache这东西，实在不推荐，nginx直接按时文档上的[范例](https://github.com/meolu/walle-web/blob/master/docs/install.md#6配置nginxapache)配置就好。

**Comment by scm20008** [comment]
主要是以前一直用apache，nginx用得不大熟悉。我换nginx再试试。

**Comment by xiezhao** [comment]
@scm20008 直接拷贝nginx的代码不用做任何配置，启动就ok，如果你还没配置好的话，留个QQ之类的，我帮你解决。
@meolu 谢谢你，解决了。

**Comment by meolu** [comment]
@xiezhao 就喜欢你这种同学：）

**Comment by scm20008** [comment]
谢谢@xiezhao 我安装好了再看。

**Comment by xiezhao** [comment]
@scm20008  不客气，我的QQ：159065974   可以随时问我，哈哈

**Comment by scm20008** [comment]
@xiezhao 加你扣扣了，nginx配置不会，报错如下，
nginx: [emerg] "server" directive is not allowed here in /etc/nginx/nginx.conf:97

官网提供的server段代码放到哪里的？

**Comment by qxhy123** [comment]
建议在nginx安装目录下新建conf.d目录, 子站配置都放这里, 然后nginx.conf配置通用设置, 具体如下:
`worker_processes  5;
worker_rlimit_nofile 65535;
error_log  logs/error_log;
#pid        logs/nginx.pid;

events {
    use epoll;
    multi_accept on;
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        off;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;
    #gzip  on;
    include /usr/local/nginx/conf.d/*.conf;      #注意这里哦, 前面的路径要换成你自己的nginx安装目录
}`

**Comment by scm20008** [comment]
@qxhy123 
我是默认的nginx.conf没动，将server段的代码放到/etc/nginx/sites-available/default里了。

**Comment by qxhy123** [comment]
修改nginx配置后, nginx -t可以查看配置文件语法错误, 可以帮助你进行调试

**Comment by scm20008** [comment]
@qxhy123 
嗯，将官网的server段代码放到default里没有语法错误，但是会报502错误，目前能想到的是nginx没法解析index.php

**Comment by qxhy123** [comment]
@scm20008 能把配置文件贴一下我看看吗

**Comment by scm20008** [comment]
文件：/etc/nginx/sites-available/default

server {
        listen       80;
        server_name  localhost;
        root /data/www/walle-web/web;
        index index.php;

        location / {
                try_files $uri $uri/ /index.php$is_args$args;
        }

        location ~ \.php$ {
                try_files $uri = 404;
                fastcgi_pass   127.0.0.1:9000;
                fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
                include        fastcgi_params;
        }
}

**Comment by qxhy123** [comment]
配置没有问题.
502一般nginx的error_log会有记录, 看看记录.

**Comment by scm20008** [comment]
2016/03/01 16:55:15 [error] 4794#0: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 10.48.194.97, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "10.48.192.244"

**Comment by qxhy123** [comment]
@scm20008 弱弱的问下你php-fpm启动起来了么

**Comment by scm20008** [comment]
![2016-03-01_173334](https://cloud.githubusercontent.com/assets/639305/13423074/c216ae56-dfd3-11e5-9ebe-d1e6b515b607.png)

@qxhy123

**Comment by scm20008** [comment]
我这边解决了：
fastcgi_pass 127.0.0.1:9000;
换成下面的，
fastcgi_pass unix:/var/run/php5-fpm.sock;


谢谢@qxhy123 @xiezhao @meolu 

官网的文档很不全，这样不好。不要光开发不完善文档，用户会很累的。

**Comment by qxhy123** [comment]
@scm20008 哈哈, 我估摸着就是这个问题.
