### ISSUE TITLE
关于版本控制器里面项目依赖性关系

### ISSUE THREAD

**Issue by Michael754267513** [meolu/walle-web#116]
您好！ 刚试用了下，感觉在QA环境是很不错的，现在我遇到的问题是，假如我有两个项目A,B，他们同时依赖一个项目C，必须C项目首先编译完毕，才能编译A,B项目，遇到这种情况，怎么去解决？

**Comment by meolu** [comment]
是什么语言项目？

我也有类似的项目，如vendor的处理，会放在一个单独的项目中维护，上线的时候再把项目代码和vendor项目合并到一起。vendor更新极少，每次添加composer的时候再发布一次，项目代码上线的时候在高级任务里添加一个copy的语句即可

**Comment by Michael754267513** [comment]
java项目的！ 我现在目前的做法是，利用pre-deploy首先编译这个C项目，然后在编译其他的项目，我这边版本控制器是SVN，发现从svn checkout下来的代码，然后经过maven做集成，最后传送到目标项目，厉害还有许多不需要的文件，这个我觉得可以在walle里面屏蔽掉。

**Comment by meolu** [comment]
嗯，这种做法是可行的，高级任务写得好，可以玩出很多花样。

不需要的文件有两种处理办法：

- 在配置UI的剔除文件列表里添加列表
- 在高级任务处理完之后直接rm

**Comment by Michael754267513** [comment]
目录层次不同，做了集成后，所有的项目都是在target下，这个需要变更路径，现在还在不断的测试，以及尝试，我觉得walle比较好的是开发和QA可以做交互，以往都是通过邮件来确认，比较繁琐

**Comment by meolu** [comment]
更详细的想法，说来听听？我们一直在收集feature

**Comment by Michael754267513** [comment]
今天试用了下，列出一下几个问题，期待改进：

1、提交上线单，里面配置的项目，项目名过长会出界
2、提交上线单，里面显示项目名称的颜色是白色，与web空白处一样，看的眼有点花
3、在我收到一个上线的case，然后点击部署的时候，是否可以把过程显示出来或者在抛出错误的时候直接在web端显示出日志。
4、在创建case的时候，提交开始与提交结束，这个是否整合成一个，就是提交完毕的。

大致就以上问题。feature待我QA环境发布一波在提及，另外这个发布能否添加一个健康监测的机制，就是当其中一个发布ok，然后通过一种方式去监测这个服务的存活，是否可以提供服务，然后在切换下一个。

**Comment by meolu** [comment]
嗯，很好：）

1、3会在下一版本改进
2的调色可能会在整体改版中处理
4没理解，更详细点？

不同的服务监测方式不一样，所以没有统一的方式，或者可以通过高级任务写脚本来实现。我们准备做一个灰度发布这样的一个功能，你看是否可代替此功能？

**Comment by Michael754267513** [comment]
期待中~
到时产品出来了，可以试试，辛苦了～

**Comment by Michael754267513** [comment]
４的话我到时截图，标记出来，下班了，走人～

**Comment by scm20008** [comment]
对于walle，还有哪些功能是jenkins没法被替代的?

如果几个工程(即一个.git仓库)组合在一起成为一个项目，这种形式的，walle好像还不支持。
walle是一个项目对应一个.git仓库，比较费事。

反而对于Jenkins一个job里是可以新建多个.git仓库的。

**Comment by littlehz** [comment]
issue超时关闭
