### ISSUE TITLE
文档安装依赖缺少 php-xml

### ISSUE THREAD

**Issue by littlehz** [meolu/walle-web#117]
[http://doc.huamanshu.com/%E7%93%A6%E5%8A%9B/2.%E5%AE%89%E8%A3%85/%E4%BE%9D%E8%B5%96.html](http://doc.huamanshu.com/%E7%93%A6%E5%8A%9B/2.%E5%AE%89%E8%A3%85/%E4%BE%9D%E8%B5%96.html)

需要增加
`yum install php56w-xml`

~~可能需要在 php.ini 配置~~
~~`extension=dom.so`~~

原因
phpunit 依赖 DOM 扩展，DOM扩展需要 xml 支持。

**Comment by meolu** [comment]
好的，已经加上：）
