### ISSUE TITLE
 ssh yes的那个问题可以通过ssh参数来解决

### ISSUE THREAD

**Issue by wudikua** [meolu/walle-web#118]
ssh -o CheckHostIP=false

**Comment by meolu** [comment]
额，孟君：）
没注意到这个参数，你直接提PR？

**Comment by wudikua** [comment]
我有时间看看。我们公司的部署系统我也做过一段时间，我给你提个功能挺有用。我们那个系统有个自定义脚本的功能，大多数项目除了把git的代码发上去还需要做些别的工作，比如java需要用mvn编译，php有时候部署上去还需要清一些opcache代码才能生效，这些都是自定义脚本里去写的。不过你这弄得也挺好的了，佩服佩服。

**Comment by littlehz** [comment]
在 ansible 分支做了 8e75dd1ada204c900c789f1380bb88d3de29e611
