### ISSUE TITLE
部署svn项目的问题

### ISSUE THREAD

**Issue by wasai9494** [meolu/walle-web#121]
![image](https://cloud.githubusercontent.com/assets/1996727/13518839/14f43004-e20d-11e5-9400-ad0eac1bbc70.png)
为什么部署svn的项目一直报这个错误，求教

![image](https://cloud.githubusercontent.com/assets/1996727/13518876/71d002bc-e20d-11e5-8d9c-4acd3ae70714.png)

**Comment by littlehz** [comment]
宿主机 代码检出仓库，需要创建好，并给php-fpm进程所在的用户有权限

**Comment by wasai9494** [comment]
原来是因为我在提交上线的时候，文件列表里填写了内容导致 多谢

**Comment by wuliqingu** [comment]
文件列表  不用填 具体文件么？
