### ISSUE TITLE
初始化项目 报错 求助各位大神 谢谢

### ISSUE THREAD

**Issue by wuliqingu** [meolu/walle-web#123]
[root@04 walle-web]# ./yii walle/setup
create dir 创建目录...
mkdiring dir: /tmp/walle/
set writable 设置可写权限...
Setting writable: /opt/walle-web/runtime
Setting writable: /opt/walle-web/web/assets
Setting writable: /tmp/walle/
set executable 设置可执行权限...
Setting executable: /opt/walle-web/yii
update database 更新数据库: yii migrate/up ...
Yii Migration Tool (based on Yii v2.0.7-dev)

Error: SQLSTATE[HY000] [2002] 拒绝连接

**Comment by littlehz** [comment]
config/local.php 修改数据库连接。没有写数据库的权限。

**Comment by wuliqingu** [comment]
我检查了一下按照指南里已经改好了 还请帮忙看下是否正确，感谢~ 
 'components' => [
        'db' => [
            'dsn'       => 'mysql:host=127.0.0.1;dbname=walle',
            'username'  => 'root',
            'password'  => '123456',
        ],
