### ISSUE TITLE
mv软链的问题

### ISSUE THREAD

**Issue by wasai9494** [meolu/walle-web#124]
![image](https://cloud.githubusercontent.com/assets/1996727/13594466/92e02e52-e53f-11e5-9312-7abba592215a.png)

为什么mv -fT的时候  加上-T就会吧我目标的文件夹给干掉弄没了？
比如
mv -fT current /home/1/
执行以后 1文件夹就没了，消失了，不知为何

**Comment by littlehz** [comment]
是这样的，目标机 webroot 目录是软链，不需要创建真实存在的目录，只需要创建 webroot 所在的上一级目录。
