### ISSUE TITLE
初始化项目 执行到下面一段时报错  求助各位大神 谢谢

### ISSUE THREAD

**Issue by wuliqingu** [meolu/walle-web#125]
update database 更新数据库: yii migrate/up ...
Yii Migration Tool (based on Yii v2.0.7-dev)

Error: SQLSTATE[HY000] [2003] Can't connect to MySQL server on '127.0.0.1' (111)

请问数据库服务需要单独开启吗？

**Comment by littlehz** [comment]
duplicate #127
