### ISSUE TITLE
配置报错403 Forbidden

### ISSUE THREAD

**Issue by chrislay** [meolu/walle-web#126]
无论怎么配置，配置文件也是一样，在apache和nginx都不行，都报 403 ，很奇怪 ！

**Comment by wuliqingu** [comment]
你好 能否帮我看下下面的报错（初始化项目时报的），万分感谢 
[root@114  walle-web]# ./yii walle/setup
create dir 创建目录...
mkdiring dir: /tmp/walle/
set writable 设置可写权限...
Setting writable: /opt/walle-web/runtime
Setting writable: /opt/walle-web/web/assets
Setting writable: /tmp/walle/
set executable 设置可执行权限...
Setting executable: /opt/walle-web/yii
update database 更新数据库: yii migrate/up ...
Yii Migration Tool (based on Yii v2.0.7-dev)

Error: SQLSTATE[HY000] [2003] Can't connect to MySQL server on '127.0.0.1' (111)

**Comment by wasai9494** [comment]
楼上你是数据库没配置。。。。。本地起mysql了么。

**Comment by wuliqingu** [comment]
数据库配置是按照指南里整的 但是没有单独起mysql 请问怎么启动啊 本人菜鸟 求大神指点

**Comment by wuliqingu** [comment]
弱弱的问一下 MySQL 需要单独安装吗？

**Comment by wasai9494** [comment]
不会。需要自己安装mysql

**Comment by wuliqingu** [comment]
收到  谢谢亲~
