### ISSUE TITLE
请问需要单独安装mysql 吗？代码中会直接带插件吗？

### ISSUE THREAD

**Issue by wuliqingu** [meolu/walle-web#127]
现在初始化项目报错 
[root@4 walle-web]# ./yii walle/setup
……
set executable 设置可执行权限...
Setting executable: /opt/walle-web/yii
update database 更新数据库: yii migrate/up ...
Yii Migration Tool (based on Yii v2.0.7-dev)

Error: SQLSTATE[HY000] [2003] Can't connect to MySQL server on '127.0.0.1' (111)

**Comment by littlehz** [comment]
需要自行安装MySQL
