### ISSUE TITLE
mv -fT 的问题

### ISSUE THREAD

**Issue by tedlz** [meolu/walle-web#128]
我的配置：
```
webroot = /var/www/{project-name}
releases = /var/www/{project-name}/releases
```

然后部署时遇到了和 issues 27一样的问题
https://github.com/meolu/walle-web/issues/27

最后的解决方案：

`webroot` 改为 `/var/www/{project-name}/project`
`releases` 不变

另外也尝试过去掉 `-T`，但是无法正确创建软链

**Comment by littlehz** [comment]
webroot 和 release 分开配不同的目录里，不能是父子目录关系

**Comment by tedlz** [comment]
@littlehz 了解，谢谢解答
