### ISSUE TITLE
svn更新项目问题

### ISSUE THREAD

**Issue by wasai9494** [meolu/walle-web#134]
我在使用svn部署项目的时候，同步文件夹后项目目录总是空的，我修改了如下代码才同步正确
walle-web/components +74

![image](https://cloud.githubusercontent.com/assets/1996727/13738796/4d6dcefc-ea02-11e5-87c2-e12d6c3a2515.png)
不知是否是因为我配置错误的问题，还是什么问题

**Comment by meolu** [comment]
额，应该是你在提交svn上线单的时候，没有在上线文件列表中写文件列表。[svn上线文档](https://walle-web.io/docs/submit-bill.html#二、svn-项目提交上线单)

**Comment by wasai9494** [comment]
默认不写不是全量更新嘛，每次如果要全量需要手动写一个*么

**Comment by littlehz** [comment]
@meolu 水哥看看是限制下 file_list 参数必填，还是做成不填就默认 * ？

**Comment by meolu** [comment]
嗯，我改成默认*吧
