### ISSUE TITLE
svn部署问题

### ISSUE THREAD

**Issue by tomhaoye** [meolu/walle-web#135]
上线全量文件列表直接填*，总是报这个

![image](https://cloud.githubusercontent.com/assets/11913766/13770815/a823c26c-eac4-11e5-8b17-81c23e7ed6ae.png)

看了一下发现是执行到Svn.php line(291)
```
list($file, $version) = StringHelper::explode($file, ' ', true, true);
```
返回的数组长度只有1，是我哪儿做错了还是必须输入版本？

**Comment by littlehz** [comment]
./yii walle/upgrade
升级下walle，已经解决的问题。

**Comment by tomhaoye** [comment]
动作真快，👍

**Comment by tomhaoye** [comment]
谢谢，刚好在前一天拉下来～
