### ISSUE TITLE
请教问题 ？

### ISSUE THREAD

**Issue by knight-zhou** [meolu/walle-web#14]
装你这套软件装了半天我的个汗啊。本想偷懒yum装无奈要php5.4 只好一建安装包了

**Comment by meolu** [comment]
本身不是PHP开发？

**Comment by knight-zhou** [comment]
运维呢 略懂php，还在装这个环境。

**Comment by meolu** [comment]
http://freeloda.blog.51cto.com/2033581/1286592

**Comment by knight-zhou** [comment]
还在安装呢。php环境没什么问题。在跑安装脚本。

**Comment by knight-zhou** [comment]
这个可以和svn一起用吗？以前用的jenkins  。

**Comment by meolu** [comment]
SVN在下一个版本支持，目前只支持Git

**Comment by knight-zhou** [comment]
不能像jenkins 那样 网页执行shell吗？

**Comment by meolu** [comment]
支持执行shell命令、脚本

**Comment by knight-zhou** [comment]
那就行了 到时候我 直接写好shell，然后部署任务，推送任务不就支持svn了。

**Comment by meolu** [comment]
建议你等我下一个版本支持svn吧，这样搞不欢迎：）

**Comment by knight-zhou** [comment]
哈哈哈 不好意思 得罪了 我暂时先用jenkins先

**Comment by knight-zhou** [comment]
改标题了

**Comment by meolu** [comment]
下一个版本发布的时候，在这个issue里通知你吧

**Comment by knight-zhou** [comment]
好的 谢谢 这边反正有邮件提醒。

**Comment by knight-zhou** [comment]
没用git，直接clone zip包下来的，用百度网盘的vendor.tgz，解压到walle-web下的.config/web.php也改了，导入数据也成功了。访问怎么跳到 http://192.168.2.54/site/login 怎么是404？

**Comment by meolu** [comment]
rewrite有没有配置好，根目录要指向walle-web/web

**Comment by knight-zhou** [comment]
readme没有说rewrite把？怎么指？

**Comment by meolu** [comment]
ngnix在Q&A有范例，apache还没有

**Comment by knight-zhou** [comment]
没有huamanshu.com邮箱不可注册：？？？？
 无法登陆？

**Comment by meolu** [comment]
```
vi config/params.php
'mail-suffix'   => [                        // 允许注册的邮箱后缀
    'huamanshu.com',                 // 如果想用qq邮箱注册，请更改为qq.com
]
```

**Comment by knight-zhou** [comment]
激活邮件第一次可以登录，但是后来就登陆不了，忘记密码提示没有这个注册用户？项目部署需要其他管理员审核，但是没看到审核按钮？

**Comment by meolu** [comment]
admin/admin, demo/demo是默认生成的账号，忘记密码要写邮箱，邮箱是admin@xxx.com（不存在）不能重置密码。
你需要配置上面的允许邮箱来注册一个项目管理员，然后由其它项目管理员来审核，比如原始账号admin，项目管理员登录了，在头像旁边会有个消息提醒，按引导的操作就可以审核通过了

**Comment by knight-zhou** [comment]
项目配置的时候只能使用git的地址，我想新建一个项目然后项目列表里面是一个框，然后我一个填写自己的shell脚本。这样好像不行吧？

**Comment by meolu** [comment]
不行，walle是基于版本管理来发布代码的

**Comment by knight-zhou** [comment]
ok谢谢了。

**Comment by meolu** [comment]
svn已经支持了
在development分支上，还没有合并到master，你可以先git checkout development去体验下，顺便反馈下体验：）

**Comment by AnthonyHuang001** [comment]
请问下svn版本的自动化部署,可以出一个版本吗?

**Comment by meolu** [comment]
现在已经更新到development分支了，目前处于验收、fix阶段，如果没有什么问题可能今天晚点的时候合并到master发布：）

**Comment by meolu** [comment]
@AnthonyHuang001 
也欢迎你切到deveopment分支试用，反馈下：）

**Comment by AnthonyHuang001** [comment]
deveopment 数据库创建失败 我把错误信息截图给你
![qq 20151020131510](https://cloud.githubusercontent.com/assets/13654659/10598593/d4a3f516-772c-11e5-845a-96841861266c.png)
![qq 20151020131545](https://cloud.githubusercontent.com/assets/13654659/10598594/d4aa4af6-772c-11e5-9182-f39cf133811e.png)

**Comment by AnthonyHuang001** [comment]
我刚才测试了下 吧下面这个字段修改一下 就可以了 麻烦群主也看一下 辛苦了
![qq 20151020133246](https://cloud.githubusercontent.com/assets/13654659/10598827/1fe17f92-772f-11e5-98e1-b6173d2674b0.png)

**Comment by knight-zhou** [comment]
更新到master上了 说声.

**Comment by meolu** [comment]
已经更新到master，请知晓
