### ISSUE TITLE
瓦力部署bug？？

### ISSUE THREAD

**Issue by huangdongliang** [meolu/walle-web#140]
手动部署和瓦力部署结果不一样：
手动部署：
这个目录中WEB-INF/classes/com/chngc/finance/web/controller是6个class  这个是正确的。
瓦力部署 目录中WEB-INF/classes/com/chngc/finance/web/controller是9个class 这个是错误的。
高级任务如下：

pre_deploy
source /etc/profile

post_deploy
cd {WORKSPACE}-svn/finance-web
mvn clean install
mvn clean package -P test
rm -rf {WORKSPACE}/*
unzip {WORKSPACE}-svn/finance-web/target/ROOT.war -d {WORKSPACE}

pre_release
/data/Shell/finance-web/tomcat stop

post_release
/data/Shell/finance-web/tomcat1 start
如果要截图qq群里可以发给你。

**Comment by meolu** [comment]
手动编译：
![image](https://cloud.githubusercontent.com/assets/4423821/13867394/7d556662-ecf9-11e5-8648-2b19e59b4668.png)

walle编译：
![image](https://cloud.githubusercontent.com/assets/4423821/13867398/89594190-ecf9-11e5-8ef1-61b62dd8ee8f.png)

**Comment by huangdongliang** [comment]
我把php代码中的 walle-web/components/Folder.php  删除工作目录屏蔽掉，执行部署发现通过了，要的代码也正常了。唯独不太一样的是，程序工作目录中比平时多了一个

![Uploading QQ图片20160318134759.png…]()

这个ROOT.war 就是解压前的程序文件。
不过功能不影响使用。
但是现在的问题根源没有扎到。

**Comment by huangdongliang** [comment]
现在的高级任务修改为：
高级任务
pre_deploy
source /etc/profile
post_deploy
cd {WORKSPACE}-svn/finance-web
mvn clean install
mvn clean package -P test
pre_release
/data/Shell/finance-web/tomcat stop
post_release
/data/Shell/finance-web/tomcat1 start
