### ISSUE TITLE
刚部署完的一段时间里面，发现程序有时候读的是新文件有时候读的是旧文件。

### ISSUE THREAD

**Issue by BelieveCode** [meolu/walle-web#145]
刚部署完的一段时间里面，发现程序有时候读的是新文件有时候读的是旧文件。部署的是php程序，没有开启opcache之类的。是不是软连接的问题啊？

**Comment by wuliqingu** [comment]
请问需要单独启动php服务么？如果需要用什么账号启动呢？谢谢

**Comment by littlehz** [comment]
@BelieveCode show me your code，怎么测试读到了旧文件

**Comment by tedlz** [comment]
部署完之后最好重启下nginx php-fpm
不然读取到的就是旧的
