### ISSUE TITLE
启动php-fpm报错，求助各位大神 

### ISSUE THREAD

**Issue by wuliqingu** [meolu/walle-web#148]
[www-php@bjoffa5-113-104 ~]$ service php-fpm start
Starting php-fpm: [23-Mar-2016 13:04:53] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
[23-Mar-2016 13:04:53] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
[  OK  ]

**Comment by littlehz** [comment]
错误提示已经告诉你了需要root启动
