### ISSUE TITLE
用户管理功能欠缺

### ISSUE THREAD

**Issue by caomiao** [meolu/walle-web#153]
- 缺少用户列表功能，即使是管理员也不能修改或者删除其他用户信息，这样如果用户注册错误或者给外人注册会很被动
- 另外密码找回功能，邮件里面的连接点开后提示 “Wrong password reset token.”，不能重置密码

**Comment by sunshineJi** [comment]
已收到，下个版本给出。

**Comment by caomiao** [comment]
用户管理缺少重置密码功能，目前重置密码只能通过邮件方式，但是邮件方式重置密码报错，所以建议用户管理添加重置密码功能
