### ISSUE TITLE
【BUG】为什么开启Ansible后部署会丢失 .*文件

### ISSUE THREAD

**Issue by Barbery** [meolu/walle-web#154]
如题，在post_deploy时我们会生成.env的环境参数，如果开启了Ansible部署模式就会出现丢失 .*文件的情况，关掉Ansible部署就一切正常

**Comment by littlehz** [comment]
稍后会修正这个问题。`tar` 与 `rsync` 不太一样，写 `*` 不会包含 `.`开头的文件。要写 `* .[^.]*`

**Comment by Barbery** [comment]
👍

**Comment by littlehz** [comment]
仔细查看了相关代码，并不是你所说的情况。需要你报告更详细的情况，你的仓库是 git or svn，项目配置、上线单怎么填写的。

rsync/ansible 默认均不会发布 .开头的隐藏文件。

**Comment by Barbery** [comment]
我这边的仓库是git，项目配置的话没什么特别的就是在post_deploy事件里面生成.env的环境变量，例如：
echo "API_DEFAULT_FORMAT=json" >> .env
echo "REDIS_CLUSTER=true" >> .env
echo "SESSION_DRIVER=redis" >> .env

**Comment by littlehz** [comment]
明白了，下一版本解决。

**Comment by meolu** [comment]
@littlehz 好速度

**Comment by littlehz** [comment]
更新到 master
