### ISSUE TITLE
全量部署问题

### ISSUE THREAD

**Issue by huangdongliang** [meolu/walle-web#157]
我全量更新代码，每次都会发现老的jar版本，老的版本1.0.0  1.0.1 都会更新的项目中，从日志上发现：
2016-04-11 11:39:37 -- Run remote command mkdir -p /data/backup/cc-web/20160411-113937 && test -d /data/App/cc-web && cp -rf /data/A
pp/cc-web/* /data/backup/cc-web/20160411-113937/ || echo 1
2016-04-11 11:39:37 -- ---------------------------------
2016-04-11 11:39:37 -- ---- Executing: $ ssh  -T  -p 22 -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no admin@172.168
.100.57 " mkdir -p /data/backup/cc-web/20160411-113937 && test -d /data/App/cc-web && cp -rf /data/App/cc-web/* /data/backup/cc-web/
20160411-113937/ || echo 1 "

我提交上线单选择是： *
高级任务：
cd {WORKSPACE}-svn/cc-web
/data/server/apache-maven-3.2.2/bin/mvn clean package -P test
rm -rf {WORKSPACE}/*
unzip {WORKSPACE}-svn/cc-web/target/ROOT.war -d {WORKSPACE}
最后一步就是最新全量包，会rsync到目标服务器上。也就是说目标服务器已经copy老的项目，新的项目不会覆盖，只能合并，就出现了上面的情况。

**Comment by littlehz** [comment]
目前rsync模式不会删除不在代码仓库中的文件，而开启ansible会删除不在代码仓库中的文件。

**Comment by huangdongliang** [comment]
如果这样，那么对于我每次都全量来说，我只需要在rsync 前面加上 --delete就可以了。
给个建议，增量部署和全量部署，弄成单选按钮的形式。调取对应的值来提交感觉好一点。另外还有一个问题，比如增量部署，上次部署的包里面有一个文件，这次要删除这个文件，那么这个好像只能手动操作了。

**Comment by littlehz** [comment]
好了，讨论确定，下一个版本处理此问题。
全量更新会删除不在代码仓库中的文件，增量更新只发布指定文件不删除任何文件。

**Comment by littlehz** [comment]
已解决，更新到master

**Comment by huangdongliang** [comment]
很赞，群里已经看到有人截图了，因为现在我用的项目已经用到生产了，不敢随便升级，等稳定后我再升级。非常感谢你们团队的贡献。
