### ISSUE TITLE
安装完成，但是用户 无法登录。

### ISSUE THREAD

**Issue by zhangkaka** [meolu/walle-web#160]
1.安装 已经完成，注册用户 已经写用数据库，但总提示“用户名/密码不对”
2.如果选择重置密码，总提示wrong password token!!

**Comment by zhangkaka** [comment]
Wrong password reset token.

**Comment by zhangkaka** [comment]
Could not complete registration
You either supplied an invalid confirmation link or the link has meanwhile expired. Please contact our support under service@huamanshu.com.

**Comment by sapser** [comment]
同样遇到这个问题..

**Comment by wu0407** [comment]
我也遇到这个问题，我的密码里有@符号就不行，应该是特殊字符没有处理导致的

**Comment by wu0407** [comment]
@littlehz

**Comment by zhangkaka** [comment]
admin/admin就可以了！

**Comment by wu0407** [comment]
注册的用户会出现，php大神看下代码，密码哪里处理，肯定没有转义

**Comment by littlehz** [comment]
还没仔细看，等晚上试试
