### ISSUE TITLE
高级任务的疑问

### ISSUE THREAD

**Issue by tedlz** [meolu/walle-web#161]
首先log没报错，宿主机和目标机是同一个，配置里面目标机器用户是root
问题1：
pre_releases：
service nginx stop
service php-fpm stop

post_releases：
service nginx start
service php-fpm start

如果这么设置的话，进度条走到代码检出的时候就把php-fpm 和nginx停止了
然后就走不下去了，服务器上看也没启动

问题2：
如果只在
post_releases：
service nginx restart
service php-fpm restart

可以走到最后一步，然后也走不下去
php-fpm用pgrep看PID是改变的，应该是重新启动了？nginx没有变

**Comment by tedlz** [comment]
可以用sh脚本解决吗？该怎么写呢？

**Comment by tedlz** [comment]
在线等了两天，作者你在哪……

**Comment by tedlz** [comment]
自己尝试了sh脚本不行。sudoers里面无论如何配置也不行

**Comment by tedlz** [comment]
急求高级任务详细教程，有没有人啊，急……

**Comment by tedlz** [comment]
在post_releases里面这样写
/etc/init.d/php-fpm restart
/etc/init.d/nginx restart
也不行
sudo /etc/init.d/php-fpm restart
sudo /etc/init.d/nginx restart
同样不行
求解

**Comment by meolu** [comment]
原因在于service需要root权限，非要这样做的话，得需要操作目标机的用户为root，但不推荐的。这问题是我最头疼的，一直有用户有这种需求，而限于php用户的安全性不能满足；如果你愿意等一两个月，后面会有解决方案。

**Comment by tedlz** [comment]
@meolu 问题是我的目标机的用户确实是root
然后就走不下去了

另外还有个问题，开启了ansible之后，部署到releases下的目录权限变成了root，直接导致一些写操作有问题
关掉ansible之后再部署，releases下的目录权限就是www，完全没问题

**Comment by tedlz** [comment]
@meolu 我尝试过
sh xxx.sh
和
php restart_service.php
都不行，全部都是到最后一步走不下去

**Comment by tedlz** [comment]
@meolu 这个问题很重要，因为公司的API涉及到多台服务器，我总不能部署好了去机器上挨个重启服务吧
且我是root目标机用户

已经在线等了几天终于盼到你回复
能否给个解决方案，walle版本110

**Comment by sunyongliang** [comment]
@tedlz  我现在项目上用的nginx和php-fpm启动用户是www用户，部署用户也是www用户，设置高级任务重启服务是没有问题的，如果有问题可以尝试使用sudo去执行重启任务。

**Comment by meolu** [comment]
如 @sunyongliang 所言，现在多数有这种需求的用户都是这种方式实现，需要把www用户加入root组，可以sudo -i无密码切换。

**Comment by tedlz** [comment]
@sunyongliang @meolu 
我把www加入visudo
设置NOPASSWD:ALL
目标机用户www
post_releases设置sudo service php-fpm restart && sudo service nginx restart
还是卡最后一步

nginx和php-fpm很确认都是www，配置检测也通过
把post_releases改为service php-fpm restart && service nginx restart则提示权限问题
大侠们帮我看下还有哪里有问题么？

**Comment by tedlz** [comment]
sudo -i
service php-fpm restart
service nginx restart
貌似也不行……

**Comment by tedlz** [comment]
也试了
sudo -i service php-fpm restart
sudo -i service nginx restart
仍旧到卡最后一步

**Comment by tedlz** [comment]
@meolu @sunyongliang 
两条命令单独测了下
现在可以通过www用户sudo -i service nginx restart单独启动nginx了，可以部署成功
但是php-fpm没办法，是宿主机和目标机同一台机器的原因吗？

**Comment by tedlz** [comment]
@meolu @sunyongliang 
确实目标机和宿主机不能相同
相同最多只能做到重启nginx，并不能重启php-fpm
我把宿主机和目标机分开，可以用
sudo -i service php-fpm restart
sudo -i service nginx restart
重启成功

希望关闭issues的时候能把我测试出来的这些坑补进官方文档中
让后面的用户少踩坑

**Comment by littlehz** [comment]
总结下你说的问题。
1、开启关闭ansible发布文件，会出现属组不同的情况。这个将来的版本会修正成无论是否开启ansible，发布之后的文件目录属组均为 `目标机用户`
2、宿主机和目标机为同一台机器，执行 service php-fpm restart，是不可能完成的任务。walle本身允许在php-fpm进程下，把自己结束了重启，还要得到重启的返回结果，对不起，walle已经被重启退出了。
3、不建议nginx restart，建议使用nginx reload。不中断HTTP请求
4、不建议使用php-fpm restart，建议只清空opcache缓存。不中断HTTP请求。ref #109

**Comment by tedlz** [comment]
@littlehz 十分感谢
之所以重启php-fpm和nginx是因为我不了解部署成功后，要重启哪个才能更改软链接
自己还未进一步测试，应该是nginx的锅了？

**Comment by tedlz** [comment]
刚试了一下
nginx只reload的话好像载入的是nginx.conf文件
不知道网站的配置文件受不受影响
而且开发机没开opcache
只reload nginx的话，貌似软链没有改过去，只能restart么？

**Comment by tedlz** [comment]
@meolu @sunyongliang @littlehz 
ansible貌似有bug，在不明情况下，关掉它之后才能提示检测成功
否则提示3条
1、宿主机ssh没加入到目标机
2、ansible ping的错误
3、目标机www-root/XXX没权限

**Comment by tedlz** [comment]
@meolu @littlehz @sunyongliang 
又发现问题了，www用户下：
sudo -i service nginx restart
可以执行成功
sudo -i service nginx reload 进度条到同步至服务器之前报错

直接service nginx reload可以成功，但是经过测试并没有reload
