### ISSUE TITLE
开启ansible部署，releases下的项目目录权限变为root，不能执行写入代码，关闭ansible后部署，releases下的项目目录权限为www，正常

### ISSUE THREAD

**Issue by tedlz** [meolu/walle-web#165]
如题……

**Comment by tedlz** [comment]
补充下，标题可能有歧义
开启后部署，项目可以访问，但是项目中的比如mkdir之类的写入代码，不能执行，提示权限问题
关闭后部署，一切正常

**Comment by tedlz** [comment]
目标机用户是root那部署的就是root，但是你们如果决定解决
https://github.com/meolu/walle-web/issues/161
6楼的问题的话就必须要注意下这个问题……

**Comment by littlehz** [comment]
ref #161，在这个 issue 讨论解决问题
