### ISSUE TITLE
为什么发布时要重新下载所有svn，而不是更新

### ISSUE THREAD

**Issue by libao2235** [meolu/walle-web#168]
为什么发布时要重新下载所有svn，而不是更新
![image](https://cloud.githubusercontent.com/assets/12504429/14739560/ea68a4da-08ba-11e6-9aeb-51a9e4a26727.png)

![image](https://cloud.githubusercontent.com/assets/12504429/14739515/8ba88a8c-08ba-11e6-9615-f2284336287f.png)

**Comment by littlehz** [comment]
更新到master
