### ISSUE TITLE
composer里面的版本号不明确

### ISSUE THREAD

**Issue by mrgeneralgoo** [meolu/walle-web#17]
"yiisoft/yii2": ">=2.4"
这样的写法不明确，会报错。
"yiisoft/yii2": "2.0.6",
改成这样就ok了，不知道是我配置还是参数的原因，composer国内全量镜像。

**Comment by meolu** [comment]
composer update下，没问题的

**Comment by meolu** [comment]
不过，提醒我想起minimum-stability需要改下

**Comment by mrgeneralgoo** [comment]
get～正常尝试使用中。

**Comment by meolu** [comment]
应该是 composer self-update
