### ISSUE TITLE
Error: could not find driver

### ISSUE THREAD

**Issue by hubinjie** [meolu/walle-web#171]
[root@xxxxx walle-web]# ./yii walle/setup 
create dir 创建目录...
mkdiring dir: /tmp/walle/
mkdiring dir: /alidata/www/default/walle/walle-web/runtime/ansible_hosts/
mkdiring dir: /alidata/www/default/walle/walle-web/vendor/bower/jquery/dist
set writable 设置可写权限...
Setting writable: /alidata/www/default/walle/walle-web/runtime
Setting writable: /alidata/www/default/walle/walle-web/web/assets
Setting writable: /tmp/walle/
Setting writable: /alidata/www/default/walle/walle-web/runtime/ansible_hosts/
set executable 设置可执行权限...
Setting executable: /alidata/www/default/walle/walle-web/yii
update database 更新数据库: yii migrate/up ...
Yii Migration Tool (based on Yii v2.0.7)

Error: could not find driver

**Comment by littlehz** [comment]
http://www.walle-web.io/docs/troubleshooting.html
