### ISSUE TITLE
代码发布

### ISSUE THREAD

**Issue by lgh8820** [meolu/walle-web#176]
发布代码的时候，svn服务器的要上线代码删除了一些文件，然后发布目标主机代码还是一样，没有删除呢？这怎么设置，才和宿主机代码一致

**Comment by littlehz** [comment]
暂时不会同步，下一个版本计划实施

**Comment by lgh8820** [comment]
OK，大赞一个先

**Comment by littlehz** [comment]
已完成

**Comment by lgh8820** [comment]
java代码发布一直没有成功，宿主机的mvn工具配置好了，命令行可以编译打包，在高级任务测试不成功，关键是命令到底要怎么写？
