### ISSUE TITLE
【请教】新建项目后检测不通过

### ISSUE THREAD

**Issue by wanghong940821** [meolu/walle-web#177]
大家好！我遇到了新建项目后检测不通过的问题，请帮下忙！
我是把gitlab和walle都部署在了同一台 CentOS6.5的机器上，部署的代码也是在这台机器上。
php 进程用户是 root。
我将 root 用户的 id_rsa.pub 里的 key 添加到了 gitlab 的 deploy_keys 里。
也将 root 用户的id_rsa.pub 里的 key 添加到了root 用户的authorized_keys里（因为我的宿主机和目的主机是同一个机器），
我使用如下的两条命令自检也是通过的。

```
git clone  gitlab里的工程的ssh地址
ssh root@127.0.0.1
```
第一条命令是直接进行 clone 的，第二条命令是直接就连接成功了的。都没有让输入密码，说明自检也是通过了的。

我设置的代码检出仓库为：/data/deploy，通过 root 用户给予了777的权限.
目标机器的webroot为：/usr/local/apache/htdocs/，也是通过 root 用户给予了777的权限的。
目标机器的机器列表填写的是：127.0.0.1
创建项目后，使用 walle 的检测选项却还是报错如下：

```
宿主机代码检出检测出错，请确认把php进程用户的ssh-key加入git的deploy-keys列表。
目标机器检测出错，请确认php进程用户ssh-key加入目标机器的root用户ssh-key信任列表。
目标机器检测出错，请确认root有目标机器发布版本库/usr/local/apache/htdocs/写入权限。
```
请问是怎么回事？

**Comment by littlehz** [comment]
如果你是用apache的，那默认情况下没有php进程，要看apache的进程用户，不会用root作为apache的工作进程，你只是用root启动了apache

在apache的工作进程用户下配置git deploy-keys和ssh-key

**Comment by wanghong940821** [comment]
我输入如下命令：

```
ps aux|grep php
```
终端显示为：

```
root     25563  0.0  0.0 103304   848 pts/0    D+   13:54   0:00 grep php
```
然后输入如下命令：

```
ps aux|grep httpd
```

终端显示为：

```
root     25567  0.0  0.0 103320   904 pts/0    S+   13:54   0:00 grep httpd
```

都是root 用户，而且我的系统上也没有其它用户的。

**Comment by wanghong940821** [comment]
求人解答呀

**Comment by littlehz** [comment]
这是 grep 进程，并没有出现 php 和 httpd 进程
