### ISSUE TITLE
部署nodejs程序卡住

### ISSUE THREAD

**Issue by yanghuan2016** [meolu/walle-web#178]
我用walle部署nodejs，代码同步到服务器后需要执行npm install安装依赖包，很多都是从国外站点下载，比较耗时，部署到这里的时候会一直卡在这里，通过重定向npm的日志发现npm已经安装结束，但是部署仍然卡在这里，是否是程序有执行超时的设置

**Comment by littlehz** [comment]
php web执行命令，有删除超时设置
1、nginx.conf fastcgi timeout设置
2、php-fpm.conf timeout的设置
3、php.ini timeout的设置

不过是不是不应该每次发布代码都 npm install？是否可以考虑一次npm install 放在另外的目录，每次发布的时候软链过来？
