### ISSUE TITLE
建议增加多个账号可以管理同样的项目，增加管理员的完全发布和回滚权限

### ISSUE THREAD

**Issue by tedlz** [meolu/walle-web#179]
1、现在别人部署上线的，管理员用户无法回滚
2、某个管理员账号创建的项目，别人看不到，也无法管理

所以现在我们这么用的
单用户

**Comment by littlehz** [comment]
目前用户管理和用户功能这块是比较欠缺，还在计划中

**Comment by littlehz** [comment]
issue超时关闭
