### ISSUE TITLE
小白咨询下用户上传的静态资源怎么处理的

### ISSUE THREAD

**Issue by pangdahua** [meolu/walle-web#180]
现在有个问题是这样的 以前用了开源的cms开发了一个业务，里面有各种文件缓存和上传的资源
现在使用walle的话我感觉会有个问题由于walle线上使用了软链，文件缓存和一些上传的文件都在根目录下
请问您是怎么解决的
还是一开始的时候就对这块做了拆分。

**Comment by littlehz** [comment]
cms架构需要更新了，这个架构的问题在于不支持分布式，和walle发布其实没有多大的关系。
1、用户上传的内容应当使用分布式存储，或者使用七牛、又拍云这样的云存储
2、数据缓存使用redis或者其他k/v，不要使用文件缓存
3、模板编译缓存存临时文件，每次发布这些临时文件丢失，自动更新
4、session改用redis、mysql或者加密cookie，不要使用file session

如果你的系统不想支持分布式，不想大修改，只是为了能用walle发布。那么编写高级任务，把这些数据缓存放在非webroot目录，高级任务执行ln -s软链到webroot下的某个目录。

**Comment by pangdahua** [comment]
非常感谢！

**Comment by littlehz** [comment]
补充：
5、程序运行日志，写入到非仓库目录
6、配置文件，生产环境可以是 xxx.config.production，而测试环境可以是 xxx.config.development，发布代码高级任务配置 xxx.config.production 软链至 xxx.config。程序读取配置文件使用 xxx.config，可以支持生产环境和开发环境

**Comment by jc91715** [comment]
怎么解决这样的问题

第一次运行 composer install 后，

第二次就直接使用第一次 vendor文件夹

目前正在接触瓦力，对于这个问题，有没有小伙伴已经解决了，减少些解决这个问题的时间
