### ISSUE TITLE
希望能够添加自动化测试部分

### ISSUE THREAD

**Issue by hezll** [meolu/walle-web#183]
非常简单易用
希望如jenkins一样添加automation生成测试结果等功能

前期可以考虑对yii的codeception 测试框架支持
后面可以考虑支持junit等等java测试框架

**Comment by littlehz** [comment]
具体点？

**Comment by hezll** [comment]
可能说针对自动化这个提法不太准确，应该说增加以下两个功能之后，就可以配置自动化测试的任务

功能：
1.计划任务，定时执行部署，同时支持Github hook
2.发邮件通知支持模板设定，可以将程序部署后运行生成的或者测试框架部署运行后生成的report  作为邮件内容发给相关用户报告。

这样等于用户可以将测试的自动化加进来，通过在发布后触发测试或者daily run的方式，保证系统的稳定性。

举例，用户创建一个自动化测试项目的部署。通过计划任务定期执行生并成测试报告，每次部署代码的任务执行完之后触发这个任务。

**Comment by cnxzcxy** [comment]
如果反过来想，增加瓦力api，以便jenkins在执行任务的过程中，进行调用，如何？

**Comment by littlehz** [comment]
walle提供api是在考虑中

**Comment by hezll** [comment]
通过jenkins调用瓦力api当然也不错。但是这个会不会降低walle的应用范围。walle的目标不应该是轻量级的jenkins么？哈哈
