### ISSUE TITLE
增量上线建议、版本选取建议

### ISSUE THREAD

**Issue by yang59324** [meolu/walle-web#184]
1、建议增量上线不用手动填写要上线的文件名称，可以通过svn lookup change 确定版本中需要上线哪些文件。
2、建议版本选取可以选择多条。因为如果只能选一个版本，上线版本多的情况下，需要多次提交才能完成上线。

**Comment by littlehz** [comment]
1、下个小版本实现
2、不支持，一个版本就是这个时刻整个仓库的完整状态

**Comment by littlehz** [comment]
issue超时关闭
