### ISSUE TITLE
[task]建议在执行任务时，记录任务的持续时间

### ISSUE THREAD

**Issue by fredyj** [meolu/walle-web#186]
### 出发点

每次构建部署的时候，执行时间是个考量因素
### 现状

当前只有任务的开始时间，记录在 task.updated_at 中。
每一步的记录会体现在 record.duration
### 预期

希望能够在上线单列表中增加以下三功能
- 上线单的持续时间；
- 上线单的每一步骤 持续时间详情；
- 上线单的持续时间的历史趋势( 类似 jenkins 的 buildTimeTrend)；

**Comment by littlehz** [comment]
issue超时关闭
