### ISSUE TITLE
【建议】显示发布文件的列表和测试、预上线、上线使用一个任务号

### ISSUE THREAD

**Issue by qinlodestar** [meolu/walle-web#188]

**Comment by littlehz** [comment]
详细描述下？

**Comment by qinlodestar** [comment]
1. 现在上线文件之后，自己和审核人员都不能看到有哪些上线的文件。
2. 测试、预上线、上线要提交三次，才能上线成功，应该使用一个任务号。
3. 每个任务号需要一个驳回的功能，否则如果文件上线出错，还需要提交一个新的任务号

**Comment by littlehz** [comment]
对整个walle结构改动太大，暂时不考虑
