### ISSUE TITLE
 安装启动后错误

### ISSUE THREAD

**Issue by jsxy** [meolu/walle-web#189]
这是哪里配置问题？

**Comment by jsxy** [comment]
![1](https://cloud.githubusercontent.com/assets/15187452/15532949/e3d885f6-2294-11e6-9296-24463f732dee.png)
![2](https://cloud.githubusercontent.com/assets/15187452/15532955/e921443a-2294-11e6-9478-de786dd87407.png)

**Comment by jsxy** [comment]
![3](https://cloud.githubusercontent.com/assets/15187452/15533022/363d911a-2295-11e6-9e38-f39e7f682a16.png)

**Comment by littlehz** [comment]
php-fpm 没有启动或者不是9000端口

**Comment by jsxy** [comment]
非常感谢。
为修改李配置php5监听端口  /etc/php5/fpm/pool.d/www.conf把
listen = /var/run/php5-fpm.sock  改为 listen = 127.0.0.1:9000
然后sudo service php5-fpm restart 就好了
