### ISSUE TITLE
初始化部署隔离空间出错

### ISSUE THREAD

**Issue by LookingDreamer** [meolu/walle-web#19]
![image](https://cloud.githubusercontent.com/assets/11344104/10692379/bbf6423c-79c3-11e5-9691-0daecf40b834.png)

**Comment by meolu** [comment]
是用svn？

**Comment by LookingDreamer** [comment]
对

**Comment by meolu** [comment]
麻烦点配置操作栏的【检测】看报什么错，另权限已设置？

**Comment by LookingDreamer** [comment]
嗯 正在检测  谢谢
