### ISSUE TITLE
经常发生发布上线卡在ansible解压文件成功后，在要执行pre-release之前

### ISSUE THREAD

**Issue by wu0407** [meolu/walle-web#192]
1. 最后卡主时日志显示

·2016-06-06 18:57:07 -- ---------------------------------
2016-06-06 18:57:07 -- ---- Executing: $ ANSIBLE_SSH_ARGS='-o UserKnownHostsFi
le=/dev/null -o StrictHostKeyChecking=no -o CheckHostIP=false' ansible 'all' -
u 'qmuser' -m shell -a 'tar --preserve-permissions --touch --no-same-owner -xz
f /app/data/releases/pc/20160606-185501.tar.gz -C /app/data/releases/pc/201606
06-185501' -i '/opt/dev/walle-web/runtime/ansible_hosts/project_3' -f 30 -T 12
00
2016-06-06 18:57:38 -- 10.105.107.196 | success | rc=0 >>
.....
10.105.87.237 | success | rc=0 >>·

2016-06-06 18:57:38 -- ---------------------------------

2.通过php-status观察到，php-fpm已经处理完请求，处理时间差不多150多秒，但是前端进度条，卡在那边
3.php最大执行时间设置是20分钟，不是这个问题

**Comment by littlehz** [comment]
点部署按钮前，打开 chrome 的网络请求，检查 start-deploy 的这个请求，是否 peding 完成后 502 超时，还是正常完成。

**Comment by wu0407** [comment]
已经找到原因了
卡在controllers\WalleController.php第474行的Record::saveRecord:
`    private function _transmission() {

        $sTime = Command::getMs();

        if (Project::getAnsibleStatus()) {
            // ansible copy
            $this->walleFolder->ansibleCopyFiles($this->conf, $this->task);
        } else {
            // 循环 scp
            $this->walleFolder->scpCopyFiles($this->conf, $this->task);
        }

        // 记录执行时间
        $duration = Command::getMs() - $sTime;

        Record::saveRecord($this->walleFolder, $this->task->id, Record::ACTION_SYNC, $duration);

        return true;
    }`
并且在runtime/logs/app.log，发现了
`2016-06-07 22:55:46 [180.167.75.66][14][-][error][yii\db\Exception] exception
'PDOException' with message 'SQLSTATE[HY000]: General error: 2006 MySQL server
 has gone away' in /opt/dev/walle-web/vendor/yiisoft/yii2/db/Command.php:781
Stack trace:
......
Next exception 'yii\db\Exception' with message 'SQLSTATE[HY000]: General error
: 2006 MySQL server has gone away
The SQL being executed was: UPDATE `task` SET `status`=4 WHERE `id`=1046' in /
opt/dev/walle-web/vendor/yiisoft/yii2/db/Schema.php:628
Stack trace:`

发现php连接mysql一直没有断开，而更新任务状态重用了这个连接，而mysql超时时间为120秒，所以更新状态失败，无法继续执行下面任务。

解决方法:
第一种:增大mysql的wait_time
第二种:等待大神改代码，变成新建mysql连接，并及时关闭。

**Comment by littlehz** [comment]
wait_timeout 太短，业务都会受影响。如果在web层重连mysql，容易导致mysql雪崩。内网通信尽量都设计成长连接方式，TCP连接需要三次握手、断开需要四次挥手，内网通信没必要主动断开连接，浪费这么多次连接的消耗。

wait_timeout应当在 1800 ~ 3600 比较合理，只是起到保护性的作用，避免某些进程死了连接一直还在。wait_timeout影响的并不是SQL语句执行时间，而是连接进程的未操作闲置时间。
