### ISSUE TITLE
最终的webroot使用软连接对PHP的__FILE__带来的影响

### ISSUE THREAD

**Issue by gloomyzerg** [meolu/walle-web#194]
今天调试一个程序 
因为walle的webroot最终是以软连接的方式发布的,而php的 `__FILE__` 读取的是源文件的绝对路径
由此带来了一个问题,例如
webroot 为 /www/php
/www/php/a.php 
`
  <?php
  define(DIR_ROOT,dirname(dirname(__FILE__)));
  include DIR_ROOT."/b.php";
`
b.php 的路径应该为 /www/b.php

由于采用了软连接 `dirname(dirname(__FILE__)) `这里的路径就不再是 /www 而是 releases 设置的路径 也就是软连接的源文件路径 所以就无法加载到b.php

当然php用此方法 定义路径 本身是不可取的 
用一个绝对路径去取一个相对路径的文件
但在很多开源软件中利用了此方法去取程序的上一级路径
有时可能有很多目录需要部署在同一个路径下  然后相互用此方法取上一级路径来找到其他目录 
但此时如果上一级路径中的依赖没有部署在同一git项目中 虽最终发布在同一目录但无法相互加载
此问题和walle本身没有太大关系 但今天遇到这个问题  在此说一下 以备他人遇到时 可参考查询

**Comment by littlehz** [comment]
1、如果你的nginx版本低于1.9，那么__DIR__是 webroot 路径。如果高于1.9，那 __DIR__ 是 release 路径，这是 nginx 的实现。
2、如果依赖 代码仓库自身的文件，那 __DIR__ . '/xxx/xxx' 不会有问题。如果依赖 代码仓库以外的其他公共文件，那直接写完整路径。外部的依赖不应当写相对路径。
3、php应当遵循 PSR 标准，使用 autoload、composer 载入文件，不应当在代码层面出现 include、require

其他问题参考 https://github.com/meolu/walle-web/issues/109

**Comment by gloomyzerg** [comment]
1.这个确实没有注意到  线上nginx版本没有用到>1.9的 
2.确实这样的外部依赖 不应使用相对路径  只是由于历史原因 有些程序的 确实需要部署在同一级目录 但为了保持程序独立演进 又分布在多个git项目当中 而使用这种方法获取上级目录 来加载依赖
3.现在的程序是应该遵循PSR 标准的,对依赖的管理更加科学,但PSR是近几年才流行起来的标准,有些程序有历史包袱

最后谢谢你的解答 很详细 尤其是第一条 之前确实不知道
