### ISSUE TITLE
日后是否考虑开发API功能

### ISSUE THREAD

**Issue by gloomyzerg** [meolu/walle-web#195]
比如我们现在有一个简单的需求
以前我们利用git的hook来实现自动部署
当开发分支下的代码被合并入master 就会触发测试和部署
walle现在提供了更便捷,和可视化的部署流程及配置.
但有一个问题是每个开发人员需要发布版本时必须要在walle中操作一遍,提交一个上线请求很麻烦
而且开发和版本控制是在本地进行的 而walle是在服务器环境部署的 由于权限问题并不是所有人都可以访问服务器
我们现在用了一个hack的方法 在git hook 触发后 直接向walle的数据库写入上线请求
但此方法始终不是太友好,日后是否考虑提供API来让git hook或者其他系统来结合使用,完成一些功能呢?

**Comment by littlehz** [comment]
有提供API的计划。
但上线发布是很严谨的操作，要预合并、上线前测试、发布、上线后测试等多个环节。即使提供了API也并不建议每次提交到git master都发布上线。

**Comment by gloomyzerg** [comment]
谢谢你的回答
我们现阶段的大体流程是这样
上线前的一些单元测试 我们是利用git hook 来完成的,通过单元测试后的程序会被部署到一个仿真环境下 .然后通过流量复制来导入一些流量做测试,根据程序反馈的一些信息如RT,QPS,CPU占用等一些指标来决定是否最终上线的.
但这其中的一些流程还是可以进行自动化的.比如测试环境到仿真环境的部署,其实无须人工去干预,代码通过了自动化的测试,程序就可以被部署至仿真环境去进行进一步的测试.然后在仿真环境中监控一些关键指标 来决定是否提交上线请求 ,这部分也可以实现自动化.最终的上线的操作是需要运维人员根据服务器的运行情况以及发布的时间节点来决定何时安排上线.这部分可能是需要人工审核.这中间可能还需要一个灰度发布,流控等更复杂的流程.总之不管以什么方式来做部署管理,就像使用walle的初衷都是为了我们更方便更安全更严谨的管理整个代码部署的流程,而流程的自动化往往比人工更可靠高效,不是吗?
当然这种流程并不一定科学,只是我们现阶段的一些做法和理解.
因为之前已经有一些规定好的工作流,使用git hook 加之一些脚本来实现的.但由于运维人员并没有直接参与到代码的管理中.所以最终发布是人工操作从仿真环境部署到线上的.现在有了walle 很好的解决了这个问题.
所以我们就想如果walle能提供一些API,我们就可以很方便的结合之前的一些流程,毕竟所有的流程要推翻重来在实际实施上会有一些阻力的或者说是一个漫长的过程.
说了这么多最后还是感谢walle为我们提供这样简单,便捷的工具

**Comment by littlehz** [comment]
是有API的计划，但可能进度没有这么快。如果你有想法，也可以直接提pr过来 😄

**Comment by gloomyzerg** [comment]
好的 谢谢

**Comment by EastSoup** [comment]
api 有计划了吗，我也想要这个功能
