### ISSUE TITLE
指定某个版本后，自动拉取此版本修改/新增/删除的文件进行上线操作

### ISSUE THREAD

**Issue by tomjamescn** [meolu/walle-web#196]
增量上线模式现在不好用，既然指定了版本，那么就应该是此版本相对于上一次上线版本的修改/新增/删除的所有文件，为什么还要手工录入一次文件列表了？如果有这个功能，可以大大提高上线效率。

**Comment by littlehz** [comment]
没这么简单。
1、并不是每次提交git都会上线，可能会相差多个版本
2、编译型语言发布，不仅仅需要发布提交到git中的文件。需要配合高级任务，生成一些编译后的文件，指定文件上线时，填写把这些文件一起发布。甚至可能不需要发布代码仓库中的文件，而只发布编译后的文件。

指定文件上线，选择版本，是提供一个版本的仓库快照。发布者自行指定哪些文件需要发布。所以也不叫`增量上线`而是`指定文件`

**Comment by tomjamescn** [comment]
恩，是的，我说的主要针对解释性语言，版本库用svn这种特定场景。今后是不是可以考虑针对不同场景，一键安装设置，更方便。
