### ISSUE TITLE
项目配置页交互 BUG

### ISSUE THREAD

**Issue by whjstc** [meolu/walle-web#199]
**项目配置页**
[查看]及[检测]直接点击，出现空白页。
新标签页打开为正常。
![error](https://cloud.githubusercontent.com/assets/1953915/16029625/a510b89c-321c-11e6-8bd2-8a3722a012ac.gif)

**Comment by littlehz** [comment]
还不能重现此问题，你需要打开php.ini的error_reporting和error_log看看错误日志，报告上来具体错误。
如果服务器端没有错误的话，通过chrome控制台检查一下页面js是否有报错。
