### ISSUE TITLE
can't execute this command

### ISSUE THREAD

**Issue by yhtsnda** [meolu/walle-web#2]
excute this command error : composer install global require "fxp/composer-asset-plugin:*"

tip follow as:
Invalid argument global require fxp/composer-asset-plugin:*. Use "composer require global require fxp/composer-asset-plugin:*" instead to add packages to your composer.json.

**Comment by meolu** [comment]
my fault：(

it should be : composer require global require "fxp/composer-asset-plugin:*"

**Comment by telnetor** [comment]
我想问几个问题：
1、我配置好的项目，在"提交上线任务"没显示这个项目，不知还要如何配置
2、我要把代码分发到几台不同的机器上，不知是否支持，这几台机器要如何配置
3、我自己搭建的git服务器是否可用

**Comment by yhtsnda** [comment]
execute this command:
composer require global require "fxp/composer-asset-plugin:*"

error tip:
[UnexpectedValueException]
  Could not parse version constraint require: Invalid version string "require"

**Comment by meolu** [comment]
@telnetor 
1. 配置的时候要把最后一项设置为有效，然后在配置列表里添加成员，然后成员就有权限上线了
2.分发到不同机器没有问题，需要的只是bash，然后就是配置里user都有服务器群的部署目录权限，然后就可以rsync, link等操作了，当然宿主机跟所有目标机器添加信任，可以免密码登录
3.自己的gitlab当然也是支持的，只要是git的服务器，地址写ssh格式地址，添加拉取用户的ssh-key信任即可

**Comment by meolu** [comment]
@yhtsnda 
composer global require "fxp/composer-asset-plugin:*"

**Comment by liky-cn** [comment]
Hi,meolu
1.项目配置中，新建项目，上线方式无法选择tag，是否需要审核也无法选择是，修改设置也无效
2.提交上线任务中，也无法显示其他分支
请问，以上问题怎么解决，谢谢。

**Comment by yhtsnda** [comment]
@meolu  thanks
success

**Comment by meolu** [comment]
@liky-cn 
1.配置项目选择上线方式的时候，branch/tag选择的时候选tag，然后预览确认是否选择tag方式？
2.提交任务时，确认php进程用户的ssh-key有没有添加到该项目的deploy-key的信任列表中？这样才有权限拉git的信息

**Comment by meolu** [comment]
@yhtsnda :+1:

**Comment by liky-cn** [comment]
@meolu 
1.配置项目中找不到预览功能（walle-web 0.4.0），在配置项目的时候，我确认是选择了tag，审核也设置为YES，但都无效
2.已经设置好ssh-key，只能获取到master分支，和master分支的commitID

**Comment by meolu** [comment]
@liky-cn 
1.预览在那个配置列表里，查看那个就是
2.git项目里除了master还有其它分支？

**Comment by liky-cn** [comment]
@meolu 
1.查看的窗口中显示上线方式：branch，审核：0，无法修改这两个设置
2.git项目中有很多分支，在项目开发过程中需要发布其他分支进行功能测试。是否只能显示master？

**Comment by meolu** [comment]
@liky-cn 
1.用的是什么浏览器？
2.你点击选择分支的那个刷新icon看看？

**Comment by liky-cn** [comment]
@meolu 
IE，谷歌都试过了，点击刷新按钮无法刷新出其他分支

**Comment by meolu** [comment]
@liky-cn 
1.可以修改的，我测试了几个机器正常
2.看下浏览器的请求有没有分支列表返回？

**Comment by telnetor** [comment]
/walle/get-branch?projectId=1
/walle/get-commit-history?projectId=1&branch=master

**Comment by liky-cn** [comment]
@meolu 
只看到执行了
@telnetor 
/walle/get-branch?projectId=1
/walle/get-commit-history?projectId=1&branch=master

看不到有列表返回

**Comment by meolu** [comment]
@liky-cn 
去你的宿主机部署仓库里
```
su www                     # php进程用户名称ps aux|grep php看下
cd /var/www/deploy  # 看你的配置宿主机的第一项目录
git pull && git branch -a # 看能取到分支列表不？
git log -20 --pretty="%h - %an %s"  # 同样看下能拉到commit不？
```

**Comment by meolu** [comment]
@telnetor @liky-cn 
加入q群：482939318，截图方便点？

**Comment by jxhsjxhs** [comment]
每次部署拉代码的时候会报  get commit log failed
