### ISSUE TITLE
url路由规则无法定制

### ISSUE THREAD

**Issue by hzted123** [meolu/walle-web#202]
Url::to('@web/user/list')
这种写法会导致用户自行定义路由的时候无法使用
不需要用這種方式來定義
Url::to(['/user/list])  这种方式，使用yii2 默认的方式，便于自定义路由规则

**Comment by littlehz** [comment]
哪里的？帮忙pr过来？

**Comment by hzted123** [comment]
全局的路由配置都是上面的方式 Url::to('@web/user/list')
这是基于根域名的 绝对地址
如果需要配置成一个域名下的子目录 例如 http://localhost/walle-web/  就悲剧了
项目内应该是用相对路径类设置啊

**Comment by littlehz** [comment]
子目录基本不考虑，现代单入口框架基本上都要独占域名
