### ISSUE TITLE
高级功能无法使用，只要使用prerelease等功能，就无法上线

### ISSUE THREAD

**Issue by rainmor** [meolu/walle-web#207]
2016-07-04 21:42:11 [120.52.24.227][1][-][error][yii\base\ErrorException:8] exception 'yii\base\ErrorException' with message 'Undefined index: command' in /home/tomcat/walleweb/controllers/WalleController.php:361
Stack trace:
#0 /home/tomcat/walleweb/controllers/WalleController.php(361): yii\base\ErrorHandler->handleError(8, 'Undefined index...', '/home/tomcat/wa...', 361, Array)
#1 [internal function]: app\controllers\WalleController->actionGetProcess('222')
#2 /home/tomcat/walleweb/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#3 /home/tomcat/walleweb/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#4 /home/tomcat/walleweb/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('get-process', Array)
#5 /home/tomcat/walleweb/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('walle/get-proce...', Array)
#6 /home/tomcat/walleweb/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#7 /home/tomcat/walleweb/web/index.php(11): yii\base\Application->run()
#8 {main}
2016-07-04 21:42:11 [120.52.24.227][1][-][info][application] $_GET = [
    'taskId' => '222'
]

**Comment by rainmor** [comment]
#if [ $UID -ge 500 ]; then
#        exec /usr/bin/script -t 2>/var/log/script/$USER-$UID-`date +%Y%m%d%H%M`.date -a -f - q  /var/log/script/$USER-$UID-`date +%Y%m%d%H%M`.log
#    fi

把这个日志记录功能关掉，我就能正常使用了，谁知道是为什么？

**Comment by littlehz** [comment]
php.ini error reporting 级别调低，不报告 E_NOTICE 提示
