### ISSUE TITLE
高级功能有问题啊

### ISSUE THREAD

**Issue by jason-gao** [meolu/walle-web#208]
报错：代码检出前置任务操作失败::''<br>'. /etc/profile && cd /data/baidu/test.baidu.com/prod/test-v3-20160705-145535 && echo 111 >> /tmp/a.log' 
1. 前置任务：echo 111 >> /tmp/a.log' 
2. 宿主机目录：/data/baidu/test.baidu.com，宿主机上有prod/test-v3目录，压根不存在test-v3-20160705-145535目录，20160705-145535实际上应该是在目标机的目录,感觉目录不对啊

post_deploy也测试了，也报错。。

**Comment by littlehz** [comment]
项目配置看下
