### ISSUE TITLE
walle 打开首页总是报告：对assets目录没有写权限，求帮助。

### ISSUE THREAD

**Issue by showfilv** [meolu/walle-web#211]
Invalid Configuration: The directory is not writable by the Web process: /var/www/html/walle-web/web/assets

[root@localhost walle-web]# ll
总用量 156
drwxrwxrwx.  2 root root    25 7月   4 20:22 assets
drwxrwxrwx.  2 root root  4096 7月   4 20:22 components
-rwxrwxrwx.  1 root root   970 7月   4 20:22 composer.json
-rwxrwxrwx.  1 root root 97587 7月   4 20:50 composer.lock
drwxrwxrwx.  2 root root    71 7月  10 08:42 config
drwxrwxrwx.  3 root root    46 7月   4 20:22 console
drwxrwxrwx.  2 root root  4096 7月   4 20:22 controllers
drwxrwxrwx.  2 root root    59 7月   4 20:22 docker
-rwxrwxrwx.  1 root root   848 7月   4 20:22 Dockerfile
drwxrwxrwx.  2 root root  4096 7月   4 20:22 docs
-rwxrwxrwx.  1 root root 10255 7月   4 20:22 LICENSE
drwxrwxrwx.  3 root root    96 7月   4 20:22 mail
drwxrwxrwx.  4 root root    27 7月   4 20:22 messages
drwxrwxrwx.  2 root root  4096 7月   4 20:22 migrations
drwxrwxrwx.  5 root root  4096 7月   4 20:22 models
-rwxrwxrwx.  1 root root  5050 7月   4 20:22 README.md
drwxrwxrwx.  4 root root    54 7月   4 20:58 runtime
drwxrwxrwx.  3 root root    62 7月   4 20:22 tests
drwxrwxrwx. 22 root root  4096 7月   4 21:03 vendor
drwxrwxrwx.  8 root root    76 7月   4 20:22 views
drwxrwxrwx.  5 root root  4096 7月   9 00:11 web
drwxrwxrwx.  2 root root    22 7月   4 20:22 widgets
-rwxr-xr-x.  1 root root   793 7月   4 20:22 yii

还是报没有权限，我就郁闷了，为什么呢？？所有目录文件权限都给到了777

**Comment by littlehz** [comment]
手动创建这个目录

**Comment by showfilv** [comment]
assets  存在的，权限也是777

**Comment by showfilv** [comment]
assets  存在的，权限也是777

**Comment by showfilv** [comment]
@littlehz assets 存在的，权限也是777

**Comment by huangyisan** [comment]
selinux记得关闭
[root@Master_129 walle]# getenforce 
Enforcing
[root@Master_129 walle]# setenforce 0
