### ISSUE TITLE
post-release无法重启服务

### ISSUE THREAD

**Issue by qiufei230** [meolu/walle-web#212]
在代码同步到目标机器后，且完成了软连接的建立，需要启动python服务，但是无法启动。
post-release的脚本：
cp /var/app/deploy/url_detection/deploy/test/project.cfg /var/app/deploy/url_detection/src/
pgrep -f  detect_main| xargs kill -9
python /var/app/deploy/url_detection/src/detect_main.py --logging=none &

每次执行kill -9命令正常执行，但是后面的python命令就没有执行，但是这整个命令可以在shell正常执行的，请问原因是啥？

**Comment by littlehz** [comment]
切换到php进程用户执行测试下， su - xxxx
一般是环境变量的问题。

**Comment by rainmor** [comment]
post-release貌似只能执行一行命令，
每次我想执行多行shell时，就部署失败。

不过，也许是shell本身执行失败，最近正在研究这个问题。

**Comment by littlehz** [comment]
@rainmor 一行一条，可以多条。但用的是 && ，如果前面的执行出错，后面的会停止。
