### ISSUE TITLE
walle 打开首页总是报告：对assets目录没有写权限，求帮助。

### ISSUE THREAD

**Issue by showfilv** [meolu/walle-web#214]
Invalid Configuration: The directory is not writable by the Web process: /var/www/html/walle-web/web/assets

drwxrwxrwx. 2 root root 4096 7月   4 20:22 ace
drwxrwxrwx. 2 root root    6 7月   6 03:34 assets
drwxrwxrwx. 9 root root   85 7月   4 20:22 dist
-rwxrwxrwx. 1 root root 4286 7月   4 20:22 favicon.ico
-rwxrwxrwx. 1 root root  387 7月   4 20:22 index.php

现在所有文件都是777权限

**Comment by littlehz** [comment]
尝试chown改属主。尝试关闭 selinux

**Comment by rainmor** [comment]
按照经验，你只需要关闭selinux

setenforce 0
