### ISSUE TITLE
关于git代码的增量部署

### ISSUE THREAD

**Issue by liziqing** [meolu/walle-web#216]
貌似现在不能进行git代码的增量部署，就算写了文件以及文件夹名字，也是全量部署。因为代码比较多，每次全量的速度有点慢。
另外是否可以记录上次代码提交的版本，然后选择这次部署的版本，进行版本比较自动做增量发布呢？

**Comment by littlehz** [comment]
选择指定文件，填写列表，就是增量部署。
版本比较也只是生成文件列表，在计划中，但没这么快。
