### ISSUE TITLE
安装完注册新管理员无权限

### ISSUE THREAD

**Issue by hgz6536** [meolu/walle-web#217]
安装完毕注册了新管理员，点击项目配置，提示没被其他项目管理员审核，如何过去超级管理员权限

**Comment by rainmor** [comment]
需要登录admin用户，审核通过其管理员权限

**Comment by hgz6536** [comment]
@rainmor 默认admin 密码是神马

**Comment by littlehz** [comment]
密码也是 admin

**Comment by hgz6536** [comment]
@littlehz 谢谢，请问代码是如何部署到节点服务器的呢？ssh ？还是rsync啊
