### ISSUE TITLE
询问并发的问题

### ISSUE THREAD

**Issue by knightseal** [meolu/walle-web#219]
举例说明：
比如要发布线上10台服务器，那么在发布的时候 是并发同时进行发布的吗？这样子如果是tomcat 这种，上传war 解压，重启tomcat 会有一定几率造成 10台全部下线，请问是否有设置并发数量的设置，
比如10台服务器，并发是5，5台更新完毕，进行下5台更新，或者有类似 的功能，？

如果只能支持串行，时候当机器数量太多的时候会造成发布时间过长？

**Comment by littlehz** [comment]
不用这么麻烦。
开启 ansible，并发传输文件。配置 post_release_delay 参数，让高级任务串行执行。

pre_release 做下负载、停止tomcat操作。
post_release 做启动tomcat、上负载操作。

**Comment by knightseal** [comment]
post_release_delay ,这个在文档里面没有，看名字像是 发布以后 delay时间是吗？
