### ISSUE TITLE
项目比较多时，项目配置列表的显示会错乱

### ISSUE THREAD

**Issue by wh2000292** [meolu/walle-web#221]
项目比较多时，项目配置列表的显示会错乱

**Comment by littlehz** [comment]
截图看看，顺手改的话也可以帮忙pr过来

**Comment by wh2000292** [comment]
![qq 20170713120533](https://user-images.githubusercontent.com/3404396/28149903-a71ddc72-67c3-11e7-9b7d-9a1aeb010f48.png)

**Comment by daxiong123** [comment]
样式其实还好吧

**Comment by littlehz** [comment]
issue超时关闭
