### ISSUE TITLE
htaccess  不是apache伪静态规则么？nginx也适用么，我创建完成是404！

### ISSUE THREAD

**Issue by Johnhacker** [meolu/walle-web#223]
`server {
listen 80;
server_name  auto.pmwiki.net;
access_log off;
index index.html index.htm index.php;
include /usr/local/tengine/conf/rewrite/none.conf;
root /data/wwwroot/walle-web/web;

location ~ [^/]\.php(/|$) {
    #fastcgi_pass remote_php_ip:9000;
    fastcgi_pass unix:/dev/shm/php-cgi.sock;
    fastcgi_index index.php;
    include fastcgi.conf;
    }
location ~ .*\.(gif|jpg|jpeg|png|bmp|swf|flv|ico)$ {
    expires 30d;
    access_log off;
    }
location ~ .*\.(js|css)?$ {
    expires 7d;
    access_log off;
    }
}

`

**Comment by littlehz** [comment]
nginx不能用 .htaccess
没有配置 try_files，参考walle文档。
