### ISSUE TITLE
项目部署问题Git module

### ISSUE THREAD

**Issue by Mark-jk** [meolu/walle-web#224]
因为项目在git里面引用了git module ，发觉pull下来的源码里面不会自动将git module的模块pull下来。

**Comment by littlehz** [comment]
git module 用的比较少了吧。一般都是把公共的组件做成包，放在各种语言的包管理器中管理。比如 npm、composer等，包可以是私有的，也可以是公开的。

如果你需要git module，也可以配合 post_deploy 脚本，再通过额外的命令更新一次。

**Comment by Mark-jk** [comment]
感谢回答，现在我的做法也是在post_deploy里面重新拉取module。
