### ISSUE TITLE
部署提示成功，但是米有执行post-deploy任务

### ISSUE THREAD

**Issue by ly827** [meolu/walle-web#232]
任务也很简单 php run --env=Test
cp run run.phpppppppp;

**Comment by ly827** [comment]
发现原因了 www没有root权限 而mv cp 等命令都需要root权限

**Comment by ly827** [comment]
给力root权限 免密也开了 还是不行。。。

**Comment by ly827** [comment]
再次确认 用php的进程用户在命令行完全没有问题，在walle执行失败

**Comment by ly827** [comment]
自己研究了下 最终问题出在/etc/profile上 去掉这个命令就好啦，但是去掉/etc/profile同步的时候不能启用Ansible

**Comment by littlehz** [comment]
可能还是你配置了一些环节变量、或者bashrc，导致初始化命令出错。
/etc/profile 是肯定需要引入的

**Comment by ly827** [comment]
嗯 看了/etc/profile文件 没发现什么异常 诡异
