### ISSUE TITLE
宿主机的php 运行进程不为www 导致代码走不下去么

### ISSUE THREAD

**Issue by shenboran** [meolu/walle-web#234]
1.宿主机的php 运行进程不为www 导致无法检出代码 （无法修改）

2.如果宿主机 和某一台目标主机 可否进行操作？

**Comment by littlehz** [comment]
1、查看 /tmp/walle的日志，同时切换到 php进程用户 例如 su - xxx ，手动执行 walle日志里的命令，根据报错自行调整
2、可以同一台机器，一样的需要配置 ssh 证书。
