### ISSUE TITLE
每次发布版本都从release中某个版本 做一个软连接到代码发布

### ISSUE THREAD

**Issue by shenboran** [meolu/walle-web#236]
每次发布版本都从release中某个版本 做一个软连接到项目目录中。如果代码文件中存在一个uploads文件上传目录 还有 runtimes 文件则每次更新版本就不会存在 如何解决这个问题？

**Comment by chenjia404** [comment]
发布的时候，有个全量/增量选择，选择『指定文件』

**Comment by littlehz** [comment]
需要分离UGC内容，UGC内容不应当放在代码仓库路径。见  #180
