### ISSUE TITLE
svn项目上线方式选择branche或者tag，部署时svn up出错

### ISSUE THREAD

**Issue by Apollolan** [meolu/walle-web#241]
for 1.2.0版本
项目地址配置为项目根目录：
![htn27 y 4 mc1b 73t9_l3](https://cloud.githubusercontent.com/assets/16299064/17961344/b222f078-6add-11e6-9875-db9d2f27827a.png)
项目结构为：
![jev9g5h dx os c x r](https://cloud.githubusercontent.com/assets/16299064/17961370/cc009af4-6add-11e6-91dc-03577ac78a48.png)
选择branch方式上线，部署时失败报错：
![image](https://cloud.githubusercontent.com/assets/16299064/17961391/fac10c0c-6add-11e6-9206-ab75a5c99e25.png)
查看walle日志显示：
![image](https://cloud.githubusercontent.com/assets/16299064/17961418/2d07a19e-6ade-11e6-8bc6-9f9f76537505.png)
分析发现，cp -rf /data/www/deploy/test/walle_test/branches/branch2 /data/www/deploy/test/walle_test-20160825-160701  这样copy过去之后是不含.svn文件夹的，因为.svn是在/data/www/deploy/test/walle_test/  这一层的，所以cd到/data/www/deploy/test/walle_test-20160825-160701之后再执行svn up，由于找不到.svn，所以会报错

**Comment by Apollolan** [comment]
@littlehz 这个bug有计划修复吗？

**Comment by oyvfhp** [comment]
我也和你一样，出现这个BUG，分析也是这个问题，COPY过去的时候不是完整的版本库。
所以SVN的TAG和branchs发布都不行。

**Comment by oyvfhp** [comment]
@littlehz 这里也有个问题，每次提交上线单都去产生一个新的文件夹，我们项目文件比较大，这很消耗时间的。

**Comment by jkluo** [comment]
请问这个bug修复了吗？我也遇到这个问题了。

**Comment by Alibner** [comment]
我不懂PHP，但是凭经验分析了一下，判断出来应该不是上面几位所说的那个问题

拷贝`cp -rf` 目录过去，是带`.svn`的，我自己也试过；报错估计是另有原因。

执行了
```shell
svn up -q --force -r 0 
```

为何`-r`后面是`0`，我不明白。难道`0`代表的是最新版本？ 

我试了一下，新项目发布的时候，我把`-r 0`给去掉了（直接修改了`php`文件），就通过了。

这里我分析得到，发现这个是执行回滚到指定版本号的时候才用到的。

如果不是回滚，应该不要带`-r` 这个参数，因为更新下来已经是最新的了。 

我搜索查到有关文件如下：

```
./controllers/WalleController.php
./components/Svn.php
./controllers/TaskController.php
./models/Task.php
```

希望 @littlehz 能够看到这个`bug`，有时间就修复一下；谢谢！

**Comment by littlehz** [comment]
issue超时关闭
