### ISSUE TITLE
项目检测不通过

### ISSUE THREAD

**Issue by cheikh-wang** [meolu/walle-web#242]
> 我在一台腾讯云的CentOS 6.5服务器上部署了walle，打算将这台服务器都作为宿主机和目标主机，环境是LAMP环境。

### 创建项目点击检测，报错“宿主机代码检出检测出错，请确认把php进程用户的ssh-key加入git的deploy-keys列表”，而其他另外三个检测项是通过了的。于是我试着切换到deploy用户后，使用如下命令检出github里的代码：

```
git clone 项目的ssh地址
```

成功地检出了代码！

我又试着去开源中国的git仓库里创建了一个私有仓库，并将deploy用户下的id_rsa.pub文件内容加入到了deploy keys，更改walle项目配置里的地址为开源中国里这个仓库的ssh地址，保存后，过一会检测通过了。

所以我纳闷了，为什么我用开源中国的就可以，用github就检测不通过呢？请大家帮帮忙，谢谢！

**Comment by littlehz** [comment]
查看 /tmp/walle/ 下的日志，看看 walle 执行了什么操作，你也一样 su - deploy 切换到 php进程用户执行。
很多时候是由于环境变量问题。ssh上去的环境变量和进程使用的环境变量不一样。
