### ISSUE TITLE
windows本地安装 初始化出现问题

### ISSUE THREAD

**Issue by Camelora** [meolu/walle-web#244]
./yii walle/setup #初始化

出现以下提示：
$ ./yii walle/upgrade
stash save local change 暂存本地修改: git stash save ...
pull code 更新代码: git pull ...
stash pop local change 弹出暂存本地修改: git stash pop ...
create dir 创建目录...
mkdiring dir: /tmp/walle/
mkdiring dir: D:\wamp64\www\walle-web\runtime/ansible_hosts/
mkdiring dir: D:\wamp64\www\walle-web/vendor/bower/jquery/dist
set writable 设置可写权限...
Setting writable: D:\wamp64\www\walle-web/runtime
Setting writable: D:\wamp64\www\walle-web/web/assets
Setting writable: /tmp/walle/
Setting writable: D:\wamp64\www\walle-web\runtime/ansible_hosts/
set executable 设置可执行权限...
Setting executable: D:\wamp64\www\walle-web/yii
update database 更新数据库: yii migrate/up ...
Yii Migration Tool (based on Yii v2.0.7)

Error: could not find driver

**数据库连接配置是：
'db' => [
            'dsn'       => 'mysql:host=127.0.0.1:3307;dbname=walle',
            'username'  => 'root',
            'password'  => '',
        ],

**Comment by littlehz** [comment]
不支持 windows

**Comment by littlehz** [comment]
issue超时关闭
