### ISSUE TITLE
请教如何能自动执行composer update

### ISSUE THREAD

**Issue by cheikh-wang** [meolu/walle-web#245]
我用walle部署基于yii2框架的项目，上线成功后每次都要手动执行composer update命令，我感觉可以在post_release里配置命令，但不知道该怎么写。我这样写是错的：

```
cd {WORKSPACE}
composer update
```

**Comment by littlehz** [comment]
这样写没错，但你要注意环境变量问题，可能你的php不在进程用户的PATH里，具体看 /tmp/walle/ 的日志。当然也不用 cd，默认已经是在 {WORKSPACE} 目录。

**Comment by cheikh-wang** [comment]
/tmp/walle/目录没有输入任何内容
