### ISSUE TITLE
Log 中的Exception

### ISSUE THREAD

**Issue by yeyanchao** [meolu/walle-web#247]
部署时log中出现：
Exception 'yii\base\ErrorException' with message 'Undefined index: command' in /path/to/walle/controllers/WalleController.php:361

并且偶尔会有部署成功但代码未更新的情况。

**Comment by littlehz** [comment]
什么是『部署成功但代码未更新的情况』？

**Comment by yeyanchao** [comment]
代码未更新的问题是指 最后软链切换失败了 新的代码目录已经生成 但是生效的代码路径未更新

**Comment by littlehz** [comment]
issue超时关闭
