### ISSUE TITLE
文件过滤问题

### ISSUE THREAD

**Issue by hanyinfei** [meolu/walle-web#249]
文件过滤路径不生效
例如:
过滤列表如下:
index.php

会将index.php，a/index.php,b/index.php,只要文件名是index.php的都过滤掉

**Comment by javiermu** [comment]
我也有同样的遭遇，会全部递归匹配，能改进下否？

**Comment by daxiong123** [comment]
如果是 /index.php 呢

**Comment by littlehz** [comment]
issue超时关闭
