### ISSUE TITLE
日志目录等自动生成的目录会在发布的时候被清空

### ISSUE THREAD

**Issue by lanjuzi** [meolu/walle-web#251]
虽然可以通过配置文件用绝对路径指向外部目录或者通过发布回调任务来解决，但是感觉还是比较麻烦，比如上传附件的目录。
另外，如果项目有文件被删除，指定文件发布的时候好像是会报错的。

**Comment by littlehz** [comment]
UGC内容本就应当和代码仓库分离。
参考 #180

**Comment by lanjuzi** [comment]
恩啊，前者目前是按照类似 #180 的方法解决的。
那么如果仓库中有文件被删除，这类文件如何指定文件进行更新呢。
