### ISSUE TITLE
安装完毕报这个错误。

### ISSUE THREAD

**Issue by junliepigyao** [meolu/walle-web#253]
安装完成进入首页就报这个。

preg_match(): Compilation failed: this version of PCRE is not compiled with Unicode property support at offset 0

环境详情：http://xxoo.design/

PHP Version 5.6.26

PCRE (Perl Compatible Regular Expressions) Support  enabled
PCRE Library Version    8.31 2012-07-06
Directive   Local Value Master Value
pcre.backtrack_limit    1000000 1000000
pcre.recursion_limit    100000  100000

**Comment by littlehz** [comment]
pcre版本低了，重新编译安装pcre和php

**Comment by junliepigyao** [comment]
我是用的yum安装的php ， 可以指定PCRE Library的版本么？ 
另外我也单独安装了PCRE。但是无法让php使用我单独安装的版本呢？
是必须下载php编译才行么？

**Comment by Tillychang** [comment]
create dir 创建目录...
mkdiring dir: /tmp/walle/
mkdiring dir: /home/report/walle-web-master/walle-web-master/runtime/ansible_hosts/
mkdiring dir: /home/report/walle-web-master/walle-web-master/vendor/bower/jquery/dist
set writable 设置可写权限...
Setting writable: /home/report/walle-web-master/walle-web-master/runtime
Setting writable: /home/report/walle-web-master/walle-web-master/web/assets
Setting writable: /tmp/walle/
Setting writable: /home/report/walle-web-master/walle-web-master/runtime/ansible_hosts/
set executable 设置可执行权限...
Setting executable: /home/report/walle-web-master/walle-web-master/yii
update database 更新数据库: yii migrate/up ...
Yii Migration Tool (based on Yii v2.0.7)

Error: could not find driver


请问这个安装时出在什么问题上？ mysql扩展我已经安装了

**Comment by Tillychang** [comment]
create dir 创建目录...
mkdiring dir: /tmp/walle/
mkdiring dir: /home/report/walle-web-master/walle-web-master/runtime/ansible_hosts/
mkdiring dir: /home/report/walle-web-master/walle-web-master/vendor/bower/jquery/dist
set writable 设置可写权限...
Setting writable: /home/report/walle-web-master/walle-web-master/runtime
Setting writable: /home/report/walle-web-master/walle-web-master/web/assets
Setting writable: /tmp/walle/
Setting writable: /home/report/walle-web-master/walle-web-master/runtime/ansible_hosts/
set executable 设置可执行权限...
Setting executable: /home/report/walle-web-master/walle-web-master/yii
update database 更新数据库: yii migrate/up ...
Yii Migration Tool (based on Yii v2.0.7)

Error: could not find driver


请问这个安装时出在什么问题上？ mysql扩展我已经安装了

**Comment by Tillychang** [comment]
create dir 创建目录...
mkdiring dir: /tmp/walle/
mkdiring dir: /home/report/walle-web-master/walle-web-master/runtime/ansible_hosts/
mkdiring dir: /home/report/walle-web-master/walle-web-master/vendor/bower/jquery/dist
set writable 设置可写权限...
Setting writable: /home/report/walle-web-master/walle-web-master/runtime
Setting writable: /home/report/walle-web-master/walle-web-master/web/assets
Setting writable: /tmp/walle/
Setting writable: /home/report/walle-web-master/walle-web-master/runtime/ansible_hosts/
set executable 设置可执行权限...
Setting executable: /home/report/walle-web-master/walle-web-master/yii
update database 更新数据库: yii migrate/up ...
Yii Migration Tool (based on Yii v2.0.7)

Error: could not find driver


请问这个安装时出在什么问题上？ mysql扩展我已经安装了

**Comment by littlehz** [comment]
你可以尝试用第三方更高版本的 pcre yum 源升级 pcre，再重新 yum 安装 php。
或者手动编译php。
