### ISSUE TITLE
安装完成后，setup报错

### ISSUE THREAD

**Issue by Tillychang** [meolu/walle-web#255]
create dir 创建目录...
mkdiring dir: /tmp/walle/
mkdiring dir: /home/report/walle-web-master/walle-web-master/runtime/ansible_hosts/
mkdiring dir: /home/report/walle-web-master/walle-web-master/vendor/bower/jquery/dist
set writable 设置可写权限...
Setting writable: /home/report/walle-web-master/walle-web-master/runtime
Setting writable: /home/report/walle-web-master/walle-web-master/web/assets
Setting writable: /tmp/walle/
Setting writable: /home/report/walle-web-master/walle-web-master/runtime/ansible_hosts/
set executable 设置可执行权限...
Setting executable: /home/report/walle-web-master/walle-web-master/yii
update database 更新数据库: yii migrate/up ...
Yii Migration Tool (based on Yii v2.0.7)

Error: could not find driver

ps：已经安装mysql扩展。

**Comment by littlehz** [comment]
需要 pdo-mysql 扩展

**Comment by dreamer-chen** [comment]
vendor百度云链接失效了，可以放个安全的链接吧
