### ISSUE TITLE
如何从v0.9.5平滑升级到v1.2.0版本

### ISSUE THREAD

**Issue by BelieveCode** [meolu/walle-web#256]
首先感谢瓦力！！！
已经有10几个代码库在使用瓦力了，今天发现有更新了而且看changelog更新的东西，很多都是我们需要的。所以希望知道怎样可以平滑升级上去，对当前的系统不会有影响。

在升级方面我觉得gogs就做得很好，文档和升级过程都是很友好的。

**Comment by dwercn** [comment]
升级后还是使用原来的数据库数据发现用户表有些字段意思有变化了，还有部署的时候会报错。

**Comment by BelieveCode** [comment]
@meolu 麻烦看下，给个数据迁移步骤哈。

**Comment by littlehz** [comment]
如果你的walle带有 .git。可以执行 `./yii walle/upgrade` 会自动从 git 拉取最新的 walle 代码（可能需要手动解决冲突，一般是 config 文件），也会自动更新数据库。
如果没有 .git，那下载最新的 release 文件，覆盖代码。对比解决 config 文件的变更。执行 `./yii walle/setup`，会自动设置目录权限和数据库更新

**Comment by BelieveCode** [comment]
@littlehz  好的，我试试。可以在升级文档这边加升级步骤。https://walle-web.io/docs/upgrade.html

**Comment by dreamer-chen** [comment]
vendor这个包失效了，好难找啊，放个链接吧

**Comment by dwercn** [comment]
@dreamer-chen  composer用https://packagist.phpcomposer.com，直接composer install还是挺快的。

**Comment by dwercn** [comment]
@littlehz  按你说的方法可以升级成功，测试了三个环境也没有什么问题。
