### ISSUE TITLE
多项目配置问题建议

### ISSUE THREAD

**Issue by snftbmqj** [meolu/walle-web#257]
场景：我有上百个项目，这样会导致提交上线单时项目太多很难查找。
建议：1、自动扫描git/svn中所有项目，通过下拉列表和搜索的方式查找。
           2、如果实现难度大，可否形成人工后台配置列表，前端展示通过下拉列表及搜索。
期待回复，谢谢。

**Comment by littlehz** [comment]
暂无这项计划
