### ISSUE TITLE
Walle基于tag发布的问题

### ISSUE THREAD

**Issue by hanjuntao1** [meolu/walle-web#260]
1. Walle基于tags发布功能，是否支持基于非master分之的发布？
   2.目前试用结果是。在develop分支上打tag发布，在walle上使用基于tags发布时，发布结果显示是tags:master, 而非基于develop分支的tags发布，导致上线失败

**Comment by hanjuntao1** [comment]
补充一下，是gitlab的分支打tag

**Comment by dwercn** [comment]
我们是使用Gogs，在master和非master上面打tag都是可以正常发布的。可以看下/tmp/walle/下面的日志报什么错误下。

**Comment by littlehz** [comment]
把 /tmp/walle 的日志贴出来看看，walle的操作和gitlab里实际tag路径都看看

**Comment by station19** [comment]
不会上线失败吧,只是上线后显示的时候会显示master分支,....我测试过..用master新建分支dev,然后用dev分支打了newfenzhi这个标签,然后上线的时候 在版本选取那里选择好你刚刚打的标签....上线是成功的...
  在你上线选择tag的时候 只要你选择对了,还是会上线成功的......

**Comment by station19** [comment]
目测楼主应该是在gitlab创建tag的时候 默认用了master而非新分支...
