### ISSUE TITLE
权限与目录的配置问题

### ISSUE THREAD

**Issue by Tillychang** [meolu/walle-web#262]
![qq 20161020154324](https://cloud.githubusercontent.com/assets/8511213/19550459/12074852-96dc-11e6-8b12-357d0e3b3dd1.png)
![qq 20161020154341](https://cloud.githubusercontent.com/assets/8511213/19550461/123e74d0-96dc-11e6-854c-30fb4a1c0ea5.png)
![walle](https://cloud.githubusercontent.com/assets/8511213/19550464/13454e62-96dc-11e6-9d79-79a8a90f37bb.png)

涉及目录全部已修改权限为７５５，不知道确切问题在哪，也看不到ｌｏｇ．有没有老司机遇到过这个问题

**Comment by littlehz** [comment]
查看 /tmp/walle 下的日志

**Comment by 0312birdzhang** [comment]
first blood 亮了 :joy:

**Comment by oyvfhp** [comment]
看日志，walle的缓存文件都有分开不同的地方，有几个点。

**Comment by jkluo** [comment]
我也遇到这个问题，日志记录是
![image](https://cloud.githubusercontent.com/assets/12638923/21177478/54ee26ca-c226-11e6-87d6-792b9707e6e0.png)请问你解决了吗？

**Comment by weinshun** [comment]
我也是遇到同样问题

**Comment by littlehz** [comment]
issue超时关闭
