### ISSUE TITLE
话说vendor可否直接加进去

### ISSUE THREAD

**Issue by NowSirius** [meolu/walle-web#264]
同标题
安装那什么劳什子vendor各种坑啊，一直在报错。。受不了了，还有网盘还挂了。。求直接加进去吧。。

**Comment by littlehz** [comment]
正确使用包管理器，网络不行可以用国内镜像或者vpn

**Comment by NowSirius** [comment]
`Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for yiisoft/yii2 2.0.7 -> satisfiable by yiisoft/yii2[2.0.7].
    - yiisoft/yii2 2.0.7 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
  Problem 2
    - yiisoft/yii2 2.0.7 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - yiisoft/yii2-swiftmailer 2.0.5 requires yiisoft/yii2 >=2.0.4 -> satisfiable by yiisoft/yii2[2.0.7].
    - Installation request for yiisoft/yii2-swiftmailer 2.0.5 -> satisfiable by yiisoft/yii2-swiftmailer[2.0.5].

  To enable extensions, verify that they are enabled in those .ini files:
    - /etc/php/7.0/cli/php.ini
    - /etc/php/7.0/cli/conf.d/10-opcache.ini
    - /etc/php/7.0/cli/conf.d/10-pdo.ini
    - /etc/php/7.0/cli/conf.d/20-calendar.ini
    - /etc/php/7.0/cli/conf.d/20-ctype.ini
    - /etc/php/7.0/cli/conf.d/20-exif.ini
    - /etc/php/7.0/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.0/cli/conf.d/20-ftp.ini
    - /etc/php/7.0/cli/conf.d/20-gettext.ini
    - /etc/php/7.0/cli/conf.d/20-iconv.ini
    - /etc/php/7.0/cli/conf.d/20-json.ini
    - /etc/php/7.0/cli/conf.d/20-phar.ini
    - /etc/php/7.0/cli/conf.d/20-posix.ini
    - /etc/php/7.0/cli/conf.d/20-readline.ini
    - /etc/php/7.0/cli/conf.d/20-shmop.ini
    - /etc/php/7.0/cli/conf.d/20-sockets.ini
    - /etc/php/7.0/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.0/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.0/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.0/cli/conf.d/20-tokenizer.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
`

**Comment by NowSirius** [comment]
那个vendor网盘还能给不。。不想用这个Composer 有点伤不起了

**Comment by SHISHENGHUO** [comment]
安装那什么劳什子供应商各种坑啊，一直在报错..受不了了，还有网盘还挂了..求直接加进去吧..

**Comment by daxiong123** [comment]
`
    "repositories": {
        "packagist": {
            "type": "composer",
            "url": "https://packagist.phpcomposer.com"
        }
    }`

可以使用国内的镜像

**Comment by littlehz** [comment]
issue超时关闭
