### ISSUE TITLE
一个问题：支持中控机（跳板机）与否？

### ISSUE THREAD

**Issue by yuqiyi** [meolu/walle-web#265]
从目前的情况来看，是不支持的。但是从我自身感觉，很多企业都是通过中控机去访问线上服务器。
肯定不能把walle部署到中控机上。一方面，代码仓库（svn/git)很可能是在内网，中控机上也无法得下来代码。二则，中控机本身也不能挪作他用。
我们现在是通过jenkins做，内网更代码，编译。然后把包同步到中控机，中控机再执行远程部署，达到目的。
不知道walle有没有这个计划？以后会不会加？

**Comment by littlehz** [comment]
ssh、scp本身就支持 跳板机，不需要额外支持。例如 ~/.ssh/config 的配置
```
Host bg-a
    HostName 1.2.3.4
    Port 22
    User ubuntu
    IdentityFile ~/.ssh/prod-ubuntu

Host web-a
    HostName 192.168.200.2
    Port 22
    User ubuntu
    IdentityFile ~/.ssh/prod-ubuntu
    ProxyCommand ssh -q -W %h:%p bg-a
```

然后你就可以使用 ssh web-a 直接连接到内网的服务器（透过 bg-a），或者 scp /xxx/xxx/x.tar.gz web-a:/tmp/ 这样的操作也支持。

当然，在walle的主机列表里，填写 bg-a 而不是IP地址，那一样的会使用到 ~/.ssh/config 的配置。

**Comment by yuqiyi** [comment]
呃，事实是这样，但是忽略了速度的问题。
比如我们，在国内研发，所有服务器都在国外。速度比较慢。
所以我们之前是先传到中控机，再由中控机的脚本负责分发。这样速度慢只慢在中控机上传那块儿。剩下都在内网，速度就快得多了。
这种方式确实可以，就是速度上来说，会很慢。

**Comment by fireice009** [comment]
@yuqiyi 找到解决办法了嘛？

**Comment by littlehz** [comment]
issue超时关闭
