### ISSUE TITLE
[new feature]上线单文件列表选择功能

### ISSUE THREAD

**Issue by 0312birdzhang** [meolu/walle-web#266]
自己用java山寨了个walle :sweat_smile: ，稍微修改了点界面
希望官方的也可以支持这样的功能，如下（用ztree写的）

![default](https://cloud.githubusercontent.com/assets/1762041/20053844/59614cec-a515-11e6-97b3-685448c19e74.png)

**Comment by littlehz** [comment]
这个效果很好

**Comment by 0312birdzhang** [comment]
@littlehz 不过我没考虑周全，还需要根据选择的分支与版本动态变路径，这样需要将代码拷贝一份，提交的时候还要把这个临时的清理掉，有点不优雅 :joy:

**Comment by littlehz** [comment]
issue超时关闭
