### ISSUE TITLE
目标服务器用户要求可登陆用户才行，这样是不是不安全？

### ISSUE THREAD

**Issue by zhoujun165** [meolu/walle-web#267]
目标服务器用户要求可登陆用户才行，这样是不是不安全？如果部署walle的服务器被黑了，那项目线上环境就直接可以被登录了。

**Comment by littlehz** [comment]
不能登录的用户无法ssh和scp，如果采用其他私有同步协议，一样有漏洞，不如用成熟的ssh证书方案。ssh可以配合vpn、跳板机、ip限制等多重方案加强安全。
另外 walle的服务器建议和生产环境在同一个内网。

**Comment by rainmor** [comment]
如果walle服务器和生产环境一个内网，那么就必须和代码所在环境分开。
如果代码的框架很大的话，不经处理就上传到生产环境，网络卡死人！！！

**Comment by littlehz** [comment]
@rainmor walle的git客户端与git服务器的更新是增量增量，依靠git客户端完成。
如果你的代码仓库很大，更应该将walle与生产服务器放一个内网。walle传输文件到多台生产服务器，即使用ansible，也是N被的文件尺寸传输，并不是传一次就行。

**Comment by zhoujun165** [comment]
我想用rsync同步

**Comment by huyiwill** [comment]
安装配置好了，ssh也好了，权限也是好的,怎么解决这些问题，antisble也安装了


宿主机代码检出检测出错，请确认把php进程用户www的ssh-key加入git的deploy-keys列表。
目标机器检测出错，请确认php进程www用户ssh-key加入目标机器的www-remote用户ssh-key信任列表。

目标机 ansible ping 出错，请检查 ~/.ssh/config 及 ssh 证书配置
目标机器检测出错，请确认www-remote有目标机器发布版本库/data/www/publish写入权限。

**Comment by littlehz** [comment]
issue超时关闭
