### ISSUE TITLE
上线出错－是bug？

### ISSUE THREAD

**Issue by ShoujunChen** [meolu/walle-web#27]
错误信息：

全量更新服务器出错:'10.93.0.4 : mv: cannot overwrite directory '/var/www/publish' with non-directory'
'ssh -p 22 -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no www@10.74.0.4 "sh -c \"ln -sfn /var/www/releases/portal-html/20151028-151637 /var/www/releases/portal-html/current-portal-html.tmp && chown -h www /var/www/releases/portal-html/current-portal-html.tmp && mv -fT /var/www/releases/portal-html/current-portal-html.tmp /var/www/publish\""' 

很明显是最后一段shell有问题：
mv -fT /var/www/releases/portal-html/current-portal-html.tmp /var/www/publish
直接执行也会报错：mv: 无法以非目录来覆盖目录"/var/www/publish"

是bug吧

**Comment by meolu** [comment]
软链接不能覆盖目录 /var/www/publish，`rm -rf  /var/www/publish`

**Comment by ShoujunChen** [comment]
增加定位信息，这是点击部署的时候产生的，如何修复：
![2015-10-28 3 26 04](https://cloud.githubusercontent.com/assets/6425440/10782063/3ddc8a5a-7d88-11e5-865e-a0f06bfa7adf.png)

**Comment by meolu** [comment]
软链接不能覆盖目录 /var/www/publish，`rm -rf /var/www/publish`，重启部署

**Comment by ShoujunChen** [comment]
对的，软链接不能覆盖目录 /var/www/publish，rm -rf /var/www/publish 

但是这个系统生产的脚本，我也没法改它
是重新部署还是重启apache服务？

如果重新部署，不知道问题的根源是什么，根源不找到，重新部署一遍也未必可以啊

**Comment by meolu** [comment]
![image](https://cloud.githubusercontent.com/assets/4423821/10782235/66fa6104-7d89-11e5-9dc2-d99799798982.png)

目标机不应该新建该目录，删除就好，walle会自己新建一个`/var/www/publish`软链

**Comment by ShoujunChen** [comment]
问题解决
多谢，meolu！
