### ISSUE TITLE
删除掉的文件怎么进行增量发布？GIT

### ISSUE THREAD

**Issue by oyvfhp** [meolu/walle-web#271]
GIT中删除掉的文件怎么进行增量发布？
仓库有点大，如果用全量的话会很慢。

**Comment by littlehz** [comment]
1、指定文件发布，只发布传输指定的文件到目标机
2、全量发布，传输整个仓库的文件到目标机，不会保留不在仓库中的文件。

没有你说的功能，walle建议和生产环境在同一个内网，同时把UGC图片、文件分离出仓库。

**Comment by littlehz** [comment]
issue超时关闭

**Comment by wjangelking** [comment]
我这边也遇到这个问题，删除的是代码，所以这个增量发布的问题是不是可以优化，增加一个删除文件列表 @littlehz

**Comment by littlehz** [comment]
@wjangelking 指定文件发布不考虑删除。建议使用全量发布。
