### ISSUE TITLE
安装配置完成了，ssh也加了，但是检测的时候总是报这些错误，后来也安装了ansible,大神这是什么回事啊，跪求

### ISSUE THREAD

**Issue by huyiwill** [meolu/walle-web#272]
宿主机代码检出检测出错，请确认把php进程用户www的ssh-key加入git的deploy-keys列表。

目标机器检测出错，请确认php进程www用户ssh-key加入目标机器的www-remote用户ssh-key信任列表。

目标机 ansible ping 出错，请检查 ~/.ssh/config 及 ssh 证书配置
目标机器检测出错，请确认www-remote有目标机器发布版本库/data/www/publish写入权限。

**Comment by littlehz** [comment]
常见问题
http://www.walle-web.io/docs/install-error.html
http://www.walle-web.io/docs/troubleshooting.html

**Comment by huyiwill** [comment]
ansible的问题文档里面没有，我感觉问题是不是出现在ansible 


发自网易邮箱大师
在2016年11月21日 23:33，littlehz 写道:

常见问题
http://www.walle-web.io/docs/install-error.html
http://www.walle-web.io/docs/troubleshooting.html

**Comment by littlehz** [comment]
ansible是基于ssh，你解决好了第二个 ssh 目标机的错误，自然就会解决ansible的错误

**Comment by station19** [comment]
这个意思是  你要吧 你宿主机的 php进程用户的公钥 放到 git上去这样 宿主机才有权限从gitlab上面拉取项目

**Comment by huyiwill** [comment]
弄好了，原来是机器ssh权限问题


发自网易邮箱大师
在2016年11月30日 15:43，station19 写道:

这个意思是 你要吧 你宿主机的 php进程用户的公钥 放到 git上去这样 宿主机才有权限从gitlab上面拉取项目

**Comment by littlehz** [comment]
issue超时关闭
