### ISSUE TITLE
上线状态显示错误

### ISSUE THREAD

**Issue by ghost** [meolu/walle-web#273]
代码上线完成后，当前状态显示为审核通过，而不是上线完成或回滚
![image](https://cloud.githubusercontent.com/assets/16896107/20554258/938426d8-b195-11e6-92c1-f365047b644a.png)

**Comment by littlehz** [comment]
最后一步上线完成后，会更新任务状态变成上线完成。可能是你的mysql wait_timeout过短，导致最后一步操作数据库时，连接已经关闭了无法修改完成，先检查下mysql的配置

**Comment by littlehz** [comment]
issue超时关闭
