### ISSUE TITLE
www已经可以检出git库，但是。。宿主机代码检出检测出错，请确认把php进程用户www的ssh-key加入git的deploy-keys列表

### ISSUE THREAD

**Issue by outyua** [meolu/walle-web#275]
您好，我的www用户已经能直接git clone那个仓库，用的是gitlab，已经添加了ssh-key，但是还是报这个错误，求解答，谢谢~

**Comment by littlehz** [comment]
用 `su - www` 切换到 www 用户，git clone 仓库测试。注意，一定要 `su - www`

**Comment by aiddroid** [comment]
@littlehz  www，apache 这些用户基本上都是 nologin 的，需要改成 可以login的吗？

**Comment by aiddroid** [comment]
@littlehz  让用户在机器上创建专门的 walle 账号来做代码拉取，部署是不是会更清晰？

**Comment by yuyouwen** [comment]
同遇到该问题，到部署目录下手动删除test这目录就检测通过了。

**Comment by OdeenOnLine** [comment]
同遇到该问题  git clone可以，但是检出检测不通过

**Comment by zhaohehe** [comment]
同问

**Comment by littlehz** [comment]
@aiddroid 比较困难，目前是运行在 php-fpm 下的，指定用户比较难配置。后续2.0版本会启动单独的用户。

**Comment by littlehz** [comment]
issue超时关闭
