### ISSUE TITLE
新建项目时候的用排除文件时候注意事项...(原来如此.搜嘎)

### ISSUE THREAD

**Issue by station19** [meolu/walle-web#278]
发现新建项目时候的排除 比如我排除gitlab上的 conf/conf.php ,
因为项目上的配置文件 平时没人动, 所以不太新,然后我在高级任务的 post_deploy 添加

echo "123' >abc.txt  #成功
cp /data/conf/conf.php conf/conf.php #不成功
cp /data/conf/conf.php conf/conf.php  #成功

唯独这第二行不成功,测试几次都一样..单独测试也是,于是看了/tmp/walle/下面的日志

发现 执行顺序是先 cp 然后再 执行 --exclude   ,这样就导致 把我后面的 cp任务的也给排除掉了.....

希望我的关注是有帮助的啊...希望walle项目越来越完善....

**Comment by littlehz** [comment]
是这样设计的，排除文件在发布阶段排除不发布到目标机。并不是在仓库检出时排除。

**Comment by littlehz** [comment]
issue超时关闭
