### ISSUE TITLE
只支持默认从master拉tag

### ISSUE THREAD

**Issue by liyingchunvip** [meolu/walle-web#279]
我们的工程都是从gitlab的develop分支打的tag，但提交上线单，只看到默认从master分支拉，请修复一下。

**Comment by liyingchunvip** [comment]
可以从提交上线单的标题：test （tag:master 版本号：v0.7.13）可以体现出来，默认拉的是master分支

**Comment by station19** [comment]
我测了下,...虽然现实的是master分支
..但是能读取到你用分支打的那个tag,只要你tag选择争取...拉去文件还是从你的dev分支的tag拉的,会成功

**Comment by littlehz** [comment]
issue超时关闭
