### ISSUE TITLE
生产环境上线方式建议

### ISSUE THREAD

**Issue by xufqing** [meolu/walle-web#282]
有些运维习惯，我们上线部署，只上线到测试环境。
上线生产环境时是从测试环境同步到生产环境。这样可以避免某些开发小伙伴在svn或git突然更新了某些代码。
       如果可能请考虑增加一个选项，不需要从svn或git直接拉取代码，由管理员自行执行脚本进行代码发布~

**Comment by littlehz** [comment]
不考虑这种上线流程，原因如下：

```
这样可以避免某些开发小伙伴在svn或git突然更新了某些代码。
``` 
这是团队规范和约束的问题，不可能存在这种情况。

1、规范来说，任何生产环境的代码，必须严格与 git 仓库一致。即一切提交到 master 的代码，必须短时间内上线，反过来，服务器上在运行的代码一定是在 git 仓库里的。
2、保持 1 的严格同步，是尽可能的避免出现问题。从 git 发布到 测试环境，调试修改，发现有问题，修改代码提交 git，再发布到测试环境，直到测试通过为止。测试通过之后，再从 git 发布到生产环境。所以 git 中的代码一定是经过严格测试的。
3、git 仓库的修改，都会有历史版本记录，可以方便的进行代码审计以及撤销。这其实是更好的防止误操作。
4、直接在测试环境修改的代码，没有副本，从测试环境直接发布到生产环境之后，这部分代码忘记提交怎么办。这有很大的风险。

正确的做法：

是合理使用 git 分支。master 分支表示当前生产环境在使用的代码，不是谁都可以提交的，必须是授权人员才能提交代码到 master。而项目中，根据不同的开发周期，设定多个 开发特性 分支，一般开发人员提交代码到对应的 开发特性 分支。

测试时，可以直接把特性分支发布到测试环境，测试不通过，继续修改特性分支代码提交重新发布到测试环境。测试验收通过，merge 到 master 分支，再把 master 分支发布到预发布环境测试，验收通过，将 master 分支发布到生产环境。

如果你的团队流程不是这样，那应当考虑变更你的团队开发和上线规范，正确使用 git 和 发布系统。

**Comment by littlehz** [comment]
issue超时关闭
