### ISSUE TITLE
unable to login

### ISSUE THREAD

**Issue by passioner-li** [meolu/walle-web#283]
I have installed complete.
but i don't have username&password for login.
and when i try to login with admin&admin ,error happend with:ldap_bind(): Unable to bind to server: Can't contact LDAP server

**Comment by AlfioSaitta** [comment]
Simple edit /config/params.php from

`'user_driver'=>'ldap',`
to 
`'user_driver'=>'',`

**Comment by littlehz** [comment]
or
`'user_driver'=>'local',`
