### ISSUE TITLE
关于如何做到不停服务升级应用

### ISSUE THREAD

**Issue by flysqrlboy** [meolu/walle-web#286]
【walle如何做到不停服升级后端应用】比如nginx做反向代理。我们现在的做法是，把后端应用服务器分为A，B两个子集群（1）先修改nginx仅保留反向到其中A集群，B集群全部更新代码并重启；（2）nginx切换到B集群；（3）A集群全部更新并重启；（4）修改nginx 反向到A和B集群，升级完毕。
我的问题是：walle在发布应用时是如何做到类似的效果的？谢谢！

**Comment by littlehz** [comment]
发布什么语言？

**Comment by jos666** [comment]
1. pre_deploy 执行在nginx upstream 删除在升级的机器
2. post_release 基本测试  在nginx upstream 增加升级后的机器

**Comment by flysqrlboy** [comment]
了解，感谢！
