### ISSUE TITLE
如何使发布中断

### ISSUE THREAD

**Issue by xwqiang** [meolu/walle-web#292]
在发布过程中，由于某些原因 ，我需要做一些校验，如果校验不通过，则阻止后面的流程。比如，检查某个配置文件中是否有abc字段，该如何处理
> 我目前的方法是，通过执行grep configFile|grep abc 如果没有，则执行一个错误的shell脚本，如 cat file-not-exist

**Comment by littlehz** [comment]
shell 脚本的返回状态码不为0，表示错误，就会中断发布了。

**Comment by littlehz** [comment]
issue超时关闭
