### ISSUE TITLE
代码检出目录的问题

### ISSUE THREAD

**Issue by thiskidy** [meolu/walle-web#293]
您好，通过了解瓦力是一个非常好的上线发布系统，目前正在搭建中，不过遇到一个小问题。在部署的时候，报如下问题
上线出错:（
代码检出后置任务操作失败::''
'. /etc/profile && cd /opt/test/test/test/webapp-20170210-104402 && cp /letv/workspace/a /tmp/a && echo "ok, it works fine." > /tmp/a' 

/opt/test/test 是代码检出仓库路径，下载代码的实际变为/opt/test/test/test/webapp，而且没有后面的-20170210-104402。
所以执行cd /opt/test/test/test/webapp-20170210-104402失败，请教这个是什么原因，非常感谢！

**Comment by littlehz** [comment]
/opt/test/test/test/webapp-20170210-104402 是每次发布时，自动产生的临时工作目录。你注意观察，一定会生成类似的目录。

如果后面的高级任务脚本出错（返回码不为0），那么会中断发布，并且删除这个临时工作目录，所以等提示发布失败时，你再找这个临时目录是没有的。

重点检查后面的脚本是否有问题。

不过，也有一些情况是 . /etc/profile 里加载的 .bash_profile、.bashrc 这些在非 tty 下不能用。

**Comment by thiskidy** [comment]
非常感谢littlehz的回复，周末还加班回复，真是辛苦，这个问题已经解决了，我也是还不够细致，没有青春高级任务里的task都是在哪个主机上操作才出错，非常感谢！
