### ISSUE TITLE
适合django代码发布不

### ISSUE THREAD

**Issue by vTNT** [meolu/walle-web#3]
需要重启服务啥的

**Comment by meolu** [comment]
当然可以：）

![部署流程](https://camo.githubusercontent.com/0ad20cce21e071a990944b9de8d46caf08f5a0b4/68747470733a2f2f7261772e6769746875622e636f6d2f6d656f6c752f77616c6c652d7765622f6d61737465722f73637265656e73686f74732f77616c6c652d666c6f772e706e67)

可以在post-release Task里添加重启命令即可

**Comment by vTNT** [comment]
composer install 报错：
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - yiisoft/yii2 2.0.x-dev requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 dev-master requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.6 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.5 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.4 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - Installation request for yiisoft/yii2 >=2.0.4 -> satisfiable by yiisoft/yii2[2.0.4, 2.0.5, 2.0.6, dev-master, 2.0.x-dev].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

**Comment by meolu** [comment]
`composer update`

**Comment by meolu** [comment]
然后再装一次`composer global require "fxp/composer-asset-plugin:*"`

**Comment by vTNT** [comment]
昨天安装调试还是有问题  明天加群 问问下
