### ISSUE TITLE
用户组的概念

### ISSUE THREAD

**Issue by linlihai** [meolu/walle-web#305]
目前在用瓦力碰到一些配置麻烦的事情.  项目比较多, 新入职的员工要配置几十个工程.

是否会考虑引入用户组的概念

**Comment by wushuiyong** [comment]
好问题！

最近在开发一个全新的版本，调研下，如果推出，你是否愿意更新使用？

**Comment by wushuiyong** [comment]
是完全全新的， 底层更换成 python，以前的基本功能保持不变，在之前的基础上新增功能

**Comment by linlihai** [comment]
当然愿意, 啥时候出版本

**Comment by webluoye** [comment]
新版啥时候会发了

**Comment by littlehz** [comment]
issue超时关闭
