### ISSUE TITLE
关于检测不通过

### ISSUE THREAD

**Issue by fucongcong** [meolu/walle-web#306]
当项目过大时，git clone 需要很长时间，导致脚本超时，最后生成了文件夹 但是项目没有clone下来，导致一直报 检测未通过。

附command：
mkdir -p /var/cm/prod/xxx  && cd /var/cm/prod/xxx  && /usr/bin/env git clone -q git@0.0.0.0:xxx.git . && /usr/bin/env git checkout -q master

解决方案 手动clone完 到指定文件夹，在检测 即可通过

**Comment by onecer** [comment]
第一次检测的时候，它会在后台拉取代码。就算是你把页面关了，它进程也一直持续到拉取代码完成。这种情况建议是等待一段时间。用iotop可以看到它读写数据情况。另外一个办法也是你说的，自己先行在指定目录先自己Clone一遍，再执行检测。

**Comment by littlehz** [comment]
issue超时关闭
