### ISSUE TITLE
在通过walle 进行代码发布之后php-fpm 会一直保持及其高的cup占用，有大神遇到过类似的情况吗？

### ISSUE THREAD

**Issue by andrewchen1** [meolu/walle-web#307]
我的walle是部署在docker之中，docker是直接使用的 [idoall/walle-web](https://hub.docker.com/r/idoall/walle-web/).在使用walle部署node项目，在执行yarn命令的时候会使php-fpm 保持极高的cpu资源占用，并且这种情况无法恢复直至重启容器中的php-fpm。现在我把yarn的命令放到目标机中执行，上述情况就不会发生了。请问大神能解释一下大概的原因么 = =!

**Comment by littlehz** [comment]
yarn install 和 yarn run 本来就会很高的CPU占用。一般情况node_modules目录都是忽略的，所以每次发布代码的时候估计都会重新安装
