### ISSUE TITLE
配置没有通过我遇到的一个原因

### ISSUE THREAD

**Issue by shenyang2576** [meolu/walle-web#308]
通过walle配置项目的时候一直检测未通过，甚至已经怀疑人生了。第二天早上醒来才发现ansible的版本太低了，服务器是ubuntu 14.04默认的ansible版本是1.x。请根据ansible官方文档来升级到最新的版本。http://www.ansible.com.cn/docs/intro_installation.html#apt-ubuntu

**Comment by onecer** [comment]
检测的时候，要等代码检出成功才能通过，不会是项目太大拉取了一晚吧。

**Comment by littlehz** [comment]
issue超时关闭
