### ISSUE TITLE
这个系统跟jenkins对比有什么优势、缺点？

### ISSUE THREAD

**Issue by 3tgame** [meolu/walle-web#309]

**Comment by BelieveCode** [comment]
相比jenkins其项目配置更简单、回滚快速、权限分级、用户分组功能更完善；UI界面更优雅，用户体验更人性，大大方便了开发者和管理者的持续交付开发。支持各种web语言代码发布，php、python、java等。

**Comment by littlehz** [comment]
issue超时关闭
