### ISSUE TITLE
部署无法访问

### ISSUE THREAD

**Issue by zzvv** [meolu/walle-web#31]
部署完成,访问502. 没找到工程下log路径,无法定位问题

**Comment by zzvv** [comment]
packages-dev": null,
     "aliases": [],
     "minimum-stability": "stable",
    "prefer-stable": false,
     "prefer-lowest": false,
     "platform": {
        "php": ">=5.4.0"
     },
    "platform-dev": []

**Comment by meolu** [comment]
502是没安装完整，大多是因为 vendor没安装，tail下 php-error

**Comment by zzvv** [comment]
额.弱弱的请教下,怎么配置..囧~ 我不是phper




  
  Sent with zzcv

**Comment by zzvv** [comment]
由于想迅速搭建,so 使用了lnmp.org 的快速安装脚本构建的运行环境.
php -v  -> php 5.4.41

**Comment by meolu** [comment]
php -i|grep error #看下日志在什么目录，然后tail看是什么错误，要不我也定不了位

**Comment by fanzydong531** [comment]
./yii migrate/up 没有 migrate这个目录呢

**Comment by meolu** [comment]
migration目录

**Comment by zzvv** [comment]
没有找到这个目录
运行失败

**Comment by zzvv** [comment]
./yii migrate/up  应该是执行数据导入吧.这步我在安装的时候执行过了,执行成功

**Comment by meolu** [comment]
如果数据库导入成功，nginx配置好就ok了

**Comment by zzvv** [comment]
一共就7张表?

**Comment by zzvv** [comment]
./yii migrate/up 是执行数据导入对吧,我这步执行过了,数据库也可以看到初始化进去的数据了在 2015年11月3日，16:42，huamanshu <notifications@github.com> 写道：migration目录—Reply to this email directly or view it on GitHub.

**Comment by meolu** [comment]
compser安装了没？看php-error吧，直接定位问题

**Comment by zzvv** [comment]
安装成功了~ 我估计是lnmp.io 的一键脚本做了一些 "所谓的优化" 造成的,回头我试试完全手动搭建环境试试看.

 -- 

Sent with Airmail

发件人: huamanshu <notifications@github.com>
回复: meolu/walle-web <reply@reply.github.com>
日期: 2015年11月4日 at 18:21:49
到: meolu/walle-web <walle-web@noreply.github.com>
抄送: Tory <2pporg@gmail.com>
邮件标题:  Re: [walle-web] 部署无法访问 (#31)  

compser安装了没？看php-error吧，直接定位问题
