### ISSUE TITLE
软链接切换版本的问题。

### ISSUE THREAD

**Issue by bluehunters** [meolu/walle-web#312]
我看版本切换时根据软链接的原理切换的，不是文件覆盖。 如果我的目录包含大量的数据。是不是得把img，mp4,这种文件做到其他目录里边去才行。不然部署完了，软链接变了图片也看不到了。可以这样理解吧。

**Comment by daxiong123** [comment]
这种情况最好可以使用一个独立的目录进行挂载，或者直接使用第三方图床，像七牛或者又拍这种服务。

**Comment by sports98** [comment]
个人觉得，你也可以把你的img,mp4这种目录做成目录放在你的项目内。

或者使用walle的后置脚本处理功能，进行下修复

**Comment by onecer** [comment]
1. 将用户生产的静态文件，比如图片，上传的文件等资料，移出项目目录外，每次部署再做个软链接过来。[walle部署高级任务](https://uublog.com/article/20170410/walle-pre-deploy-test/) 利用高级任务，每次部署的时候，删除这些目录，再做软链接。

2. 其实终极就该分离这类静态文件出来，上传到七牛或者其它文件服务器。

**Comment by littlehz** [comment]
参考 #180
