### ISSUE TITLE
使用了一段时间提出几个建议

### ISSUE THREAD

**Issue by pigvip** [meolu/walle-web#314]
1.ansible支持用普通用户登录然后切换成root权限执行指令。
2.ansible的指令可以单次执行每次的指令，这样便于排除命令问题。
3.前台是否增加输出执行结果情况反馈

**Comment by littlehz** [comment]
walle 并不是针对 ansible 开发的，ansible 可以选择开关。为了增加通用性，权限就通过高级任务加 sudo就行。单次执行，关掉 ansible 即可。
而前台增加日志显示，在2.0版本开发。

**Comment by meolu** [comment]
详见[pull-322](https://github.com/meolu/walle-web/pull/322)
