### ISSUE TITLE
提交上线单时无法显示新的tag

### ISSUE THREAD

**Issue by yeyanchao** [meolu/walle-web#316]
项目配置成使用tag上线，当tag较多时（也就十几个）遇到新打的tag 在下拉列表中看不到。

v1.2.0

**Comment by littlehz** [comment]
是看不到只显示最近几个，还是页面有错误？

**Comment by yeyanchao** [comment]
是只显示了之前的十几个，最新的 tag没有显示在下拉列表中，页面没有报错。

**Comment by BelieveCode** [comment]
通过php运行用户到部署机上面手动拉取下tag，看下是什么情况。

**Comment by meolu** [comment]
太多了呗
