### ISSUE TITLE
某种情况下会导致已经上线的项目nginx 404

### ISSUE THREAD

**Issue by wwek** [meolu/walle-web#317]
重现方式
1. 配置项目A，项目B
2. 不同配置： 项目名字，webroot
3. 其他所有配置相同，包括使用同一个git仓库地址， 项目A使用分支1，项目B使用分支2
4. 分别上线1次项目A，项目B
5. 上线项目B 10次

这个时候 项目A nginx 就报404 了

分析原因：
虽然是不同的项目，使用同git不同的分支，但是使用了相同的git仓库地址，那么在 /data/releases 中就是一个文件夹， 里面并不会按照分支区分
默认配置 版本保留数为10，多次发布的项目A删掉了历史发布，然而这个时候却把不想删的项目B的发布版本库给删了

临时解决办法：
办法1：如果是不同项目，使用同一个git仓库的不同分支， 那么  发布版本库 设置为不同的目录
办法2：版本保留数改为 100 （但是同样有风险）

彻底解决：
发布版本库 目录中 再按照分支建立
如： /data/releases/gitp1/20170418-130815
变成：  /data/releases/gitp1/分支/20170418-130815

这样这个问题就彻底解决了

**Comment by onecer** [comment]
这个问题我也遇过。不同项目要放不同文件夹。曾经一天上线多次，把有些项目挤掉了。

复制一份去新目录，先手动建立软连接，然后改walle配置正确指向新目录。下次发布就正常了。

**Comment by littlehz** [comment]
是没考虑这个情况，看样子 releases 分目录不要按 git 仓库名称来分，按 project id 分就好。

**Comment by wwek** [comment]
@littlehz  嗯的，按照project id就可以解决了

**Comment by sn01615** [comment]
这个问题解决了吗？

**Comment by meolu** [comment]
我来在新版解决吧
