### ISSUE TITLE
项目回滚版本出错

### ISSUE THREAD

**Issue by panjiekenan** [meolu/walle-web#32]
回滚后再上线之后代码不变更

**Comment by meolu** [comment]
是回滚第一次的上线？

**Comment by panjiekenan** [comment]
中间的版本。没有回滚成功，再回滚到其他版本，代码版本错乱了

**Comment by meolu** [comment]
截图看下上线列表

**Comment by panjiekenan** [comment]
![1](https://cloud.githubusercontent.com/assets/5036713/10899990/637ce994-8215-11e5-84c6-1d81768c2f41.png)
![2](https://cloud.githubusercontent.com/assets/5036713/10899989/6375266e-8215-11e5-9d9f-ca5abc7fa80d.png)
如图最后一次回滚应该是v1.0.4版本。但是实际的代码版本却是v1.0.3。

**Comment by meolu** [comment]
回滚的意思：这次上线（v0.4.0）无效，回滚到此次上线之前的版本（v0.3.0）
