### ISSUE TITLE
可否在部署页面显示出日志

### ISSUE THREAD

**Issue by smileawei** [meolu/walle-web#323]
在上线java项目的时候 通常需要编译。能否在部署进度条下方 开启显示实时日志。方便在编译失败的时候 看到错误。感谢。

**Comment by Alibner** [comment]
您好，我想咨询下，上线JAVA项目的时候，如何编译呢？ 我看系统里面没有配置编译的地方。还请指导一下

**Comment by smileawei** [comment]
高级任务里，调用shell执行编译。

**Comment by Alibner** [comment]
好的，谢谢！

**Comment by littlehz** [comment]
基于php-fpm的很难实现。walle 2.0 重构应该可以做到这个功能

**Comment by sxwailyc** [comment]
是的，编译的时候也能看到过程就好了
