### ISSUE TITLE
配置邮件服务器错误

### ISSUE THREAD

**Issue by pingink** [meolu/walle-web#324]
stream_socket_enable_crypto(): Peer certificate CN=`*.263.net' did not match expected CN=`smtp.100tal.com'

**Comment by smileawei** [comment]
这个是邮箱smtp服务器ssl证书和域名不符合导致的

**Comment by littlehz** [comment]
SMTP证书错误，如果SMTP不支持ssl加密，需要在配置文件中关掉加密
