### ISSUE TITLE
Visual Studio Team Services 测试失败

### ISSUE THREAD

**Issue by cndiviner** [meolu/walle-web#325]
我们的代码托管在Visual Studio Team Services ，当我们配置好后，用的地址是ssh://leifeitest@leifeitest.visualstudio.com:22/_git/MyFirstProject，检测的时候提示错误：宿主机代码检出检测出错，请确认把php进程用户vagrant的ssh-key加入git的deploy-keys列表。
ssh-key已经添加了，我如果用开源中国的就可以，请教这是什么原因？

**Comment by littlehz** [comment]
使用 sudo su - vagrant 切换到 vagrant 的用户环境，并且执行 git clone 试试报错没
