### ISSUE TITLE
如何部署.env等配置文件

### ISSUE THREAD

**Issue by IIInsomnia** [meolu/walle-web#332]
因为是软连接，不能每次都需要单独处理配置文件吧

**Comment by sn01615** [comment]
放在宿主机上的源码目录即可，会连带拷贝过去的，当然你如果提交到了git，每次post_deploy时，把准备好的.env文件拷贝过去即可。

**Comment by BelieveCode** [comment]
或者直接在 `pre_release` 里面直接添加脚本内容

    echo "<?php define('ENV', 'DEVELOP');//生产环境" > {VERSION}/Conf/env.php

**Comment by littlehz** [comment]
请查看 #180
