### ISSUE TITLE
当从github拉取代码发生冲突时，就无法进行发布操作

### ISSUE THREAD

**Issue by jiingwang** [meolu/walle-web#335]
![error](https://user-images.githubusercontent.com/24888115/27383406-7ad6a552-56bd-11e7-98f3-db7c225ce87d.png)

**Comment by onecer** [comment]
检出仓库的代码别改。改发布的目录的代码临时用用还行。

**Comment by littlehz** [comment]
walle配置的仓库代码应当是不被其他程序修改的，因为要从这个目录拉取最新文件，有缓存速度快些。
walle每次发布的时候，会创建临时工作目录，在 post_deploy 命令里修改需要的内容。
