### ISSUE TITLE
$_ENV里读取配置失败？

### ISSUE THREAD

**Issue by sn01615** [meolu/walle-web#337]

**Comment by littlehz** [comment]
请具体描述问题

**Comment by sn01615** [comment]
我的PHP版本下$_ENV默认不存在，详见https://github.com/meolu/walle-web/pull/338
`if (empty($_ENV)) {
    $_ENV = $_SERVER;
    foreach ($_ENV as $key => $value) {
        if (strpos($key, '_PASS')) {
            $_ENV[$key] = base64_decode($value);
            if ($_ENV[$key] === false) {
                $_ENV[$key] = $value;
            }
        }
    }
}`

**Comment by littlehz** [comment]
这样操作不好吧，php没有$_ENV，应该找php.ini解决，而不是改代码。
