### ISSUE TITLE
前后端协同上线你们是怎么做的？

### ISSUE THREAD

**Issue by minxinqing** [meolu/walle-web#339]
由于前后端上线时间差，在时间差里的访问会由于两端的文件不同步而出现BUG。
前后端协同上线你们是怎么做的？

**Comment by sn01615** [comment]
前后分离，分离为项目即可，或者尝试子项目

**Comment by minxinqing** [comment]
现在就是做了前后端分离，成了2个项目，所以会上线的时候有时间差

**Comment by sn01615** [comment]
用at命令写脚本定时上线如何？

**Comment by qixiaobo** [comment]
非覆盖发布吧
https://my.oschina.net/qixiaobo025/blog/913285 <https://my.oschina.net/qixiaobo025/blog/913285>

**Comment by minxinqing** [comment]
非覆盖发布也会有问题，比如 前端调用接口，此次迭代接口返回的数据格式做了调整，用之前的JS调用现在的接口会出问题，用现在的JS调用之前的接口也会出问题，所以要求同步上线。

**Comment by sn01615** [comment]
后端版本判断 ：)

**Comment by minxinqing** [comment]
我打算改下发布系统，两个项目捆绑在一起发布，等两个项目代码都发上去了之后，再执行修改软链的操作。
谢谢各位。

**Comment by qixiaobo** [comment]
一般来说非覆盖发布已经可以解决一大波问题，后端是否类似于dubbo有版本控制？但是正常来说很难保证所有的调用都能成功，如果调用失败前端check一下当前web版本和服务端是否同步（如果一样说明后端报错），如果不同步说明web端代码过旧不完全兼容直接在前端刷新即可

**Comment by sn01615** [comment]
请问两个人同时上线会有问题吗？

**Comment by ginnerpeace** [comment]
只要不把walle的上线当做最终发布就可以了，这个只构建，自己再做一步所有项目构建后的发布动作。

**Comment by littlehz** [comment]
前后端分离了，这和用手机客户端APP一样的，后端代码应当做到兼容一部分历史版本。
先发布后端，再发布前端。
做了前后端分离，SPA应用，即使同时发布前后端也是无效的，SPA应用，没有刷新前端的代码也还是旧的。

**Comment by littlehz** [comment]
讨论暂告一段落吧，如果有新的想法，欢迎issue

**Comment by sohucw** [comment]
是不是可以考虑一下 k8s滚动更新
