### ISSUE TITLE
部署java程序war包问题

### ISSUE THREAD

**Issue by bobo365** [meolu/walle-web#342]
同一个webroot下有好多war包，此前都是直接上传war自动解压，如果使用walle的话，目标地址不能存在，如何解决这个问题呢？

**Comment by onecer** [comment]
发布去一个特定地方，再用post-deploy高级任务写个脚本复制过去，搞定。

**Comment by bobo365** [comment]
那回退的时候不会受到影响吧？

**Comment by onecer** [comment]
回滚相当重新部署以前版本的东西，应该可以，你可以试试。

**Comment by bobo365** [comment]
好的，我来先试验一下。谢谢。

**Comment by littlehz** [comment]
可以尝试下
