### ISSUE TITLE
“发布版本库”里文件丢失后的回滚问题

### ISSUE THREAD

**Issue by ginnerpeace** [meolu/walle-web#343]
看了一下代码，回滚时若发布版本库没有文件，仍然会直接执行 ln -s 

其实可以判断一下备份文件丢失的情况，若没有文件，就当做重新发布上次commit。
这应该算是健壮性问题，可以在适当的时机考虑一下加进去，支持这种重新构建的回滚方式。

这样的话，表结构可能会更改，就不仅仅是保存上一次的软链号了

**Comment by littlehz** [comment]
是说最近发布的10个版本备份，手动删掉了备份吗？

**Comment by wu0407** [comment]
我觉的回滚历史上某个版本(不是当前版本)，这个功能没有什么意义啊。我已经发布好几个版本，还要重新回滚很早之前的版本，遇到这样需求，应该重新创建上线单，清楚知道自己的要回滚的commit号

**Comment by ginnerpeace** [comment]
em....我当时是看到发布时存了一个字段(是上次构建的目录名)，然后回滚操作是直接取那个字段去创建软链了

假如那个文件夹不在了的话不是就回滚失败吗……

所以意思是可以判断一下要回滚的那个版本还在不在目标机器上，没有的话程序里就用commit id再clone一遍

@wu0407 
不过确实可以重新创建……是我有点吹毛求疵了\_(:з」∠)\_

**Comment by meolu** [comment]
你们说得对。这个应该考虑下
