### ISSUE TITLE
没有灰度发步功能，创建上线不能选择某台机器

### ISSUE THREAD

**Issue by hanlingzhi** [meolu/walle-web#350]

**Comment by BelieveCode** [comment]
我们的做法是将需要做灰度发布的那台服务器先从之前的哪个部署项目里面踢出来，然后重新建copy一个部署项目，就只有这台机器，部署这个项目就可以。

**Comment by daxiong123** [comment]
这个应该会在新版本中有

**Comment by littlehz** [comment]
2.0应该是有这个计划的

**Comment by littlehz** [comment]
这个fork做了一些改进，可以先试试 https://github.com/shopiz/walle-web
