### ISSUE TITLE
 安装失败，Access denied for user 'root'@'122.233.48.9' (using password: YES)

### ISSUE THREAD

**Issue by leedow** [meolu/walle-web#354]
执行./yii walle/setup提示:
Error: SQLSTATE[HY000] [1045] Access denied for user 'root'@'122.233.48.9' (using password: YES)

这个IP什么鬼？找半天也不知道是哪里设置的

**Comment by zGaron** [comment]
这个意思是  拒绝从 122.233.48.9 这个ip 以 root 用户身份登录

原因应该是 数据库 的root 用户没有开 外网访问权限。 
@leedow

**Comment by leedow** [comment]
@zGaron 可这个IP不是我本人设的，我的数据库IP不是这个

**Comment by zGaron** [comment]
是连接的来源， 比如你walle 部署在 A ， 数据库在 B 那个 这个提示的 那个IP对应的是 你的  A 的位置
@leedow

**Comment by zGaron** [comment]
解决办法：
以 root 用户进入数据库服务器：
执行：
create database walle;
grant all privileges on `walle`.* to 'walle'@'%' identified by '××××';

然后修改配置为 用户 walle 密码 ××××（上面你设置的）

**Comment by leedow** [comment]
@zGaron   谢谢，明白了，已解决，不过很奇怪我配置config/web.php中的数据库链接没有用，要改local.php的配置就好了

**Comment by littlehz** [comment]
是用 config/local.php 的配置
