### ISSUE TITLE
执行runLocalCommand没有获取到全部的报错信息

### ISSUE THREAD

**Issue by wyicwx** [meolu/walle-web#355]
我运行项目配置检测的时候svn报错了，但是在日志里没有任何报错信息，仅仅是执行失败了。。我通过在终端里运行传递给runLocalCommand函数的命令时是有显示报错的。。

**Comment by wyicwx** [comment]
分析了下：

`
    public function updateRepo($branch = 'trunk', $svnDir = null) {
        $svnDir = $svnDir ?: Project::getDeployFromDir();
        $dotSvn = rtrim($svnDir, '/') . '/.svn';

        if (file_exists($dotSvn)) {
            // 存在svn目录，直接update
            $cmd[] = sprintf('cd %s ', $svnDir);
            $cmd[] = $this->_getSvnCmd('svn cleanup');
            $cmd[] = $this->_getSvnCmd('svn revert . -q -R');
            $cmd[] = $this->_getSvnCmd('svn up -q --force');
            $command = join(' && ', $cmd);
            return $this->runLocalCommand($command);
        } else {
            // 不存在，则先checkout
            $cmd[] = sprintf('mkdir -p %s ', $svnDir);
            $cmd[] = sprintf('cd %s ', $svnDir);
            $cmd[] = $this->_getSvnCmd(sprintf('svn checkout -q %s .', escapeshellarg($this->getConfig()->repo_url)));
            $command = join(' && ', $cmd);
            return $this->runLocalCommand($command);
        }
    }
`
`components/Svn.php`里的`updateRepo`函数通过&&拼接shell命令

`
    final public function runLocalCommand($command)
    {
        $command = trim($command);
        $this->log('---------------------------------');
        $this->log('---- Executing: $ ' . $command);
        $status = 1;
        $log = '';
        exec($command . ' 2>&1', $log, $status);
        // 执行过的命令
        $this->command = $command;
        // 执行的状态
        $this->status = !$status;
        // 操作日志
        $log = implode(PHP_EOL, $log);
        $this->log = trim($log);
        $this->log($log);
        $this->log('---------------------------------');
        return $this->status;
    }
`
`updateRepo`函数拼接后的command传递给`components/Command.php`里的`runLocalCommand`

在`exec`函数执行前有给command拼接 2>&1，这样做在单条命令下没问题，但是如果是用&&拼接的多条命令，那这边只能获取到最后一条命令的报错信息，前面的命令就获取不到了

**Comment by littlehz** [comment]
没太注意，意思就是拼接多条命令用 ` 2>&1 && ` 替代 ` && `

**Comment by wyicwx** [comment]
@littlehz 是这个意思
