### ISSUE TITLE
将自动生成的webroot软链接改为其他名称

### ISSUE THREAD

**Issue by baiyuchina** [meolu/walle-web#358]
在创建项目中，webroot会在父目录下自动创建个名为webroot的软链接，能否将生成的webroot这个名称改为其他名称。

**Comment by BelieveCode** [comment]
这个名称应该是由你的webroot这个配置值决定的，比如你你的配置值为“/data/wwwroot/platform”，应该就是在”/data/wwwroot/“下面生成”platform“的软链

**Comment by littlehz** [comment]
配置的webroot目录不应当存在，只存在webroot的上级目录即可。webroot是软链，不是真实目录。
