### ISSUE TITLE
部署多台机器列表如何在 pre_release 阶段传递不同的参数

### ISSUE THREAD

**Issue by flyhxg** [meolu/walle-web#359]
部署多个机器IP，在 pre_release  阶段看已经到目标机上了，如何在 pre_release 上传递跟ip一一对应的参数

**Comment by BelieveCode** [comment]
这是要实现什么功能？
已经到了每台目标机器，直接通过脚本获取相应机器的ip，然后通过ip区分参数是否可以？

**Comment by flyhxg** [comment]
嗯，可以，项目传到目标机后，需要远程控制 slb 上下线，但是有多台机器的，就需要在每台机器上都弄个脚本，感觉成本有点大，改项目的话又有点难度
