### ISSUE TITLE
上线错误：

### ISSUE THREAD

**Issue by xuanskyer** [meolu/walle-web#36]
报错信息：
```
上线出错:（
同步文件到服务器出错:'Host key verification failed. rsync: connection unexpectedly closed (0 bytes received so far) [sender] rsync error: error in rsync protocol data stream (code 12) at io.c(600) [sender=3.0.6]'<br>'rsync -avz --rsh="ssh -p 22" /mnt/hgfs/walle_test/test/docs-20151104-145705/ root@192.168.3.177:/tmp/walle_test/release/docs/20151104-145705'
```

宿主机：192.168.3.222
目标机：192.168.3.177
* 已经设置了宿主和目标机之间可以 直接 无密码 ssh登陆成功了。
* /tmp/ 和 /tmp/walle_test目录 都是 777 权限。

**Comment by meolu** [comment]
添加ssh信任了没？

**Comment by xuanskyer** [comment]
添加了。
我看了报错的那个命令里， 宿主主机下并没有`/mnt/hgfs/walle_test/test/docs-20151104-145705/`这个目录。只有`/mnt/hgfs/walle_test/test/docs`目录。是这个原因么？

**Comment by meolu** [comment]
`/mnt/hgfs/walle_test/test/docs-20151104-145705/`会自动生成的
把命令拷出来，手动执行看报什么错。
