### ISSUE TITLE
目标机器权限的问题

### ISSUE THREAD

**Issue by BelieveCode** [meolu/walle-web#360]
我现在是在目标机器添加了"deploy"这个专门用来处理部署的用户，然后给了他sudo权限，然后给予“/bin/chown,/bin/echo,/bin/rm”免登录操作，前面两个在处理后置任务的时候没有问题，有问题的是如果存在需要删除的版本就会出现没有权限的问题，因为那些版本我都会设置成“chown www:www {VERSION}”.对于这个问题要怎么处理？

**Comment by BelieveCode** [comment]
发现这个问题后，我就修改walle的代码，在删除的代码里面也添加 “sudo rm XXX”，这边有设置sudo账号的项目是正常，但是一些之前的没有设置sudo账号的项目就是页面显示部署成功了，但是部署列表那边是显示待部署状态（之前那些项目目录权限都是直接跑在deploy下面，所以不需要sudo权限）。

**Comment by BelieveCode** [comment]
对于这个权限的问题，你们是怎么处理的？

**Comment by BelieveCode** [comment]
@meolu

**Comment by littlehz** [comment]
主流的运维规范是，代码文件属主是发布用户（如publisher），而nginx/apache的进程用户是另外一个（如www、nobody）。保证代码文件对于nginx/apache进程来看是只读的，一定程度上保护代码不被程序漏洞修改。

不要用文件缓存，使用 redis 缓存。
部分ugc内容，要么用dfs分布式存储，要么nfs集中存储。如果实在要本地临时存储，配置目录可写权限，与代码目录区分，临时存储目录不解析php等文件。

**Comment by littlehz** [comment]
关联 #180
