### ISSUE TITLE
提交的时候也有报错

### ISSUE THREAD

**Issue by 727023460** [meolu/walle-web#363]
全量更新服务器出错::'10.121.1.110 : mv: cannot overwrite directory ‘/app/’ with non-directory'
能否将
mv -fT /data/release/ht-game/*.tmp /app
改成
mv -f /data/release/ht-game/*.tmp/*  /app/
好吧，mv不安全，能否用cp -f命令，要是我之前的app目录里面存在用户上传的静态文件，不是一起被覆盖掉了吗

**Comment by littlehz** [comment]
1、配置的webroot不应当存在，会自动创建。
2、静态文件需要分离，不应当存在于代码目录。

**Comment by littlehz** [comment]
ugc 内容分离详见 #180
