### ISSUE TITLE
可以添加“只允许文件”列表吗？

### ISSUE THREAD

**Issue by muunnw** [meolu/walle-web#364]
现在有“排除文件”列表，可以增加一个“只允许文件”列表，达到白名单的效果

**Comment by littlehz** [comment]
发布过程，会在宿主机生成临时工作目录，可以通过post_deploy脚本控制编译的文件、删除不需要的文件等操作。
只把临时工作目录的文件发布到目标机。目标机的webroot目录文件会和这个临时工作目录保持一致，所以怎么修改临时工作目录的文件都可以。
