### ISSUE TITLE
ansible并发数在哪设置？

### ISSUE THREAD

**Issue by auto007** [meolu/walle-web#366]
首先感谢开发者的辛勤劳动！
请问一次传文件到多少个目标主机怎么设置，即ansible -f参数的功能在哪可以调？

**Comment by littlehz** [comment]
基本不用改，已经调试过很多次，是最合适的参数，-f 10 能把带宽跑满，也不会占用太多CPU、内存资源

**Comment by wu0407** [comment]
https://github.com/meolu/walle-web/blob/master/components/Ansible.php#L20
