### ISSUE TITLE
发布用户与线上运行用户不一致，怎么解决呢？

### ISSUE THREAD

**Issue by panpan-zhang** [meolu/walle-web#371]
能不能添加个运行用户呢？
发布用户与线上运行用户不一致，导致
１）目录权限混乱，不易管理
２）容易发生运行权限异常

**Comment by shopiz** [comment]
你可以在项目配置的高级任务中写脚本调整文件/目录权限，需要你当前发布用户有权限修改

**Comment by littlehz** [comment]
基于 php-fpm 的walle，比较难实现此功能。
如果你运维能力比较强，可以配置 独立的 php-fpm pool，nginx 配置 独立的 upstream，就可以给 walle 用单独的运行用户

**Comment by wu0407** [comment]
直接配置发布用户与线上运行用户一致这样就行了，不过看你的运行用户是否允许登陆，这涉及到系统的权限管控
