### ISSUE TITLE
宿主机未安装 ansible，请安装 ansible 或 在项目配置中关闭 ansible。

### ISSUE THREAD

**Issue by CooperHush** [meolu/walle-web#375]
我明明已经安装了 ansible 呀！为什么还是提示这个？
# yum install ansible
Loaded plugins: security
Setting up Install Process
Package ansible-2.3.1.0-1.el6.noarch already installed and latest version
Nothing to do

**Comment by littlehz** [comment]
可能是还不支持2.0以上版本的ansible

**Comment by wu0407** [comment]
我的ansible 2.3.2.0是可以的，先看一下walle的日志，检测时也会输出日志的，是不是运行php的用户，ansible没有加入PATH变量中

**Comment by littlehz** [comment]
我试了下，这个版本的 ansible 并没有问题，可能是环境变量的问题
