### ISSUE TITLE
support docker

### ISSUE THREAD

**Issue by liujingyu** [meolu/walle-web#376]
I write a patch. support v1.2.0: https://gist.github.com/liujingyu/d35202524d0c01a6de5e0b0946e52118
welcome to fork!

**Comment by jialeo** [comment]
@liujingyu 请问怎么用？

**Comment by liujingyu** [comment]
@jialeo 首先把walle-web项目`git clone`下，然后download my gist到项目的根目录(命令v1.2.0.patch),然后，使用`git apply v1.2.0.patch` .

![截图](http://7xla3k.com1.z0.glb.clouddn.com/apple5d361ef15e4ed73ae1a99c1255600222.png)

**Comment by wu0407** [comment]
walle来发布docker感觉不太好，docker还是用编排系统发布比较好，不过小规模是可以用这种方法

**Comment by meolu** [comment]
你们这么说，也有道理
