### ISSUE TITLE
上线发布太慢

### ISSUE THREAD

**Issue by pangxieke** [meolu/walle-web#377]
现公司搭建私有gitlab代码仓库，放在内网网段。
Walle发布系统，也放在内网网段。

发布到内网开发环境时，十分迅速。
但发布到线上环境（AWS），需要20分钟左右。现在代码仓库已经有300M左右。
请问有什么好的方法？
能否完善增量发布方式？在原分支基础上，增量同步文件？

**Comment by littlehz** [comment]
生产环境的 walle 放在 aws 内网，walle 与 git 通过公网同步（防火墙限定ip）。git 有自己的增量控制方法，流量很小，并且有缓存，这样发布速度才快。

**Comment by wu0407** [comment]
这个问题可以关闭了，walle原理不是在目标机器上git pull，而是发布机git pull，打包，传输、解压、软链、清理
