### ISSUE TITLE
项目配置检测一直超时(TMOUT_OUT)504,跪求解决的方案

### ISSUE THREAD

**Issue by zzhtom** [meolu/walle-web#378]
nginx 也添加的相应的配置：
       large_client_header_buffers 4 16k;
        client_max_body_size 300m;
        client_body_buffer_size 128k;
        proxy_connect_timeout 600;
        proxy_read_timeout 600;
        proxy_send_timeout 600;
        proxy_buffer_size 64k;
        proxy_buffers   4 32k;
        proxy_busy_buffers_size 64k;
        proxy_temp_file_write_size 64k;
信息如下：
GET http://127.0.0.1:8080/walle/detection?projectId=1 504 (Gateway Time-out)
2017/09/26 21:57:04 [error] 7490#0: *228 upstream timed out (60: Operation timed out) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "GET /walle/detection?projectId=1 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "127.0.0.1:8080", referrer: "http://127.0.0.1:8080/conf/"
2017/09/26 21:57:04 [error] 7490#0: *228 upstream timed out (60: Operation timed out) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "GET /walle/detection?projectId=1 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "127.0.0.1:8080", referrer: "http://127.0.0.1:8080/conf/"
2017/09/26 21:57:04 [error] 7490#0: *228 upstream timed out (60: Operation timed out) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "GET /walle/detection?projectId=1 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "127.0.0.1:8080", referrer: "http://127.0.0.1:8080/conf/"
GET http://127.0.0.1:8080/walle/detection?projectId=1 504 (Gateway Time-out)

**Comment by wu0407** [comment]
增加fastcgi_read_timeout 150s; 这里150s改成你要的时间

**Comment by amdxypf** [comment]
您好，请问下，之前504超时是什么引起的清楚么？我这里把时间设置长一些依然报超时。感觉像是资源哪里阻塞了或者进入死循环了。
我把mysql重启了也没好，求帮助

**Comment by littlehz** [comment]
504问题一般存在以下几处
1、nginx.conf 的 fastcgi_read_timeout 以及关联的 fastcgi_XXX_timeout
2、php-fpm.conf 的 request_terminate_timeout
3、php.ini 的 max_execution_time
