### ISSUE TITLE
文件都存在为什么无法复制，父目录和当前目录都有权限

### ISSUE THREAD

**Issue by litaonet** [meolu/walle-web#379]
全量更新服务器出错::'18*.6*.**.*0 | FAILED | rc=1 >> mv: cannot overwrite directory ?/data/wwwroot/temp? with non-directory'
'ANSIBLE_SSH_ARGS='-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o CheckHostIP=false' ansible 'all' -u 'www' -m shell -a 'ln -sfn /data/deploy/www.baidu.cn/20171009-213000 /data/deploy/www.baidu.cn/current-www.baidu.cn.tmp && chown -h www /data/deploy/www.baidu.cn/current-www.baidu.cn.tmp && mv -fT /data/deploy/www.baidu.cn/current-www.baidu.cn.tmp /data/wwwroot' -i '/data/wwwroot/walle-web/runtime/ansible_hosts/project_1' -f 10 -T 600'

**Comment by littlehz** [comment]
删除 webroot 目录
