### ISSUE TITLE
shell执行过程中有部分脚本执行报错，python项目执行 source api/bin/activate 报错

### ISSUE THREAD

**Issue by ritchietam** [meolu/walle-web#380]
1，python项目执行 source api/bin/activate 报错
2，使用了别名的命令也报 命令找不到

**Comment by littlehz** [comment]
source 是 bin/bash 的命令，不要用 source
别名的命令，配置在 env，不要配置在 .bashrc

**Comment by littlehz** [comment]
1、可以使用 . api/bin/activate 表示 source api/bin/activate
