### ISSUE TITLE
发布成功，但显示部署失败

### ISSUE THREAD

**Issue by haoyuxy** [meolu/walle-web#381]
状态码是500，release脚本执行成功的，服务也起来了，就是显示部署失败，不知道什么问题，大神能指点一下吗，谢谢！
POST /walle/start-deploy HTTP/1.1" 500

-----------------------------------
post_releaseEnd...
2017-10-10 14:46:08 -- ---------------------------------
2017-10-10 14:46:08 -- ---------------------------------
2017-10-10 14:46:08 -- ---- Executing: $ echo "ERROR：项目部署失败！开始清理版本目录

**Comment by haoyuxy** [comment]
日志就是上面那一段，发布脚本执行完，然后打印了个 ERROR：项目部署失败！开始清理版本目录，就没有了

**Comment by littlehz** [comment]
500 错误，是 php 语法错误，极有可能是修改了某些 php config 文件产生的语法错误。也有可能是没有安装某些依赖，但是又关闭了错误提示，导致只显示500而没有具体错误信息。

另外，“项目部署失败！开始清理版本目录” 这几个字，好像没有在 walle 代码中出现过。

**Comment by haoyuxy** [comment]
嗯，谢啦，我检查一下。
