### ISSUE TITLE
vendor 百度网盘链接失效

### ISSUE THREAD

**Issue by bb7788** [meolu/walle-web#382]
如果国内环境安装极慢，可以直接下载vendor解压到项目根目录
这个链接失效了 http://pan.baidu.com/s/1c0wiuyc

**Comment by chenjia404** [comment]
请使用Composer中国镜像 https://pkg.phpcomposer.com/#how-to-use-packagist-mirror

**Comment by littlehz** [comment]
不再提供单独 vendor 下载，建议使用 composer 国内镜像。
