### ISSUE TITLE
请问php7以上版本是否支持

### ISSUE THREAD

**Issue by kanganxi** [meolu/walle-web#385]
目前我的运行环境是php7.17

**Comment by sn01615** [comment]
当然可以

**Comment by kanganxi** [comment]
@sn01615  谢谢

**Comment by kanganxi** [comment]
@sn01615 兄弟请问您在php7下部署是否正常，我以前在php5.5成功过，现在php7.1数据库都能写入，但是访问500

**Comment by sn01615** [comment]
@kanganxi 正常，看下PHP错误日志或框架的错误日志分析下出错在哪里，一般是php扩展和权限的问题

**Comment by kanganxi** [comment]
@sn01615 谢谢兄弟指点，已搞定

**Comment by kanganxi** [comment]
@sn01615 兄弟不好意思打扰了，我想请教一下：1:宿主机和目标可以是同一台机器么？2：是否支持coding上的git项目部署

**Comment by littlehz** [comment]
php 7.1 正常使用
