### ISSUE TITLE
未在版本库中的代码，如何管理

### ISSUE THREAD

**Issue by yantao1226** [meolu/walle-web#387]
我这里有一个需求，具体操作如下：
1. 我的项目中有个storege 目录（该目录下，还有其他目录及文件，且不能丢），但是该目录在项目中是忽略的。首次创建项目时，我手动创建了该目录。
2.在第二次发布版本后，由于软链换了路径。所以，我上一版本中的 storege 目录，就丢失了。这个怎么处理呢？

**Comment by hegoku** [comment]
同问，比如保存上传图片的文件夹就在项目目录下，每次发布后这个目录就变成新的了。。。

**Comment by peterziv** [comment]
1. 采用脚本作处理
2.设计上数据和应用分离

Thanks,
Peter

在 2017年11月9日，16:48，Jack <notifications@github.com<mailto:notifications@github.com>> 写道：


同问，比如保存上传图片的文件夹就在项目目录下，每次发布后这个目录就变成新的了。。。

**Comment by littlehz** [comment]
代码与存储分离，按 #180 操作
