### ISSUE TITLE
给walle部署机器部署代码

### ISSUE THREAD

**Issue by yeer** [meolu/walle-web#388]
需要给walle部署机器部署代码，并且需要reload php-fpm，现在的问题就是reload walle的php-fpm会导致walle部署不成功（卡在最后一步）。
不知道walle有没有什么功能能解决这个问题？

**Comment by littlehz** [comment]
参考 #109 

如果 qps 不大，可以关闭 opcache。如果 qps 比较高，担心影响性能，可以执行高级任务 opcache_reset() 而不是 reload

**Comment by onecer** [comment]
把walle放docker里面运行。

**Comment by yeer** [comment]
我是用atd实现了延迟一分钟重启fpm
at -f at.commond.restart.fpm.sh now + 1 minutes

有空了我试下opcache_reset()
