### ISSUE TITLE
能不能关闭邮件功能？

### ISSUE THREAD

**Issue by hegoku** [meolu/walle-web#389]
能不能添加新用户的时候不要发送邮件？因为没有邮件服务器，所以每次添加新用户都报错

Connection could not be established with host smtp.exmail.qq.com [php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution #0]

**Comment by littlehz** [comment]
目前没有关闭的功能，可以配外部的smtp服务器

**Comment by onecer** [comment]
检查配置吧，我也是用的exmail.qq.com.目前我们都是用的exmail.qq.com发送的。另外你用扣扣的邮件服务器也是可以的。关键是你要申请SMTP的专用密码。别用自己邮箱登录密码。

**Comment by hegoku** [comment]
好

**Comment by shijunti19** [comment]
不知道是你们的密码还是服务器配置，根本无法连接

**Comment by onecer** [comment]
@shijunti19 不可能的.建议配置个QQ邮箱发信也行啊. 或者直接添加到数据库 改字段激活也行的.开源了,自己动手吧.

**Comment by shijunti19** [comment]
@onecer 恩，我还是改数据库吧，一直显示超时，端口也开了，本地好好的！

**Comment by onecer** [comment]
@shijunti19 兄die,阿里云么.安全组端口开了没.
