### ISSUE TITLE
同一个git地址 不同的分支发布到两个项目默认情况下会出问题

### ISSUE THREAD

**Issue by sn01615** [meolu/walle-web#390]
除非在pre_deploy里git checkout 分支

**Comment by sn01615** [comment]
这样是不行的，checkout后有些没有提交的文件会消失

**Comment by sn01615** [comment]
还要再写脚本拷贝回去

**Comment by sn01615** [comment]
项目直接的隔离性有问题

**Comment by littlehz** [comment]
这是什么需求，什么场景用到？

**Comment by sn01615** [comment]
一个git里有 多个分支 每个分支 属于不同的项目 就会出问题 之前有人提过的

**Comment by sn01615** [comment]
因为现在的项目是用git地址分目录的 导致两个项目使用了相同的目录 就会出问题

**Comment by littlehz** [comment]
关联 #317

1、#317的问题，不是关键。这个问题修改与否，都不是特别重要，改进的优先级也不会很高。
2、`checkout后有些没有提交的文件会消失` 请勿将 walle 自动检出的git本地副本与开发时的git本地副本使用同一个，保持walle自动检出的那份绝对干净。
3、最重要的，git仓库不应当使用不同的目录方式。
 3a. 一切分支的改动都应当合并到master分支，开发时用若干个 dev_xyz 分支，开发完成后合并至master，上线发布时创建 vX.Y 分支 可选创建 tag。保证合并进主干之后才上线，上线后非紧急BUG不允许修改。
 3b. 不同的业务、甚至是同一个业务不同的相对独立的开发人员使用不同的独立git仓库。比如APP一个仓库、网页前端一个仓库、后端一个仓库。

**Comment by onecer** [comment]
这个和多个分支没什么关系。使用的时候注意一下就好。比如有dev和master两个分支，你要部署去两个不同的项目。你就新建两个项目。检出目录和发布目录不同，发布的时候选择特定的分支就好了。

**Comment by zjcnew** [comment]
太过于的复杂的需求，在产品发展到一定的程序才会考虑。
