### ISSUE TITLE
支持PHP7吗？

### ISSUE THREAD

**Issue by hongbaotong** [meolu/walle-web#391]
看官方安装文档里是php5.6，但是那个源好像已经没有了，是否能支持php7？

**Comment by littlehz** [comment]
1、支持 php7
2、什么源没有？

**Comment by wangyouw** [comment]
php7.2 不支持，yii有的文件会报错，7.1 没问题

**Comment by zhangjf108** [comment]
@wangyouw yii2更新到2.0.13就可以，yii2的Object类在7.2中是强制不能使用的关键字
