### ISSUE TITLE
官网说明有误

### ISSUE THREAD

**Issue by hailianghe** [meolu/walle-web#395]
地址http://www.walle-web.io/docs/installation.html
“1.简洁安装指南”里面的“vi config/web.php # 设置mysql连接” 应该为vi config/local.php

普通人员现在git clone 项目只能clone http的地址吧，你这边还是ssh协议的

**Comment by littlehz** [comment]
@wushuiyong 改下官网

`普通人员现在git clone 项目只能clone http的地址吧，你这边还是ssh协议的` 配了github证书都可以clone

**Comment by hailianghe** [comment]
@littlehz 如果没配ssh-key，普通游客是无法clone的，为什么不修改为https的呢
