### ISSUE TITLE
生成回滚任务失败

### ISSUE THREAD

**Issue by wjangelking** [meolu/walle-web#396]
![20171129174131](https://user-images.githubusercontent.com/17584830/33368598-18384682-d52d-11e7-8086-272315b3f764.png)

有`回滚`选项，但是点击回滚就提示`生成回滚任务失败`，这种情况偶尔会出现，请问是什么问题呢

**Comment by littlehz** [comment]
保存数据到数据库里失败了，看看php error log里有没有记录到什么原因
