### ISSUE TITLE
请问可以在windows下部署吗？

### ISSUE THREAD

**Issue by WenTao-Love** [meolu/walle-web#4]
您好！请问可以在windows下部署吗？

**Comment by meolu** [comment]
不可以的哦，要求lnmp或者lamp，需要执行bash命令

**Comment by istrwei** [comment]
linux下部署失败啊，求详细教程啊

**Comment by meolu** [comment]
https://github.com/meolu/walle-web/blob/master/qa.md
如果这个中没有你遇到的问题，那加群吧：）
