### ISSUE TITLE
发布代码前后的代码差异对比列表问题

### ISSUE THREAD

**Issue by willre** [meolu/walle-web#402]
1. 发布代码时，可否增加差异文件的对比列表？
就是显示 和上一次的代码做对比，当前要发布的代码做了哪些修改，比如显示哪些文件是修改的，哪些文件时新增的，哪些文件时删除的，这样方便做代码发布前的check，

2. “我的上线单” 这个功能里只能看一些简单的信息
这个功能，是否也可以增加一个子功能，可以查看每次发布做了哪些更改

3. 前面有朋友提到的灰度发布功能也很想要

**Comment by littlehz** [comment]
有版本号，可以用 git/svn 工具对比，专业的事情还是交给专业的工具做吧
