### ISSUE TITLE
新建用户，需要其他项目管理员审核

### ISSUE THREAD

**Issue by choudou** [meolu/walle-web#403]
第一次安装，配置项目 提示 “项目管理员尚未通过其它项目管理员的审核，无操作项目权限：）”
1. 但是这是第一个注册用户，没有其他管理员，谁来给他审核通过？
2. 看数据库有admin用户，但是登录不了，文档里也没有说明，这个到底有没有用，怎么用？

**Comment by emilwonggg** [comment]
更改数据表user中admin的 email_confirmation_token 字段最后的“_”后面的时间戳，然后将这段更改的时间戳复制到浏览器访问：项目域名+site/confirm-email?token=+email_confirmation_token

**Comment by littlehz** [comment]
账号 admin，密码 admin 登录

**Comment by waynesun01** [comment]
admin登录后点击项目管理依然还是这个错误！
新注册用户通过邮件激活进来user表中email_confirmation_token没值；
即使填了也还是
