### ISSUE TITLE
按照文档，git clone都报错

### ISSUE THREAD

**Issue by allen-hxn** [meolu/walle-web#404]
root@ubuntu-trusty-64:/home/vagrant# git clone git@github.com:meolu/walle-web.git
Cloning into 'walle-web'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

结果看github的地址
git clone https://github.com/meolu/walle-web.git就可以了。
是我看错了还是文档错了

**Comment by ideal** [comment]
这个应该是你没有在github设置你添加过SSH公钥导致的。

**Comment by littlehz** [comment]
文档没错，不过不合理，很多人没有配过github公钥。水哥 修改下

**Comment by meolu** [comment]
> 文档没错，不过不合理，很多人没有配过github公钥。水哥 修改下

这种低级错过都过不去，后面的问题怎么办？
