### ISSUE TITLE
能否列出每个版本下git下的文件，然后可以选择文件部署呢？

### ISSUE THREAD

**Issue by lilechao** [meolu/walle-web#406]

**Comment by littlehz** [comment]
按照一般规范，提交到发布分支的所有代码，应当全部上线。反之，服务器上的所有文件，也应当在git仓库中。

排除文件仅仅是排除一些缓存目录、编译目录等临时目录。

**Comment by lilechao** [comment]
因为在部署的时候遇到一个问题就是upload 目录是上传目录，如果修改一个页面固定的jpg文件 ，其存储目录也是upload 下 ，那么我们直接提交部署upload 文件夹，那么线上图片就被覆盖了。
