### ISSUE TITLE
walle发布git标签代码未更新到最新

### ISSUE THREAD

**Issue by Angel-ant** [meolu/walle-web#408]
使用操作如下：删除已存在的git标签，修改代码后，新建一样的标签，walle发布的时候代码未更新到最新
目前解决方案只能删除本地的项目目录，重新执行“检测”，有没有其他方式可以避免手动操作。

**Comment by littlehz** [comment]
tag吗？这是git系统本身的本地缓存，一般的git pull操作并不会更新。需要执行其他的git命令更新，但是比较耗时。为了少量的可能性而降低每次的发布速度，并不划算。建议这种情况手动操作。
