### ISSUE TITLE
初始化报错问题.

### ISSUE THREAD

**Issue by airforce-captain** [meolu/walle-web#415]
/opt/walle-web # /opt/walle-web/yii walle/setup
create dir 创建目录...
mkdiring dir: /tmp/walle/
mkdiring dir: /opt/walle-web/runtime/ansible_hosts/
mkdiring dir: /opt/walle-web/vendor/bower/jquery/dist
set writable 设置可写权限...
Setting writable: /opt/walle-web/runtime
Setting writable: /opt/walle-web/web/assets
Setting writable: /tmp/walle/
Setting writable: /opt/walle-web/runtime/ansible_hosts/
set executable 设置可执行权限...
Setting executable: /opt/walle-web/yii
update database 更新数据库: yii migrate/up ...
Yii Migration Tool (based on Yii v2.0.7)

Error: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)

如果local.php配置文件里数据库连接改成 localhost 的话，
初始化则提示这个问题。
 Error: SQLSTATE[HY000] [2002] No such file or directory

确认数据库连接权限没问题。

![walle](https://user-images.githubusercontent.com/16110498/37189610-41a765fa-2390-11e8-90d8-dc0e9347c99b.jpg)

**Comment by airforce-captain** [comment]
补充下测试截图.
![walle2](https://user-images.githubusercontent.com/16110498/37197120-6936f972-23b4-11e8-9b7a-66f0bcc59d64.png)

我写了个测试连接，是可以正常连接的。walle的数据库连接配置也是对的，不知道问题在哪里？

**Comment by sn01615** [comment]
你确定你使用127.0.0.1和localhost都能连接数据库吗？

**Comment by airforce-captain** [comment]
@sn01615 

上面截图中就有连接成功的命令.

**Comment by sn01615** [comment]
@airforce-captain MySQL里默认情况下localhost和127.0.0.1的账户是分开配置的，也就是两个地址可以是不同的账户名和密码，你的127.0.0.1可以连接，不能代表localhost可以连接啊

**Comment by airforce-captain** [comment]
@sn01615 
我在配置文件中是写的127.0.0.1  ，它自动给我显示的localhost , 另外，我确实两个都试了都不行,上面是我截图截少了.
我自己写个php页面，无论用localhost还是127都没问题，可以连接, walle 配置文件里无论写什么都不行, 127， localhost ,  本机ip 都试过了,  数据库里一律授权% ，使用root用户也不行，单独授权一个walle 用户也不行..见鬼了.

**Comment by sn01615** [comment]
%并不是所有主机的意思，远程可以连接，不代表本地可以连接

**Comment by airforce-captain** [comment]
@sn01615 
![1](https://user-images.githubusercontent.com/16110498/37610877-c53df228-2bdb-11e8-9c8b-81153d3dde23.png)
![2](https://user-images.githubusercontent.com/16110498/37610891-cb1ee62a-2bdb-11e8-8bfe-e0d398f938b6.png)

**Comment by sn01615** [comment]
感觉是不是少了一个hostname的？

**Comment by airforce-captain** [comment]
![walle](https://user-images.githubusercontent.com/16110498/37641669-a076c76a-2c55-11e8-87e8-3fff9b24877c.png)
