### ISSUE TITLE
部署时命令执行2次

### ISSUE THREAD

**Issue by wjangelking** [meolu/walle-web#416]
@littlehz @meolu 

**部署时，瓦力的每条命令都执行2次**

![123456](https://user-images.githubusercontent.com/17584830/37191754-8f89f858-239c-11e8-9812-fcc0c9c1782a.png)

**Comment by yeer** [comment]
我也遇到了这个问题，建议 /walle/start-deploy 接口里增加个判断重复提交的功能。有的vpn软件会重复发送请求，如果保留版本里配置的保留数量小于单次的重复请求deploy接口次数，就会导致软连接指向的是不可用的目录。网站就挂掉了。
