### ISSUE TITLE
SVN项目配置问题

### ISSUE THREAD

**Issue by giantErica** [meolu/walle-web#419]
项目配置检测总是显示，
目标机器检测出错，请确认php进程用户的ssh_key加入目标机器的信任列表
目标机器检测出错，请确认有目标机器发布版本库写入权限

但是信任关系已经添加了，权限也开了，还是报这个错，请问大概是由于什么原因

**Comment by littlehz** [comment]
配置 ssh 免密码登录

**Comment by meolu** [comment]
svn就不管了，请求公司切换到git吧
