### ISSUE TITLE
关于git http密码

### ISSUE THREAD

**Issue by vTNT** [meolu/walle-web#42]
文档：当然也可以http地址带用户名密码（不推荐）：https://username:password@github.com/meolu/walle-web.git， 其实可以有类似jenkins  git插件那样，记录git密码的，  这样也可以，不一定都是要ssh

**Comment by meolu** [comment]
对，可以记录用户名密码，但不推荐，建议用ssh，更安全

**Comment by vTNT** [comment]
就是不推荐这样https://username:password 的保存 方式，  jenkins里面是 可以保存密码 显示成***

**Comment by meolu** [comment]
嗯，展示格式可以做成：https://用户名:***/xxxx

**Comment by vTNT** [comment]
那不错

**Comment by ChinaGithub** [comment]
![1](https://cloud.githubusercontent.com/assets/4505332/11140857/36babad2-8a1a-11e5-8b00-41627713e933.png)
实在看不懂这个配置 ，求大神指教

**Comment by meolu** [comment]
详见：https://github.com/meolu/walle-web/blob/master/docs/config-git.md#四检测的错误和解决办法

ps：不要在已关闭的issue里提问，会被忽略：(
