### ISSUE TITLE
git 的地址仓为非22端口,无法部署

### ISSUE THREAD

**Issue by qinhir** [meolu/walle-web#421]
git 的地址仓为非22端口，填写带端口的repo_url 后，无法正确与git host 通过指定端口建立链接，会报：ssh: connect to host xxx.xxx.xxx.xxx port 22: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights

**Comment by littlehz** [comment]
可在 ~/.ssh/config 配置 Host 和 Port

**Comment by weikaiiii** [comment]
> 可在 ~/.ssh/config 配置 Host 和 Port

请问要配置到gitea服务器还是要部署的服务器 可以教一下吗
