### ISSUE TITLE
配置检测通过，但执行部署卡在“同步至服务器”步骤怎么解决

### ISSUE THREAD

**Issue by ztyzjn** [meolu/walle-web#423]
如题，有遇到相同问题的朋友吗，求助

**Comment by kenleemyth** [comment]
把PHP-FPM NGNIX等超时设置长点

**Comment by liujinshuai** [comment]
同问，总项目代码大概300M左右

**Comment by qinxiaogit** [comment]
同问，项目700M

**Comment by ShoJinto** [comment]
我们组要发布的项目大小已经3G多了，使用的是增量发布，但是通过跟踪日志发现增量更新之前都会把之前的项目完整的拷贝一份，这样对IO的要求太高了。可以考虑增量拷贝减少系统IO负载。

**Comment by sicunzhao** [comment]
可以看一下 /tmp/walle/  下面对应的log信息，有的报错前台页面看不到，

'cp -arf /mnt/ggtest/ggweb2/. /mnt/ggtest/releases/1/20180808-113523 && cd /mnt/ggtest/releases/1/20180808-113523 && tar --no-same-owner -pm -C /mnt/ggtest/releases/1/20180808-113523 -xz -f /mnt/ggtest/releases/1/20180808-113523.tar.gz'
2018-08-08 11:35:53 -- cp: cannot stat `/mnt/ggtest/ggweb2/.': No such file or directory

我的是报这个导致的卡住了，但是无法解决
