### ISSUE TITLE
在pre_release运行时其中的中文字符串被替换成空字符串了

### ISSUE THREAD

**Issue by DonFang** [meolu/walle-web#424]
# 当pre_release中的命令使用中文时，在运行时中文字符串被替换成空字符串了

 应用场景：使用sed命令批量替换字符串，被替换内容是一段中文字符，执行时发现变成了空字符串，导致执行报错了。
e.g.
`sed -i 's/中文/Hello/g' {VERSION}`
执行时变成：
`sed -i 's//Hello/g' {VERSION}`

**Comment by littlehz** [comment]
不支持中文，可以放在 shell 里
