### ISSUE TITLE
PHP Fatal error:  Cannot use 'Object' as class name as it is reserved 

### ISSUE THREAD

**Issue by anythink-wx** [meolu/walle-web#428]
PHP 7.2.5 (cli) (built: May 17 2018 18:28:21) ( NTS )

运行
./yii 报错
PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in /usr/local/walle-web/vendor/yiisoft/yii2/base/Object.php on line 77

**Comment by jeeinn** [comment]
PHP7.2.5不再允许使用object作为类名
参看：https://blog.csdn.net/hu_zhenghui/article/details/79222497

**Comment by anythink-wx** [comment]
明白错误原因了,但是怎么解决yii2的兼容?我是直接克隆的仓库地址
