### ISSUE TITLE
【BUG】site/Login 路由设置错误

### ISSUE THREAD

**Issue by AIJIJI** [meolu/walle-web#429]
在 /conf 页面一段时间未操作后

页面会跳转至 /conf/site/Login

这时候会报 404 Not Found

因为登陆页面应该是 /site/Login。
![image](https://user-images.githubusercontent.com/26321303/40524067-0c53d0c0-600b-11e8-8e85-5efee890edf8.png)

**Comment by meolu** [comment]
按照文档的nginx配置来，不用有错的
