### ISSUE TITLE
我在一个主机安装了walle，后面怎么操作

### ISSUE THREAD

**Issue by Liv1020** [meolu/walle-web#43]
我输入了待部署的主机ip使用了ssh 的git地址，然后怎么操作。

**Comment by meolu** [comment]
配置一个项目之后，检测下有没有问题，如有问题按提示处理问题即可

**Comment by Liv1020** [comment]
检查提示错误如下：
目标机器部署出错，请确认php进程用户用户ssh-key加入目标机器的www用户ssh-key信任列表， 且www有目标机器发布版本库/var/www/xxx写入权限。详细错误：xxx.xx.xx.xxx :

**Comment by Liv1020** [comment]
ssh-key的我知道，但是git的commit加载不出来，我的宿主机的id_rsa.pub已经添加到我的项目账号

**Comment by meolu** [comment]
>目标机器部署出错，请确认php进程用户用户ssh-key加入目标机器的www用户ssh-key信任列表， 且www有目标机器发布版本库/var/www/xxx写入权限。详细错误：xxx.xx.xx.xxx :

没有打印出php进程用户的名称？是用apache什么模式，需要得知php进程用户名称，把这个用户的ssh-key添加到目标机即可

**Comment by Liv1020** [comment]
好的，谢谢

**Comment by Liv1020** [comment]
![image](https://cloud.githubusercontent.com/assets/5382358/11029870/eefd60cc-8704-11e5-8bdb-cd9dc6de869e.png)
我使用了宿主机的ssh_key添加到项目的部署公钥，一直不可以

**Comment by meolu** [comment]
检测通过？

**Comment by Bryant-Yang** [comment]
ubuntu用php-fpm 进程是默认用户www-data，这个用户是nologin类型的用户。详细见：http://askubuntu.com/questions/486346/this-account-is-currently-not-available-error-when-trying-to-ssh

www-data作为不可登录用户，不但不能su www-data，也没有家目录存储不了ca信息。

这里难道要冒安全风险把php进程用户换成普通用户吗？
