### ISSUE TITLE
请问WALLE有办法可以类似于{WORKSPACE}一样把这用户选择的分支这个参数传到脚本里吗？

### ISSUE THREAD

**Issue by wealthjackson1** [meolu/walle-web#431]
请问WALLE有办法可以类似于{WORKSPACE}一样把这用户选择的分支这个参数传到脚本里吗？
WALLE 在发布时，开发是可以选择不同的环境时，如QA1-QA6环境，但是配置是不同的，有什么办法知道他选择的分支号吗？
![walle](https://user-images.githubusercontent.com/7401334/40594516-3bddacea-6262-11e8-8b1e-ca6392b84a30.png)

**Comment by shijunti19** [comment]
对啊
而且怎么只有{WORKSPACE}只有软连接地址，那怎么获取他的实际物理地址（这个非常重要，难道要自己去拼接出来？）

**Comment by meolu** [comment]
都可以了，具体看 #545 


| 高级变量             | 备注                | 样例                |
| -------------------- | ------------------- | ------------------- |
| `${WEBROOT}`         | 当前部署分支        | master              |
| `${CURRENT_RELEASE}` | 当前部署分支        | master              |
| `${BRANCH}`          | 当前部署分支        | master              |
| `${COMMIT_ID}`       | 当前部署的commit_id | abcde12             |
| `${PROJECT_NAME}`    | 当前部署的项目名称  | 大数据平台          |
| `${PROJECT_ID}`      | 当前部署的项目id    | 12                  |
| `${TASK_NAME}`       | 当前部署的任务名称  | 增加图表样式        |
| `${TASK_ID}`         | 当前部署的任务id    | 11                  |
| `${DEPLOY_USER}`     | 当前部署的用户      | 吴水永              |
| `${DEPLOY_TIME}`     | 当前部署的时间      | 2019-01-01 10:09:03 |
