### ISSUE TITLE
支持php7的计划吗?

### ISSUE THREAD

**Issue by wilbur-oo** [meolu/walle-web#437]
Hi,
php -v 
7.2.6
环境中执行./yii walle/setup
PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in /mydata/www/walle-web/vendor/yiisoft/yii2/base/Object.php on line 77

php7中object作为了保留字.

感谢您的项目

**Comment by sn01615** [comment]
怎么搞升级框架还是直接改？
升级框架比较妥当吧（也许）

**Comment by meolu** [comment]
新版没有了PHP版本问题，可能会有python问题。啊哈哈
