### ISSUE TITLE
配置里面如post_release 的shell 脚本不可以定义变量吗？

### ISSUE THREAD

**Issue by ShaoZeMing** [meolu/walle-web#444]
很感谢作者做的贡献，这个工具特挺用，目前有一个疑问需要请教一下：
shell脚本，定义数组变量进行遍历就会报错，错误信息页不太明确：
像这样写shell：
deploy_env="development";
deploy_user="root";
deploy_group="www-data";
deploy_root="/home/www/live";
arr_puth=("/storage" "/public/uploads" "/public/fonts") 

[ -d ${deploy_root}/shared ] || mkdir -p ${deploy_root}/shared;
shared_dir=${deploy_root}"/shared";

for NUM in ${arr_puth[@]}

do

[ -d ${shared_dir}${NUM} ] || mkdir -p ${shared_dir}${NUM};
[ -d {VERSION}${NUM} ] && rsync --progress -e ssh -avzh --delay-updates --exclude "*.logs" {VERSION}${NUM}/ ${shared_dir}${NUM}/ && rm -fr {VERSION}${NUM}/;
ln -nfs ${shared_dir}${NUM} {VERSION}${NUM};

done
就会部署失败

如果不用数组遍历,直接写

deploy_env="development";
deploy_user="sheye";
deploy_group="www-data";
deploy_root="/home/sheye/deploy/live_x";

[ -d ${deploy_root}/shared ] || mkdir -p ${deploy_root}/shared;
shared_dir=${deploy_root}"/shared";
[ -d ${shared_dir}/storage ] || mkdir -p ${shared_dir}/storage;
[ -d {VERSION}/storage ] && rsync --progress -e ssh -avzh --delay-updates --exclude "*.logs" {VERSION}/storage/ ${shared_dir}/storage/ && rm -fr {VERSION}/storage/;
ln -nfs ${shared_dir}/storage {VERSION}/storage;

[ -d ${shared_dir}/public/uploads ] || mkdir -p ${shared_dir}/public/uploads;
[ -d {VERSION}/public/uploads ] && rsync --progress -e ssh -avzh --delay-updates --exclude "*.logs" {VERSION}/public/uploads/ ${shared_dir}/public/uploads/ && rm -fr {VERSION}/storage/;
ln -nfs ${shared_dir}/public/uploads {VERSION}/public/uploads;

...

就能部署成功，对应的sh 默认执行已经修改为了bash,  部署服务器本地跑一个测试shell带数组脚本正常，还请指教

**Comment by meolu** [comment]
具体看 #545
