### ISSUE TITLE
检测总是提示请将php进程用户加入git的ssh-key中

### ISSUE THREAD

**Issue by huyiwill** [meolu/walle-web#446]
检测总是提示请将php进程用户加入git的ssh-key中.但是key已经添加了，而且在宿主机器git clone了，是成功的；后台查看代码断点调试下发现总是报错:  /usr/bin/env: git : not files 什么的？
然后也查看了cat /tmp/walle下的当天的日志，显示的是：ssh -T -p 22 -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o CheckHostIP=false 'root'@'10.0.2.79' 'rm -rf /home/wwwroot/publish/scp-trunk-svn/detection1530269160'
ssh root@10.0.2.79 免密码登陆是成功的。
想问下大佬，这是什么原因导致的？以前配置walle的时候，这些问题从来没有遇到过。

**Comment by huyiwill** [comment]
这个日志文件中看到的
2018-07-02 09:24:55 -- ---- Executing: $ ssh -T -p 22 -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o CheckHostIP=false 'huyi'@'10.0.2.79' 'mkdir -p /home/huyi/publish/scp-trunk-svn/detection1530494695'
2018-07-02 09:24:55 --

**Comment by iruimeng** [comment]
可以看到log，你把log命令直接粘贴到命令行执行下，看看有什么错误。还是不推荐使用个人账号。再有nginx的运行组是否修改为命令执行的账号。

**Comment by huyiwill** [comment]
解决了，我把源代码的git命令修改绝对路劲

**Comment by sn01615** [comment]
应该改环境变量

**Comment by aiddroid** [comment]
这里为什么必须把php进程用户加入git的ssh-key， 而不是用户自己指定一个用户，在使用这个用户的身份去拉取代码呢？这块功能感觉不应该跟php进程用户耦合。
