### ISSUE TITLE
一直卡在  请确认php进程deploy用户ssh-key加入目标机器的deploy用户ssh-key信任列表。找不到解决办法

### ISSUE THREAD

**Issue by LeesinYii** [meolu/walle-web#451]
@本地回环部署成功，远程一直提示
"目标机器检测出错，请确认php进程deploy用户ssh-key加入目标机器的deploy用户ssh-key信任列表。
目标机器检测出错，请确认deploy有目标机器发布版本库/data/wwwroot/xmt-api写入权限。"
这里，无论怎么改都不行
很多方法都试了，还是这样子，搞两天了，很多资料都不行：
su deploy
ssh-copy-id -i /home/deploy/.ssh/id_rsa.pub deploy@remote_ip 
输入密码，提示成功，且remote 目标机 /home/deploy/.ssh/authorized_keys 产生，权限为 600
chmod 755 -R /home/deploy
chmod 700 -R /home/deploy/.ssh/
chmod 600 authorized_keys

创建项目：进行测试报如上错误
尝试将 宿主机 ssh 相关的权限也都改成和 目标机一样 ，再次尝试，失败
尝试:
scp /home/deploy/.ssh/id_rsa.pub deploy@remote_ip:/home/deploy/.ssh/authorized_keys 
chmod 755 -R /home/deploy
chmod 700 -R /home/deploy/.ssh/
chmod 600 authorized_keys
报同样错误，测试本地回环依旧成功

在网上看到，修改 宿主机 php 用户 deploy 下的 .ssh/id_rsa  .ssh/id_rsa.pub 修改权限为 600 ，同时失败
上面几部都尝试免密登录了，ssh deploy@remote_ip 成功
ssh deploy@remote_ip 'ls  /home/'  执行命令也成功
执行下列命令都提示输入密码：
ssh -T -p 22 -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o CheckHostIP=false 'deploy'@'47.98.197.120' 'id'

ssh -T -p 22 -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o CheckHostIP=false 'deploy'@'47.98.197.120' 'mkdir -p /data/releases/xmt-api/detection1531920460'

ssh -T -p 22 -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o CheckHostIP=false 'deploy'@'47.98.197.120' 'rm -rf /data/releases/xmt-api/detection1531920460'

实在没办法了，比较着急，搞了这个东西搞了一天多了，让运维朋友帮忙远程也不行，还是一样的
使用 git bash 进行测试，也是一样的结果，不知道哪里出问题了

**Comment by LeesinYii** [comment]
解决了

**Comment by elinxer** [comment]
解决了没有结果吗,给个提示~~也是卡这里

**Comment by elinxer** [comment]
三个错误处理办法: 1.配置好后必须去配置目录拉一次代码,因为第一次有授权提示,要拉一次.2.目录权限错误不是因为你配置或权限问题,为待部署机器的目录权限,`ssh-copy-id -i ~/.ssh/id_rsa.pub deploy@127.0.0.1`  将walle-web所在机器的ssh-key加入到待部署主机上,上面的命令会自动加在待部署机器的.ssh中的,如此~

**Comment by secretgao** [comment]
> 解决了

大佬你是怎么解决的
![370201591959922_ pic_hd](https://user-images.githubusercontent.com/16075268/84496868-506a0a80-ace0-11ea-80c9-009604867485.jpg)

我弄了2台虚拟机 www_php1@10.211.55.12  和www_remote1@10.211.55.16 现在2台机器都已经实现了相互免密登陆  但是检测项目 还是失败
