### ISSUE TITLE
初次上线，webroot的软连接无法建立

### ISSUE THREAD

**Issue by kukuxiahuni** [meolu/walle-web#452]
`2018-07-19 10:45:07 -- ---- Executing: $ ssh -T -p 22 -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o CheckHostIP=false 'work'@'10.2.100.24' 'cp -arf /home/work/im-service/. /data1/publish/releases/8/20180719-104448 && cd /data1/publish/releases/8/20180719-104448 && tar --no-same-owner -pm -C /data1/publish/releases/8/20180719-104448 -xz -f /data1/publish/releases/8/20180719-104448.tar.gz'
2018-07-19 10:45:08 -- cp: cannot stat ‘/home/work/im-service/.’: No such file or directory`

总是提示无目录。这个不应该就是不建立嘛

**Comment by sicunzhao** [comment]
问题+1

**Comment by jeeinn** [comment]
问题+1
