### ISSUE TITLE
可以判断任务是回滚任务还是新任务吗？

### ISSUE THREAD

**Issue by baiwenl** [meolu/walle-web#456]
回滚时，有些`pre_release`是不需要执行的，比如链接数据文件夹进入发布目录，如果可以判断是回滚任务那么就跳过这些动作。
现在的做法是用if判断链接目标是否存在，如果存在就跳过，但是这样并不可靠，如果是发布新版本，是希望目标如果存在就删除并重新链接数据。

**Comment by meolu** [comment]
暂时没有考虑这么细啊
