### ISSUE TITLE
使用Ldap登陆报错

### ISSUE THREAD

**Issue by minminmsn** [meolu/walle-web#458]
版本：最新版git clone download zip文件
现象：
![image](https://user-images.githubusercontent.com/17631009/43517582-d23b61fa-95bb-11e8-90f2-b52148471ad8.png)
配置：
![image](https://user-images.githubusercontent.com/17631009/43517665-0ffcc39e-95bc-11e8-8d19-ca0272cf9f3e.png)

**Comment by fangpeishi** [comment]
LDAP 的用户节点没配置mail  这个属性吧。

**Comment by a735465047** [comment]
有这个功能？在哪里配呀，想用

**Comment by minminmsn** [comment]
@a735465047 配置文件里改下就行了

**Comment by minminmsn** [comment]
问题已经解决，功能没有问题，里面字段写反了
