### ISSUE TITLE
版本回滚问题

### ISSUE THREAD

**Issue by veiwan** [meolu/walle-web#461]
当进行版本回滚时，回滚按钮应该显示在上一个发布的版本上，当前发布的版本不应该显示回滚按钮，回滚按钮的意思是回滚到当前版本，而不是点击当前发布的版本来回滚到上一个版本，现在这个设计会让人很疑惑。
举个例子，如果版本保留数3个时，比如是V4、V3、V2、V1，当前发布的版本V4是不应该显示回滚按钮，V3、V2、V1是则需要显示回滚按钮(即意思是回滚到当前版本)
现在的设计中，版本保留数3时，线上保留的版本数应该是4个才对，即历史版本3个，当前发布的版本1个；在测试中，比如我当前的版本为V3，要回滚到V1时，就会报错

**Comment by xbw1220** [comment]
当前版本不是最新发布的吗?发布完成后,如果有问题不就是需要回滚了吗?你这个逻辑有点问题

**Comment by baiwenl** [comment]
有同样的困惑，习惯就好。veiwan 想表达的是版本旁边的按钮应该表示“回滚到”这个意思，比如v4是当前最新版，v3旁的回滚按钮表达“回滚到v3”，这样想回滚到哪个版本就找版本号旁边的按钮。
现在的按钮表达“撤销当前版本”，我要回滚到v2，就需要找到v3，点击旁边的回滚，撤销v3回到v2，是有一点饶。

**Comment by meolu** [comment]
新版的回滚非常好理解了，由文生义
