### ISSUE TITLE
centos7.4默认PHP5.4无法安装

### ISSUE THREAD

**Issue by yunyun** [meolu/walle-web#463]
Reading ./composer.json
Loading config file ./composer.json
Checked CA file /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem: valid
Executing command (/work/web/main/walle-web): git branch --no-color --no-abbrev -v
Failed to initialize global composer: Composer could not find the config file: /root/.composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Running 1.7.2 (2018-08-16 16:57:12) with PHP 5.4.16 on Linux / 3.10.0-693.2.2.el7.x86_64
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Reading ./composer.lock
Loading composer repositories with package information
Installing dependencies from lock file
Reading ./composer.lock
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Resolving dependencies through SAT
Looking at all rules.

Dependency resolution completed in 0.000 seconds
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - This package requires php >=5.5.0 but your PHP version (5.4.16) does not satisfy that requirement.

**Comment by sn01615** [comment]
Problem 1
- This package requires php >=5.5.0 but your PHP version (5.4.16) does not satisfy that requirement.

**Comment by littlehz** [comment]
需要PHP 5.5以上

**Comment by yunyun** [comment]
我直接下载了，服务器有时候改不了php版本，风险太高

**Comment by meolu** [comment]
用新版本2.0吧
