### ISSUE TITLE
www账户开启登录后要不要设置密码，会不会对网站有影响

### ISSUE THREAD

**Issue by shijunti19** [meolu/walle-web#464]
1.www账户开启登录后要不要设置密码，不设置是不是会有安全问题，会不会对网站有影响
2.如果不用www发布，upstream怎么弄，有没有教程，我用的宝塔一键安装的
3.很多网站系统的vendor可不可以也用软连接，我看你例子是写命令复制的，但是vendor超级大的啊，肯定影响速度或者可能导致文件不全
以前就关注这个系统了，但是一直卡在www账户设置密码的纠结问题上，希望有人回答下，怎么弄才安全

**Comment by littlehz** [comment]
1、密码和证书是两套登录系统。你可以配置空密码禁止登录，但又允许证书登录。或者设置一个极其复杂的登录密码。注意，登录密码和证书密码不是一回事。
2、配置独立的upstream和php-fpm pool，具体操作请咨询运维
3、可以用软链

**Comment by shijunti19** [comment]
@littlehz 好的谢谢，那我直接删了密码就行，弄个空密码

**Comment by shijunti19** [comment]
@littlehz post_deploy里要操作复制文件什么的，但是现在只有{WORKSPACE}，有没有其他参数，最好什么都传进去供我们使用，软连接对应的实际地址如git/1/20180902-093536（即将发布的版本），有没有这个网站上一个版本的实际地址如git/1/20180902-093156（从里面提取上个版本生成的文件，因为有些东西你必须生成在publid目录共外网访问，又不能用第三方有跨域问题）
