### ISSUE TITLE
我在宿主机执行目标机上的重启服务脚本一直报错

### ISSUE THREAD

**Issue by qnhjs** [meolu/walle-web#466]
上线出错:（
:'10.10.10.116 : '
'ssh -T -p 22 -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o CheckHostIP=false 'root'@'10.10.10.116' 'ln -sfn /data/release/bill/6/20180917-134029 /data/release/bill/6/current-bill.tmp 2>&1 && chown -h root /data/release/bill/6/current-bill.tmp 2>&1 && mv -fT /data/release/bill/6/current-bill.tmp /data/service1/bill 2>&1 && . /etc/profile 2>&1 && cd /data/release/bill/6/20180917-134029 2>&1 && /opt/shell/deploy/test_bill.sh' 2>&1'

请联系SA或者重新部署

其中 /opt/shell/deploy/test_bill.sh是我的脚本
脚本内容很简单，如下所示：
#!/bin/bash
for i in $(ps aux |grep bill|grep -v grep|awk -F " " '{print $2}')
do
kill -9 $i;
done
cd /data/service1 && nohup bill/bill.x >> logs/bill.log 2>&1 &

求高人指点！！！！

**Comment by littlehz** [comment]
我怎么感觉这个shell会把自己也kill呢？
