### ISSUE TITLE
请问一个发布任务是不是有执行时间限制？

### ISSUE THREAD

**Issue by yejunyi** [meolu/walle-web#467]
我这边有一个前端的发布任务，npm run build的时间比较长。我发现任务执行到一定时间就会重新开始发布任务。有时候明明到了scp到目标机器的阶段，也直接重头再来。

**Comment by shijunti19** [comment]
这个系统的机制有严重的毛病，网页端不能关闭的！
你得修改php的执行时间！

**Comment by yejunyi** [comment]
> 这个系统的机制有严重的毛病，网页端不能关闭的！
> 你得修改php的执行时间！

其实我修改过几个执行时间的配置，但还是固定3分钟左右就会重来一次

**Comment by wushuiyong** [comment]
加下我微信 wu-shuiyong 备注下名字@公司，聊下


原始邮件
发件人:junyiyedd01notifications@github.com
收件人:meolu/walle-webwalle-web@noreply.github.com
抄送:Subscribedsubscribed@noreply.github.com
发送时间:2018年9月29日(周六) 09:47
主题:Re: [meolu/walle-web] 请问一个发布任务是不是有执行时间限制？ (#467)


这个系统的机制有严重的毛病，网页端不能关闭的！
 你得修改php的执行时间！
其实我修改过几个执行时间的配置，但还是固定3分钟左右就会重来一次

**Comment by meolu** [comment]
你们说得对，php自身的不足，新版python将完全没有这个问题了
