### ISSUE TITLE
线上文件指纹存在命令注入

### ISSUE THREAD

**Issue by plushe** [meolu/walle-web#468]
runRemoteCommandByAnsibleShell等方法只是对$remoteCommand进行了escapeshellarg转义，但是$remoteCommand本身是拼接来的用户在目标机器执行的shell，它里面的参数没有转义，所以只是防止了宿主机注入，没有防止目标机器注入。
http://php.net/manual/zh/function.escapeshellarg.php

![image](https://user-images.githubusercontent.com/26989591/46867325-361ac200-ce57-11e8-8b35-0eb0af31524d.png)

**Comment by meolu** [comment]
欢迎来新版本2.0捉虫啊：）
