### ISSUE TITLE
项目部署成功后 nginx里的域名要怎么配置

### ISSUE THREAD

**Issue by xiaodongning** [meolu/walle-web#469]
![tim 20181023142630](https://user-images.githubusercontent.com/11451347/47340106-d41c5100-d6cf-11e8-9992-b60bcacb5ca7.jpg)
svn软连接到releases，每次发布版本都会更新，那么这个项目的域名要怎么配置

**Comment by elinxer** [comment]
win? win的软连接不知Linux一样的,得重配目录吧?

**Comment by xiaodongning** [comment]
每次发布新的版本后，svn目录的软连接都会更新，指向新的目录。nginx下的config 写的是具体目录吗？还是说这个只是帮我们打包而已。要自己更新到域名目录下

**Comment by meolu** [comment]
看下官方原理图
