### ISSUE TITLE
关于JAVA项目的发布

### ISSUE THREAD

**Issue by kamui0523** [meolu/walle-web#48]
HI,你提到walle支持JAVA项目的发布,但是JAVA从git拉去代码后如何building呢?多谢.

**Comment by meolu** [comment]
![](https://github.com/meolu/walle-web/blob/master/screenshots/detection-en.png)

**Comment by kamui0523** [comment]
Hi,所以你的意思是通过服务器上的执行响应的脚本来进行java从源码到jar包的编译么?

**Comment by meolu** [comment]
嗯，是的，在宿主机编译完成，同步到目标机群

**Comment by meolu** [comment]
具体看着部署流程图来看，更容易理解

**Comment by kamui0523** [comment]
了解,多谢~

**Comment by Alibner** [comment]
我这里有一个问题，想咨询下各位。还请帮忙看看；
我们的项目结构是
```
All--
	|- A项目
	|- B项目
	|- C项目
	|- D公共JAR包
	|- E公共JAR包

```
如果我要更新A项目，则直接把代码co下来的话，本地BUILD，会找不到公共JAR包。

这种问题，该怎么去处理比较好呢，麻烦了。

**Comment by Alibner** [comment]
@meolu 打扰了，这种情况有什么好的办法吗？
