### ISSUE TITLE
centos怎么安装不了2.0

### ISSUE THREAD

**Issue by shijunti19** [meolu/walle-web#480]
compilation terminated.
  error: command 'gcc' failed with exit status 1  
  ----------------------------------------
  Failed building wheel for pysqlite
阿里云服务器，我一直更新的啊
Command "/longteng/wwwroot/walle-web/venv/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-Nn17Ms/pysqlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-lnzdaN/install-record.txt --single-version-externally-managed --compile --install-headers /longteng/wwwroot/walle-web/venv/include/site/python2.7/pysqlite" failed with error code 1 in /tmp/pip-install-Nn17Ms/pysqlite/

不是用了mysql整个系统不应该再有sqlite了啊

我安装 yum install sqlite-devel解决了，不过我还是觉得有了mysql就不需要用到这个了

LOCAL_SERVER_HOST = '127.0.0.1'
    LOCAL_SERVER_USER = 'wushuiyong'
    LOCAL_SERVER_PORT = 22
数据库的密码应该写上，我觉得应该env放在根目录比较好
数据库名呢，在哪改

数据库密码不能改，放弃了....
还有数据库我用navicat不能导入数据部分，我觉得你还是合成一个比较好

**Comment by meolu** [comment]
2.0正在开发中，本周会出预览版的安装文档
