### ISSUE TITLE
在使用composer安装的时候，没有composer.json文件？

### ISSUE THREAD

**Issue by idoall** [meolu/walle-web#483]
最新版本2.0没有打tag，只能clone下源码，但使用composer更新的时候，又没有composer.json文件，怎么办？

**Comment by idoall** [comment]
官网的安装方式，好像不适合最新的2.0版本吧。2.0好像是用python写的，如何部署安装？

**Comment by meolu** [comment]
2.0正在开发中，本周会出预览版的安装文档
