### ISSUE TITLE
svn检测时提示svn: Can't convert string from 'UTF-8' to native encoding

### ISSUE THREAD

**Issue by zqstarmoon** [meolu/walle-web#49]
有中文的文件时，有如上的提示，SVN checkout失败，怎么处理这个问题，root用户下，我可以添加环境变量，php的www用户不知道怎么解决这个问题了

**Comment by meolu** [comment]
root下是加什么环境变量的？

**Comment by zqstarmoon** [comment]
export LC_CTYPE="zh_CN.UTF-8"
export LANG="zh_CN.UTF-8"

**Comment by meolu** [comment]
www用户加到www的.bash_profile也不行？

**Comment by Junw** [comment]
我也碰到了这个问题，而且我在宿主机通过php的用户登录服务器通过命令是能正常checkout含有中文路径的项目的，但是在检测操作时还是报了Can't convert string from 'UTF-8' to native encoding这个错。

**Comment by Junw** [comment]
我的问题解决了，在walle-web/config/local.php中加一句 putenv('LC_ALL=zh_CN.UTF-8'); 就行了。

**Comment by meolu** [comment]
感谢提供这个解决方案：）
