### ISSUE TITLE
234 warnings about package renames in new versions of flask

### ISSUE THREAD

**Issue by cclauss** [meolu/walle-web#494]
These renames should be done... https://travis-ci.org/meolu/walle-web/jobs/460197362#L1313

**Comment by meolu** [comment]
Goooooooood ! There are lots of error of py3 to be fixed... 
Fix them later by a special fix branch

**Comment by meolu** [comment]
@cclauss Welcome to alpha develop, I have invite you to join this repo, come on, such a exciting job.
I have write the develop doc in [INSTALL.md](https://github.com/meolu/walle-web/blob/master/alpha/INSTALL.md)
