### ISSUE TITLE
English commit / comments

### ISSUE THREAD

**Issue by lahaxearnaud** [meolu/walle-web#50]
Hello,

This project is great but all comments and commit messages are in chinese (not sur about that).
As this project is open source, it is possible to work in English?

Sincerly,

LAHAXE Arnaud

**Comment by meolu** [comment]
Configure language
```php
vi config/web.php +73

'language'   => 'en',  # zh => 中文,  en => english
```

do you clone from master? I havn't  made tag.

**Comment by Jeoffreybauvin** [comment]
+1 for working in English (app + code).

**Comment by meolu** [comment]
Walle works well both Chinese and English, I have translated it from Chinese to English, but the commit message is still Chinese. Just enjoy it after setting language in config/web.php, feedback this issue running into any question, I will response ASAP.
