### ISSUE TITLE
不是发布版本时，想重启项目的进程

### ISSUE THREAD

**Issue by oyhk** [meolu/walle-web#51]
不是发布版本时，想重启项目的进程。有提供这个功能吗？如果没有可以排一个时间开发吗？谢谢你们啦，支持你们

**Comment by meolu** [comment]
是批量机器重启服务？机器可指定？描述详细点问题

**Comment by oyhk** [comment]
你们不是有一个部署的ip地址吗？然后我想从这个列表里选一个ip然后重启进程。重启的按钮 可以调用我们自己编写的脚本

**Comment by meolu** [comment]
这个会排在1.0版本之后才能做了，不过，可以先提issue过来，我记着

**Comment by littlehz** [comment]
issue超时关闭
