### ISSUE TITLE
数据库连接报错，日志提示连接失败

### ISSUE THREAD

**Issue by a735465047** [meolu/walle-web#516]
**问题**：错误信息
错误提示
执行sh admin.sh migration时报错
**解决**：
原因是数据库配置的不对，密码也没写，端口也没写，配置settings_prod.py
SQLALCHEMY_DATABASE_URI = 'mysql://account:password@ip:port/walle'
实例：
SQLALCHEMY_DATABASE_URI = 'mysql://root:DbFfcc413a@10.26.14.141:10209/walle'

**Comment by chengjun2018** [comment]
https://github.com/meolu/walle-web/issues/513#issuecomment-446450022
