### ISSUE TITLE
执行sh admin.sh migration报错

### ISSUE THREAD

**Issue by xxw2016** [meolu/walle-web#520]
**问题**：错误信息
样例：执行sh admin.sh migration
ImportError: libmysqlclient.so.20: cannot open shared object file: No such file or directory

**解决**：
找到libmysqlclient.so.20 文件，进行软连接  ln -s /usr/local/mysql/lib/libmysqlclient.so.20 /usr/lib64/libmysqlclient.so.20 即可

**Comment by meolu** [comment]
感谢，已添加到官方文档 [http://walle-web.io/docs/install-error.html](http://walle-web.io/docs/install-error.html)
