### ISSUE TITLE
waller.py 74 waller.run Authentication failed. {参照#513#53_未能解决}-此故障卡了几天，未得到解决

### ISSUE THREAD

**Issue by chengjun2018** [meolu/walle-web#523]
问题现象：
1、在 部署管理>>上线单页面  界面右上角会提示网络连接错误
![image](https://user-images.githubusercontent.com/35955748/49868851-32002600-fe41-11e8-94d6-3ba4ca285e8b.png)
2、查看日志
tail -f logs/error.log 
```
2018-12-12 19:40:15,413 ERROR /data/www/walle-web/walle/service/waller.py 74 waller.run Authentication failed.
2018-12-12 19:40:15,441 ERROR /data/www/walle-web/walle/service/waller.py 100 waller.run task_id=0, user:www host:127.0.0.1 command:git pull, status=1, message:Authentication failed.
```
根据报错信息查看源代码
![image](https://user-images.githubusercontent.com/35955748/49868963-86a3a100-fe41-11e8-8016-5440c0bb8561.png)
3、根据官方给的解决办法-测试
3.1、宿与目标主机之间的互信-经过测试 互信OK
git clone /pull/push 都OK
![image](https://user-images.githubusercontent.com/35955748/49869061-d2eee100-fe41-11e8-9f9a-187ab8610bab.png)
3.2、宿主机与gitlab已经添加KEY
![image](https://user-images.githubusercontent.com/35955748/49869273-88ba2f80-fe42-11e8-8c93-fafac9d97c47.png)
3.3、宿与目标的目录权限-满足
![image](https://user-images.githubusercontent.com/35955748/49869363-c6b75380-fe42-11e8-8cdd-440299f73887.png)

靓图
![image](https://user-images.githubusercontent.com/35955748/49869477-1269fd00-fe43-11e8-92be-1aeee70cc124.png)

**Comment by haozi3156666** [comment]
原因是因为使用到了 fabric2，通过 fabric2 执行本机命令时，是需要先登录本机，也就是先执行 `ssh 用户@127.0.0.1`，可以在本机先执行这一步测试一下是否免密登录本机，如果不行，按照以下步骤来做：
1. 生成公钥（如果有公钥就不用执行）：ssh-keygen -t rsa
2. cp ~/.ssh/id_rsa.pub ~/.ssh/authorized_keys
3. 检查权限：
 ~：755
 ~/.ssh: 700
 ~/.ssh/authorized_keys 600
4. 执行命令：ssh 用户名@127.0.0.1，如果没有提示输密码就登录成功就表示成功了

**Comment by meolu** [comment]
@chengjun2018 描述得非常给力！也让我一下子看到了问题，赞！
```console
[www@127.0.0.1]$ ssh localhost
[www@127.0.0.1]$ cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
[www@127.0.0.1]$ ssh localhost
```

**Comment by chengjun2018** [comment]
> 原因是因为使用到了 fabric2，通过 fabric2 执行本机命令时，是需要先登录本机，也就是先执行 `ssh 用户@127.0.0.1`，可以在本机先执行这一步测试一下是否免密登录本机，如果不行，按照以下步骤来做：
> 
> 1. 生成公钥（如果有公钥就不用执行）：ssh-keygen -t rsa
> 2. cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
> 3. 检查权限：
>    ~：755
>    ~/.ssh: 700
>    ~/.ssh/authorized_keys 600
> 4. 执行命令：ssh 用户名@127.0.0.1，如果没有提示输密码就登录成功就表示成功了

感谢你的解惑  thank you

**Comment by meolu** [comment]
现在再更新下，优化成不需要处理宿主机的信任关系了
