### ISSUE TITLE
添加环境提示环境已存在

### ISSUE THREAD

**Issue by haozi3156666** [meolu/walle-web#524]
**问题描述**
在 demo 空间下建了预发布环境和正式环境，切换到另一个空间，该空间下没有任何环境，新建一个预发布环境，提示环境已存在

**截图**
![image](https://user-images.githubusercontent.com/6301977/49918508-6118a500-fede-11e8-9e9c-e2d68402384e.png)

**Comment by meolu** [comment]
更新下代码，这个问题挺早之前修复了
