### ISSUE TITLE
CentOS 7 系统环境初始化

### ISSUE THREAD

**Issue by warmwinter** [meolu/walle-web#525]
**现存什么问题没有很好被解决**

执行 `sh admin.sh init` 时缺少必要的包导致中断，应增加系统环境初始化内容

**我希望walle提供这样的功能**

增加如下初始化语句（Base CentOS 7.6.1810）

- 安装的系统自身的mariaDB(未验证)

```shell
yum install -y mariadb-devel gcc gcc-c++ python-devel
```

- 安装的MySQL（未验证）

```shell
yum install -y mysql-devel gcc gcc-c++ python-devel
```

- 安装的Mysql官方源（已验证）

```shell
yum install -y mysql-community-devel gcc gcc-c++ python-devel
```

**Comment by meolu** [comment]
感谢

**Comment by rockmelodies** [comment]
都装了没有用
![image](https://user-images.githubusercontent.com/24653177/50042033-e47df600-0098-11e9-8552-63cf70adfc35.png)

**Comment by rockmelodies** [comment]
可以了

**Comment by meolu** [comment]
已更新到`admin.sh`中，感谢建议
