### ISSUE TITLE
执行mysql语句时出错

### ISSUE THREAD

**Issue by phxiong** [meolu/walle-web#526]
**问题描述**
执行 sh admin.sh migration中提示mysql中语句报错

**问题描述**
日志堆栈贴上来。
logs/runtime.log
```


```

**截图**
拖拽到此处即可上传
![image](https://user-images.githubusercontent.com/25837384/49929392-57eb0080-fefd-11e8-9e50-b3c6952f72d7.png)

**运行环境**
 - OS: [e.g. Centos 7.x]
 - 版本 [e.g. 2.0.0]

**Comment by meolu** [comment]
用的是什么数据库，什么版本

**Comment by phxiong** [comment]
mysql  Ver 15.1 Distrib 5.5.60-MariaDB, for Linux (x86_64) using readline 5.1

**Comment by phxiong** [comment]
> 用的是什么数据库，什么版本

mysql Ver 15.1 Distrib 5.5.60-MariaDB, for Linux (x86_64) using readline 5.1

**Comment by phxiong** [comment]
mysql版本不兼容，用了Server version: 5.7.24 MySQL Community Server (GPL)这个版本没有问题

**Comment by wu0407** [comment]
装个5.6.5版本以上

**Comment by Chasers9527** [comment]
一模一样的问题~~

**Comment by phxiong** [comment]
> 一模一样的问题~~换过mysql的版本的就可以了

**Comment by meolu** [comment]
依赖有说明。[http://walle-web.io/docs/dependency.html](http://walle-web.io/docs/dependency.html)
** MySQL 5.6.5以上**，否则会在安装时报错。
在MySQL 5.6.5版本之前，Automatic Initialization and Updating只适用于TIMESTAMP，而且一张表中，最多允许一个TIMESTAMP字段采用该特性。从MySQL 5.6.5开始，Automatic Initialization and Updating同时适用于TIMESTAMP和DATETIME，且不限制数量。
