### ISSUE TITLE
希望增加docker的部署方式

### ISSUE THREAD

**Issue by owen-carter** [meolu/walle-web#528]
**现存什么问题没有很好被解决**
我觉得这个项目挺好的，代码也看了，很整洁，很优美，难得的好项目，但是初次接触，感觉部署还不是很方便，或许很多人因为部署不起来，就放弃尝试和使用这个产品，比较惋惜

**我希望walle提供这样的功能**
因此希望提供docker的部署方式，会提升用户转化率。

**大概的设计图**
项目根目录下增加Dockerfile和docker-compose.yml文件
用户只需要安装了docker和docker-compsoe就可以在直接运行dockerc-compose up 就可以跑起来应用

**Comment by henyihanwobushi** [comment]
docker compose 方式目前已经支持, 问题关闭
