### ISSUE TITLE
发布中 scp 的问题

### ISSUE THREAD

**Issue by weixiang** [meolu/walle-web#534]
有个疑问，为什么提示是在目标机器上scp 文件，到目标机器上？
不应该是从宿主机上scp到目标机器上么。

![image](https://user-images.githubusercontent.com/4156995/50008225-7a107b80-ffee-11e8-9238-c9f46348e811.png)

**Comment by weixiang** [comment]
而且scp 的包，我配置的是在/media/www/codebase内，但这里显示是从/tmp/walle/codebase

**Comment by meolu** [comment]
版本落后太多了，这次问题很早就处理过了
