### ISSUE TITLE
关于整体提升用户初次部署的用户体验的想法

### ISSUE THREAD

**Issue by owen-carter** [meolu/walle-web#538]
**现存什么问题没有很好被解决**
#### 问题：
- 部署难，这个问题存在与数据库部署，python环境部署
- 初始化难，主要是初始化脚本会出各种错误

**我希望walle提供这样的功能**
#### 特性
- 部署可以通过docker&docker-compose进行部署
- 提取出 ui api gateway db 四个组件，gatwway是api网关，ui本质上是一个nginx，用来托管静态资源
  api是我们的api服务器，db是mysql，四个都做成镜像，并将部署细节，通过Dockerfile约定在文件之类， 
  从而减少用户对部署过程中对细节的感知，
- 镜像提交到dockerhub，最终目标实现，用户只需要一份docker-compose文件，就可以部署该应用 

**大概的设计图**
组件化，微服务，后期才能更好的扩展，
![image](https://user-images.githubusercontent.com/7497665/50041025-1dae6a00-0089-11e9-8fa3-626712ea5f16.png)

**Comment by meolu** [comment]
太贴心了，感谢你的docker贡献。
