### ISSUE TITLE
BUG 安装完还是不行

### ISSUE THREAD

**Issue by rockmelodies** [meolu/walle-web#539]
**问题描述**
在`角色`下，什么页面，什么功能，报错：xx
|在`super超管`角色下，项目管理页面，编辑项目成员，提交失败，报错：用户不存在于空间用户组中

**问题描述**
日志堆栈贴上来。
logs/runtime.log
```
runtime...
```
logs/error.log
```
error...
```

**截图**
拖拽到此处即可上传

**运行环境**
 - OS: [e.g. Centos 7.x]
 - 版本 [e.g. 2.0.0]

![image](https://user-images.githubusercontent.com/24653177/50042069-869dde00-0099-11e9-93c8-33af3c619ee3.png)

**Comment by rockmelodies** [comment]
换成127.0.0.1 就好了

**Comment by rockmelodies** [comment]
![image](https://user-images.githubusercontent.com/24653177/50042434-b64ee500-009d-11e9-9104-d61705204c90.png)

**Comment by meolu** [comment]
> 换成127.0.0.1 就好了

是数据库配置只能连127.0.0.1

**Comment by meolu** [comment]
错误日志没帖上来
