### ISSUE TITLE
哪些变量呢没有我连基础的都不能用啊

### ISSUE THREAD

**Issue by shijunti19** [meolu/walle-web#545]
**现存什么问题没有很好被解决**
{WORKSPACE}这个在新版本没用啊不会替换

**我希望walle提供这样的功能**
希望提供完整的支持的变量，现在没有变量我连网站都不能部署

**Comment by meolu** [comment]
文档更新了，[自定义变量](http://walle-web.io/docs/configuration-project.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%85%A8%E5%B1%80%E5%8F%98%E9%87%8F)
