### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by Alenx58** [meolu/walle-web#559]
开发者你好，该程序应该迁移至Python3，这几天我发现了几处不太个性化的地方，我本想更改，但是我一直学习的是Python3+   Python2.x不该更改

**Comment by meolu** [comment]
很多py开发者一直在努力推进py3，没有什么不该更改的，大胆提PR吧，年前我会做完从2.7完全兼容3.7+，一起吧

**Comment by Alenx58** [comment]
> 很多PY开发者一直在努力推进PY3，没有什么不该更改的，大胆提PR吧，年前我会做完从2.7完全兼容3.7+，一起吧
-----------------------------------
好的，我应该提交至哪个branch

**Comment by meolu** [comment]
master/development都可以啊
