### ISSUE TITLE
Please commit composer.lock file to repo

### ISSUE THREAD

**Issue by Richard87** [meolu/walle-web#56]
Hi!

Please commit your composer.lock file to the repo, so we can issue `composer install` to install the excact versions you are running.

Thanks, Richard

**Comment by meolu** [comment]
I'am sorry, I miss this issue.

Thanks for remind `composer.lock`, I will add it later.

**Comment by meolu** [comment]
There is something wrong with adding `composer.lock` running travis CI. The `composer.lock` runs with param `--no-dev`, but travis CI runs with param `--dev`, so travis CI runs fail.
![image](https://cloud.githubusercontent.com/assets/4423821/11360535/47d21258-92c0-11e5-91b9-a21f501e2938.png)


so, remove `composer.lock` again.

**Comment by Richard87** [comment]
why not add composer.lock file with - -dev,  but in install.md use composer
install --no-dev?

tir. 24. nov. 2015, 08.37 skrev huamanshu <notifications@github.com>:

**Comment by meolu** [comment]
Because install with `--no-dev` in production, travis CI runs with `--dev` to run unit test

**Comment by Richard87** [comment]
You should commit a regular composer.lock file that have been used on development t othe git repo, then TravisCI will get all the -dev dependencies.

Then when deploying Walle on a production server, it should be installed with

    composer install --no-dev --optimize-autoloader

That will install only the parts of the lock-file that is not related to development....

**Comment by meolu** [comment]
Oh, yes, `--no-dev` will cover the `--dev` param, I didn't that. :100:

**Comment by Richard87** [comment]
hehe, sorry for buggin you about this, its actually a not very important issue :P
