### ISSUE TITLE
希望加入插件机制

### ISSUE THREAD

**Issue by shijunti19** [meolu/walle-web#561]
可以参考宝塔，插件机制最好现在就加入

**Comment by meolu** [comment]
嗯嗯，感谢提供新思路，加入roadmap豪华套餐

**Comment by meolu** [comment]
@shijunti19 加下我微信聊下这个思路，想听听你的想法。

**Comment by shijunti19** [comment]
我觉得最简单的就是hook吧，系统每步都加一个hook，然后系统去调用，例如start，部署前hook，系统执行到这里，就去插件获查询哪个代码挂载了就执行它。然后要弄个全局变量，方便插件去调用项目目录，用户名等等一系列的数据，然后充分利用你的websocket把每步执行都输出到前端。
