### ISSUE TITLE
关于权限问题，不知道算不算BUG

### ISSUE THREAD

**Issue by axzhcode** [meolu/walle-web#567]
1、项目管理员可以列出并删除空间所有者这个用户，导致空间所有者无法登录
2、项目管理员页面有添加成员的功能，但是提示无权限，而空间所有者有这个权限，这个功能应该属于空间所有者。

**Comment by meolu** [comment]
问题1已经权限收敛为只读权限。
问题2是和前端配合问题，后端已经设计为不可见，前端已隐藏
