### ISSUE TITLE
BUG 全站https后依旧有部分资源使用http导致无法加载

### ISSUE THREAD

**Issue by walkonthemarz** [meolu/walle-web#572]
**问题描述**
部署管理-新建上线单时，加载```/socket.io/?EIO=3&transport=polling&t=MWNxpeG```出错

**问题描述**
由于网站使用了https，在加载```/socket.io/?EIO=3&transport=polling&t=MWNxpeG``` 时，使用的协议还是http，导致被chrome浏览器拦截请求

**Comment by meolu** [comment]
之前有报过这个http资源问题，已经修复过了，你更新看下？

**Comment by XiuyeXYE** [comment]
@meolu  
部署管理 -> 新建上线单 拉取不到git分支， ssh key 我已经配置了
http://ip/socket.io/?EIO=3&transport=polling&t=NA3ztJN 400 bad request
walle version 2.0.1
