### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by huangjianjun5987** [meolu/walle-web#577]
**问题描述**
请问启动报没有这个模块是咋回事？
Traceback (most recent call last):
  File "waller.py", line 5, in <module>
    from flask.helpers import get_debug_flag
ImportError: No module named flask.helpers

**Comment by huangjianjun5987** [comment]
已解决

**Comment by yulrosy** [comment]
我也遇到了，请问一下是怎么解决的

**Comment by lfming** [comment]
???? 特么倒是说一下怎么解决的啊

**Comment by lfming** [comment]
> 已解决

怎么解决的

**Comment by lovese** [comment]
@huangjianjun5987 咋解决的，能方便说下吗？谢谢了！

**Comment by gipee** [comment]
怎么解决都补说
