### ISSUE TITLE
在进行数据迁移（执行./admin.sh migration）的时候报错没有Error: No such command "db".

### ISSUE THREAD

**Issue by jiawenchao888** [meolu/walle-web#587]
<img width="349" alt="error" src="https://user-images.githubusercontent.com/40058893/50808603-477e4800-133a-11e9-83d8-53c6e8d2a94b.png">

**Comment by wu0407** [comment]
可以贴上你的操作步骤和python版本和walle版本或commit

**Comment by jiawenchao888** [comment]
完全按照官网文档安装的。

贾文超
研发部 / 运维工程师
18310742889
上海大途弘安信息科技有限公司 
 
发件人： wu0407
发送时间： 2019-01-08 11:58
收件人： meolu/walle-web
抄送： xiaojia; Author
主题： Re: [meolu/walle-web] 在进行数据迁移（执行./admin.sh migration）的时候报错没有Error: No such command "db". (#587)
可以贴上你的操作步骤和python版本和walle版本或commit

**Comment by jiawenchao888** [comment]
我又重新执行了一遍，现在成功了，我加你们的微信技术群了，但是加不进去，能拉我进群吗？谢谢！


贾文超
研发部 / 运维工程师
18310742889
上海大途弘安信息科技有限公司 
 
发件人： wenchao.jia@datuhongan.com
发送时间： 2019-01-08 13:34
收件人： meolu/walle-web
主题： Re: Re: [meolu/walle-web] 在进行数据迁移（执行./admin.sh migration）的时候报错没有Error: No such command "db". (#587)




完全按照官网文档安装的。

贾文超
研发部 / 运维工程师
18310742889
上海大途弘安信息科技有限公司 
 
发件人： wu0407
发送时间： 2019-01-08 11:58
收件人： meolu/walle-web
抄送： xiaojia; Author
主题： Re: [meolu/walle-web] 在进行数据迁移（执行./admin.sh migration）的时候报错没有Error: No such command "db". (#587)
可以贴上你的操作步骤和python版本和walle版本或commit

**Comment by jiawenchao888** [comment]
你好,现在创建项目报这个错，请教一下是哪里的问题呢？



贾文超
研发部 / 运维工程师
18310742889
上海大途弘安信息科技有限公司 
 
发件人： wenchao.jia@datuhongan.com
发送时间： 2019-01-08 13:53
收件人： meolu/walle-web
主题： Re: Re: [meolu/walle-web] 在进行数据迁移（执行./admin.sh migration）的时候报错没有Error: No such command "db". (#587)

我又重新执行了一遍，现在成功了，我加你们的微信技术群了，但是加不进去，能拉我进群吗？谢谢！


贾文超
研发部 / 运维工程师
18310742889
上海大途弘安信息科技有限公司 
 
发件人： wenchao.jia@datuhongan.com
发送时间： 2019-01-08 13:34
收件人： meolu/walle-web
主题： Re: Re: [meolu/walle-web] 在进行数据迁移（执行./admin.sh migration）的时候报错没有Error: No such command "db". (#587)




完全按照官网文档安装的。

贾文超
研发部 / 运维工程师
18310742889
上海大途弘安信息科技有限公司 
 
发件人： wu0407
发送时间： 2019-01-08 11:58
收件人： meolu/walle-web
抄送： xiaojia; Author
主题： Re: [meolu/walle-web] 在进行数据迁移（执行./admin.sh migration）的时候报错没有Error: No such command "db". (#587)
可以贴上你的操作步骤和python版本和walle版本或commit

**Comment by y191881708** [comment]
你好，我也是在这一步提示db没找到的问题，请问是怎么解决的？

**Comment by y191881708** [comment]
你好，重新执行了下，显示是没有报错的，再次按照步骤执行，还是报db错误

**Comment by y191881708** [comment]
你好，问题已解决，使用git clone源码问题就解决了，使用手动下载的zip包不行。

**Comment by wuq** [comment]
> 你好，问题已解决，使用git clone源码问题就解决了，使用手动下载的zip包不行。

我今天 clone 的, 还是报这个错误

**Comment by bestlake** [comment]
Error: No such command "db".
Migration:                 [ fail ]
依然不行啊

**Comment by bestlake** [comment]
Error: No such command "db".
Migration:                 [ fail ]
一开始用的3.7.3，现在换成2.7.16，问题还是这样，一天了还没装成过

**Comment by bestlake** [comment]
pip install -r requirements/prod.txt
这一步很必要

**Comment by ZouHongxue** [comment]
安装python虚拟环境 -> 激活环境 -> 安装依赖 -> 最后执行
init 出了问题, 请参考 admin.sh 重新执行相应语句即可。
