### ISSUE TITLE
升级脚本语法错误

### ISSUE THREAD

**Issue by daxiong123** [meolu/walle-web#588]
**问题描述**
sh admin.sh upgrade

admin.sh: 11: admin.sh: Syntax error: "(" unexpected

**截图**

![image](https://user-images.githubusercontent.com/2648157/50809487-bf4e7180-133e-11e9-8bfe-4b7d915c35d9.png)

**运行环境**
 - OS: Ubuntu 16.04 LTS
 - python: Python 2.7.6
 - 版本: 2.0.0

**Comment by daxiong123** [comment]
语法不同 不能使用 ``function``定义方法 已解决

**Comment by elinxer** [comment]
没有解决办法?

**Comment by pdpdpdd** [comment]
今天在ubuntu中安装也有类似问题，把sh改成bash后就好了
