### ISSUE TITLE
发布出错：not a valid RSA private key file

### ISSUE THREAD

**Issue by mowangjuanzi** [meolu/walle-web#590]
**问题描述**

在`Owner`角色下，项目上线页面，执行上线命令，执行失败，报错：not a valid RSA private key file。

项目不是私有项目，所以不是权限问题。

项目地址：

https://github.com/mowangjuanzi/blog

**问题描述**
日志堆栈贴上来。想贴，但是还没看到。
logs/runtime.log
```
runtime...
```
logs/error.log
```
error...
```

**截图**
<img width="1577" alt="wx20190108-140422 2x" src="https://user-images.githubusercontent.com/13846040/50812600-5d960380-134e-11e9-909f-918c6c726cbe.png">

![fireshot capture 2 - walle - http___localhost_8000_demo e7 a9 ba e9 97 b4_project_edit_2](https://user-images.githubusercontent.com/13846040/50813780-76081d00-1352-11e9-9c82-a262a03c7fe3.png)

**运行环境**
 - OS: [mac+docker]
 - 版本 [e.g. 2.0.0]

**Comment by mowangjuanzi** [comment]
update title

**Comment by meolu** [comment]
看样子是ssh登录的问题，手工在宿主上root用户做免密码登录： `ssh baoguoxiao@api.xxx`，看能否成功

**Comment by yhbdyx** [comment]
这个问题怎么解决的 ? 我也遇到了 , 我手工建立了SSH互信 , 但部署还是出错

**Comment by huangxingle2009** [comment]
我手动在宿主也能成功，但是就是web发布不行
![image](https://user-images.githubusercontent.com/4972859/78216606-d3a2ff00-74ec-11ea-8ea0-0f2991239b17.png)
