### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by sicher123** [meolu/walle-web#591]
配置的用户是xinge:
![image](https://user-images.githubusercontent.com/23478692/50815012-95a14480-1356-11e9-9446-6676b0fde057.png)

但实际使用的用户是root，导致 Authentication failed。
![image](https://user-images.githubusercontent.com/23478692/50814955-64c10f80-1356-11e9-825e-e5b20f3e4c4b.png)

检查mysql，发现曾经以root用户配置过101机器且在网页删除，但实际该条记录只是把状态码变为-1
![image](https://user-images.githubusercontent.com/23478692/50815082-d6995900-1356-11e9-9559-b4fd42940314.png)

删除了该条记录后，检测项目通过。
![image](https://user-images.githubusercontent.com/23478692/50815091-ddc06700-1356-11e9-9c09-e86b2ac2cfde.png)

可能是使用了host字段或是name字段正则匹配做查询条件，再用了model.query.first()导致的

**Comment by meolu** [comment]
感谢反馈，已经修复，请更新使用
