### ISSUE TITLE
./admin.sh: line 74: venv/bin/activate: 没有那个文件或目录

### ISSUE THREAD

**Issue by wuyibo005** [meolu/walle-web#598]
安装的时候报这个错是什么意思？
[root@MiWiFi-R3A-srv walle-web]# ./admin.sh migration
************************************************
migration walle
----------------
./admin.sh: line 74: venv/bin/activate: 没有那个文件或目录
./admin.sh: line 76: flask: command not found
Migration:                 [ fail ]
************************************************

**Comment by wu0407** [comment]
你要装virtualenv，你执行了这些了么

> chmod +x admin.sh
> ./admin.sh init
> 
> # 注意：安装mysqlclient失败，需要先安装libmysqlclient-dev(ubuntu)
> # 注意:安装失败请指定python路径. mac 可能会有用anaconda的python，找到自己系统的python 2.7追加参数指定 -p /usr/bin/python2.7 即可
> vi admin.sh +20
> virtualenv --no-site-packages -p /usr/local/bin/python2.7 venv
>

**Comment by wu0407** [comment]
https://walle-web.io/docs/installation.html#5-Install
