### ISSUE TITLE
服务搭建好后访问主页提示网络异常, 请刷新重试

### ISSUE THREAD

**Issue by 2438com** [meolu/walle-web#599]
按照步骤安装walle，部署完成后进入主页就重复报错网络异常, 请刷新重试

无法进行后续操作，是哪些配置有问题么？

**Comment by 2438com** [comment]
![walle](https://user-images.githubusercontent.com/39622935/50881473-a2886b80-141c-11e9-99cd-7271394daa02.png)

**Comment by mwf564** [comment]
同样问题，求解！
