### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by xingyueGK** [meolu/walle-web#604]
**主机远程登录问题**
比如我以账号 A启动程序，在以账号B作为远程登录的账号，因为秘钥问题就会认证失败，

**我希望walle提供这样的功能**
需要远程主机配置可以使用密码或是指定普通账号免密登录

**Comment by meolu** [comment]
原来2.0.0预览版就是这种模式，但事实上增加一个用户，对于大多数人来说，理解和使用成本都增大了，而且从设计上说，没有这样的必要。

walle的启动用户跟配置的用户没有本质的区别，在linux里使用相应的用户做正确的事情，walle的启动用户和部署相关的用户可以完全一致，而且对权限要求不高，也不需要`sudo`
