### ISSUE TITLE
Modal windows dosn't show 

### ISSUE THREAD

**Issue by Richard87** [meolu/walle-web#61]
Modal windows dosn't show up like Detection and Preview

**Comment by meolu** [comment]
is there any js problem? check up in console bar

**Comment by Richard87** [comment]
yes, jquery.mobile.custom.min.js is missing, but adding it, or removing the script that loads it breaks the UI, when clicking any of those buttons, I get a blank page, but the content is in the data returned from the server...

**Comment by meolu** [comment]
The return is right, and remove this screenshots or cover the important message : )

walle does not require the `jquery.mobile.**.js`, what happen to you : (

**Comment by Richard87** [comment]
Well that was strange! Works flawlessly on my work computer, I'll test some more :)

/Thanks about the foto :)

**Comment by Richard87** [comment]
very strange... it works flawlessly on one my work computer, but on my personal laptop, same version of windows, same version of chrome, it dosn't work...

**Comment by Richard87** [comment]
My problem is these line of code that executes for some reason on my laptop, but since the script is missing, somehow the execution fails of the rest fails...

    <script type="text/javascript">
        //if("ontouchend" in document) document.write("<script src='/dist/js/jquery.mobile.custom.min.js'>"+"<"+"/script>");
    </script>

**Comment by meolu** [comment]
yes, you are right, I fix it.
