### ISSUE TITLE
上线时不支持目标服务器端口为非22，会出现无法将打包taz拷贝到目标服务器的问题

### ISSUE THREAD

**Issue by hxzyzz** [meolu/walle-web#615]
**问题描述**
 目标服务器端口不是默认22端口，上线时scp动作无法完成。

[root@127.0.0.1]$ cd /opt/walle/codebase/ && cp -rf /opt/walle/codebase/1 1_1_20190111_172847
[root@127.0.0.1]$ cd /opt/walle/codebase/1_1_20190111_172847 && git reset -q --hard 61ea942
[root@127.0.0.1]$ cd /opt/walle/codebase/ && tar zcf /opt/walle/codebase/1_1_20190111_172847.tgz 1_1_20190111_172847/
[root@xxx]$ mkdir -p \opt\www\codebase
[root@xxx]$ scp /opt/walle/codebase/1_1_20190111_172847.tgz root@xxx:\opt\www\codebase
[root@xxx]$ tar zxf 1_1_20190111_172847.tgz
tar (child): 1_1_20190111_172847.tgz：无法 open: 没有那个文件或目录
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

**问题描述**
日志堆栈贴上来。
logs/runtime.log
```
runtime...
```
logs/error.log
```
error...
```

**截图**
拖拽到此处即可上传

**运行环境**
 - OS: [e.g. Centos 7.x]
 - 版本 [e.g. 2.0.0]

**Comment by Akuns** [comment]
我也遇到同样的问题，你解决了吗？求指教 @hxzyzz

**Comment by ayamzh** [comment]
@Akuns 你那解决了么
