### ISSUE TITLE
让密码支持#号吧是不是你保存机制导致的

### ISSUE THREAD

**Issue by shijunti19** [meolu/walle-web#621]
password: 密码至少6个字符，至少1个大写字母，1个小写字母，1个数字。
我密码有#啊

**Comment by meolu** [comment]
方便贴下密码，确认下正则有没有问题

**Comment by shijunti19** [comment]
xiaoLU#8888
就这种大小写数字都有的

**Comment by meolu** [comment]
用户密码正则校验优化，已更新 https://github.com/meolu/walle-web/commit/c76d4f3f8b669aa678f470867a8b6ebc14304c48

**Comment by xiusin** [comment]
密码包含@符号无解吗?
