### ISSUE TITLE
安装好walle，浏览器打开，只显示一串"walle-web 2.0"

### ISSUE THREAD

**Issue by longdw** [meolu/walle-web#622]
安装好walle，浏览器打开地址，只显示一串"walle-web 2.0"。
<img width="211" alt="123" src="https://user-images.githubusercontent.com/4987178/51069623-c7275200-166d-11e9-9498-ffbc8fb15118.png">

**Comment by meolu** [comment]
按官方安装文档[http://walle-web.io/docs/installation.html#3-Nginx-config](http://walle-web.io/docs/installation.html#3-Nginx-config)，细心点检查，没问题的

**Comment by longdw** [comment]
nginx我也是按原样配置的，确实是不行，修改完nginx后我直接重启了sh admin.sh restart。不知道怎么重启nginx，请指教。
