### ISSUE TITLE
问个小问题，私人git要求输入账号密码会导致卡死

### ISSUE THREAD

**Issue by shijunti19** [meolu/walle-web#624]
目前因为这个无法正常上线中。。。从上线到现在一直被多种小问题宽饶，一直无法正常上线
对于有密码的git希望给出一个完整的设置步骤，例如要不要切换到部署用户名下，然后git再设置全局保存账号密码，然后怎么操作，我个人觉得不可能在界面里输入账号密码的，估计要提前保存好，但是目前不知道为什么不行了！runtime.log里似乎记录的有问题，应该先记录操作步骤，然后执行的，例如出现下面的记录，但是我却没看到git clone命令，导致我无法自查，希望改进
Cloning into '/git/1'...
Username for 'https://gitee.com': 
我就本地保存了，但是发现无效
我ssh里运行git clone http://***正常，账号密码不需要我输入
但是一上线他就因为账号密码卡死上线，我不知道怎么解决了！我linux上全局保存了啊
我希望你解决下
![image](https://user-images.githubusercontent.com/5392211/51070391-71f23d00-167b-11e9-9e21-fc20ba860e96.png)

一直在转，整个服务器被他彻底拖垮！我觉得应该弄个超时时间的

**Comment by meolu** [comment]
有密码的git用的是什么协议拉取代码？https/git

**Comment by shijunti19** [comment]
@meolu 用的https，我看文档2者都支持了，就用了这个，难道要换成git？以前老的好像只能git？但是如果填错你试试看，整个服务器都卡死了，2G2内存

**Comment by lzxyz** [comment]
建议还是用ssh(即git)少用https，https要设置存储用户信息，否则项目有鉴权的会导致错误，配置一个SSH就搞定了

**Comment by fm19890618** [comment]
请问楼主这个问题后怎么解决的，我也遇到这个问题

**Comment by shijunti19** [comment]
@fm19890618 上一楼说了啊用ssh://地址，作者他没去限制，也没去修复这个问题
