### ISSUE TITLE
BUG-右上角空间只能显示6个

### ISSUE THREAD

**Issue by hupinxiao** [meolu/walle-web#625]
**问题描述**
添加空间超过6个后，右上角最多只能显示6个，而且Demo空间删除了，右上角还会显示；

**运行环境**
 - OS: [e.g. Centos 7.x] 
 - 版本 [e.g. 2.0.0]
 - Docker 跑的

**Comment by meolu** [comment]
我觉得很有可能是一个后端的问题，在空间修改owner用户的时候没有把这个owner用户更新权限表。
commit 540b0d 已修复，更新确认下是不是你描述的问题
