### ISSUE TITLE
web服务器与应用服务器分离时如何部署？前端代码未开源么？

### ISSUE THREAD

**Issue by CharlesSong** [meolu/walle-web#632]
**问题描述**
1. web服务器与应用服务器分离时如何部署？
2. 前端代码我看是编译构建之后的代码，源代码不开源么？

**Comment by meolu** [comment]
前端代码目前只对开发组以及VIP企业开放

**Comment by y271024217** [comment]
> 前端代码目前只对开发组以及VIP企业开放

如何成为vip企业呢
