### ISSUE TITLE
BUG-新建账号提示网络异常

### ISSUE THREAD

**Issue by JamesLi2013** [meolu/walle-web#634]
**问题描述**
|在`super超管`角色下，用户管理页面，增加项目成员，点击提交，弹窗没有关闭,弹出报错信息：网络异常.

实际上该新增操作已成功,下次也可以登陆.
**问题描述**
日志堆栈贴上来。
logs/runtime.log
```
runtime...
```
logs/error.log
```
error...
```

**截图**
拖拽到此处即可上传
![image](https://user-images.githubusercontent.com/13946095/51235403-5acc8b80-19aa-11e9-9508-9ee676d34a21.png)

![image](https://user-images.githubusercontent.com/13946095/51235947-c400ce80-19ab-11e9-9853-1bca20782b30.png)

**运行环境**
 - OS: [Centos 7.2]
 - 版本 [2.0.0]

**Comment by Alenx58** [comment]
@JamesLi2013  你好，确认一下5000端口是否正常。

**Comment by huangshaoming1995** [comment]
我的是异常后刷新可以找到新建用户，应该是没有使用延时处理

**Comment by meolu** [comment]
现在还能复现么？方便把runtime.log贴下。

**Comment by meolu** [comment]
不要部署到外网，太危险了
