### ISSUE TITLE
希望增加项目部署时有更多的自定义设置

### ISSUE THREAD

**Issue by xbw1220** [meolu/walle-web#638]
**现存什么问题没有很好被解决**
因为我对git也不熟悉,再往上谷歌和百度了一下也没找到解决的方法,比如一个git版本库里面有多个目录,每个目录对应一个项目,但是我发布的时候是不可能整个版本库都发布过去,这样我只能使用"部署包含文件"选项里面"包含"的功能,选择柏寒对应项目的目录再发布过去,这样的话就有一个问题了,软连接指向的是项目目录的上一级目录对应版本库的话就是版本库的根目录,也就是说最后一步软连接没有达到指向项目目录的要求

**我希望walle提供这样的功能**
希望增加软连接的更深的自定义指向

**大概的设计图**
比如下面这样增加时间戳后面的自定义
project -> /wwwweb/releases/1_4_20190117_034744/project

**Comment by meolu** [comment]
我大概能理解你的意思，但还是没能100%。

- 多个项目合到一个git不是一个明智的做法。
- 想把一个git的指定目录，发布到目标服务器的根目录下，并且是同名目录。这事儿有个问题，虽然是发布了这个目录，但根目录的版本1_4_20190117_034744是重新打的，之前除了project以外的项目都会丢失。我理解对不？

**Comment by xbw1220** [comment]
> 我大概能理解你的意思，但还是没能100%。
> 
> * 多个项目合到一个git不是一个明智的做法。
> * 想把一个git的指定目录，发布到目标服务器的根目录下，并且是同名目录。这事儿有个问题，虽然是发布了这个目录，但根目录的版本1_4_20190117_034744是重新打的，之前除了project以外的项目都会丢失。我理解对不？

对哦,你说的没错哎,后来我也是一个项目一个git库..因为之前公司一直都是用SVN的,现在还是,为什么用上walle2我才搭了个gitlab存放构建的项目成品
