### ISSUE TITLE
关于目标机器的  webroot

### ISSUE THREAD

**Issue by xuanskyer** [meolu/walle-web#64]
新建目标机器的webroot目录的时候，即使项目有多次上线或者回滚操作。

在发布版本库中会有多个目录。但是webroot的软链接并没有指定具体的哪个目录，而是一直指定上层目录。
那多次上线的时候，访问时，怎么知道当前版本是哪个呢？

**Comment by meolu** [comment]
webroot的软链接指向的是版本，更新之后才会切换版本。请求不管你版本是哪个，只管webroot，软链就是起这个作用，webroot代表着最新版本，可快速切换。

**Comment by xuanskyer** [comment]
啊我试了下。好像回滚之后，软连接就没有指向具体的版本目录，而是指向上层目录了。

**Comment by meolu** [comment]
截图看下

**Comment by flashput** [comment]
这个应该是在部署了多个版本后, 直接回滚第一个提交部署的版本, 这时软连接就连到了上一级目录.
