### ISSUE TITLE
docker部署后，能正常打开界面，但是数据库没有一个表

### ISSUE THREAD

**Issue by zxj19951029** [meolu/walle-web#648]
登陆时，显示登陆错误，日志信息中，提示表不存在，登陆mysql后，发现walle数据库中，没有一个表存在

ProgrammingError: (_mysql_exceptions.ProgrammingError) (1146, "Table 'walle.users' doesn't exist") [SQL: u'SELECT users.id AS users_id, users.username AS users_username, users.is_email_verified AS users_is_email_verified, users.email AS users_email, users.password AS users_password, users.avatar AS users_avatar, users.`role` AS users_role, users.status AS users_status, users.last_space AS users_last_space, users.created_at AS users_created_at, users.updated_at AS users_updated_at \nFROM users \nWHERE users.email = %s \n LIMIT %s'] [parameters: ('super@walle-web.io', 1)] (Background on this error at: http://sqlalche.me/e/f405)
walle-mysql | mbind: Operation not permitted
walle-mysql | mbind: Operation not permitted

**Comment by WenHou** [comment]
遇到同样的错误...

**Comment by WenHou** [comment]
在已有的 issue 中找到结果了
https://github.com/meolu/walle-web/issues/541

我的问题按这个步骤解决的，供参考
docker ps
docker exec -it walle-python bash
cd /opt/walle-web
chmod +x ./admin.sh && ./admin.sh migration

**Comment by zxj19951029** [comment]
参照楼上的做法，确实是可以的
