### ISSUE TITLE
that's amazing,i want to be a contributor

### ISSUE THREAD

**Issue by zuoRambo** [meolu/walle-web#65]
yes,i do

**Comment by meolu** [comment]
好吧，如果有兴趣的话，看下to-do list有没有你想做的。或者在上线单列表里加一个选项，【只看我的上线单】不勾选则展示他有权限的项目的所有上线单。

**Comment by zuoRambo** [comment]
composer.lock 很有必要么 没有的话 那些symfony的依赖 应该移除

**Comment by meolu** [comment]
`composer install`的时候，它首先会判断composer.lock文件是否存在。如果存在，将会下载相对应的版本(不会在于composer.json里面的配置)，这意味着任何下载项目的人都将会得到一样的版本；如果不存在，则后是全新安装。
