### ISSUE TITLE
希望能开放前端源代码，这样其它人也可以贡献代码，或者自己解决BUG

### ISSUE THREAD

**Issue by baimoer** [meolu/walle-web#654]
既然后端的所有代码都开源了，那么前端代码开源，其实都是小事了。

但是开源社区要发展，就得有更多的人去贡献代码，而前端代码是必不可少的。再或者出现了BUG，有开发能力的人，也可以自己解决掉，而不是在github上面提bug，等待着解决。

如果是担心首页的推荐内容，也就是指向github连接，导向start被人取消掉的话，其实没有太大必要，因为实际上只需要在index.html里面加入一行css代码`display:none`代码，就可以隐藏掉了。

本人只是提一下意见，并是说索要代码这种意思，而是希望walle-web这种优质的项目，能得到更好的发展，得到社区的代码反馈，以更快的发展。最后，无论如何，都感谢作者开源出这么优质的项目，祝walle-web会越来越好

**Comment by baimoer** [comment]
@meolu

**Comment by meolu** [comment]
1.x是全部开源的，回馈太少了。2.0后端开源，提交上来的PR非常少，没有实质性的贡献，国内太缺乏奉献精神了，也太缺乏感恩之心。如果你曾维护了几年这个项目，每天遇到大量的伸手党，近三年来，没有一分钱的收获，付出大量的精力，晚睡早起，没有周末，这种孤独前行的体会实在不好受。少有像你这种既有能力，同时理解感谢我们的同行。

开放了确实是可以帮助更多的企业，但大多数企业是很浅层的使用，等待更新。我们有这样的私心想做出比jenkins更好用的部署工具，也有这样的能力。我们的计划是在2019年完成组建6人团队，不断稳定更新成为行业最好的部署工具，这是我们walle团队的理想。

有很多不为人知的辛酸和故事，但我依然在坚持，愿有更多理解我们的同行，愿有更多志同道合之人加入。
