### ISSUE TITLE
更新后tag展示不出来啦

### ISSUE THREAD

**Issue by a735465047** [meolu/walle-web#657]
**问题描述**
在`角色`下，什么页面，什么功能，报错：xx
|在`super超管`角色下，项目管理页面，编辑项目成员，提交失败，报错：用户不存在于空间用户组中

**问题描述**
日志堆栈贴上来。
logs/runtime.log
```
runtime...
```
logs/error.log
```
error...
```

**截图**
拖拽到此处即可上传
![image](https://user-images.githubusercontent.com/12880365/51510417-eb3a1e80-1e37-11e9-8b97-a0264577aeec.png)

**运行环境**
 - OS: [e.g. Centos 7.x]
 - 版本 [e.g. 2.0.0]

**Comment by meolu** [comment]
sorry, fixed
