### ISSUE TITLE
hook文档错误

### ISSUE THREAD

**Issue by Liv1020** [meolu/walle-web#68]
pre_deploy文档是pull代码之前，但是我使用的时候是pull代码之后，post_deploy而是sync目标服务器的relaese文件夹的时候，是文档错误了吧

**Comment by meolu** [comment]
宿主机
pre_deploy
git pull
post_deploy

目标机
pre_release
rsync
post_release

**Comment by Liv1020** [comment]
为什么我在pre_deploy的时候可以使用这样的语句
···php
cd /home/deploy/prod/project
cp .env.dist .env
···

**Comment by Richard87** [comment]
Hi!

This is what I'm using in PRE_RELEASE (hope it will help you)

	cd {VERSION}
	ln -sf /var/www/api-v2-current/static/parameters.yml app/config/parameters.yml
	ln -sf /var/www/api-v2-current/static/logs app/logs
	ln -sf /var/www/api-v2-current/static/cache app/cache
	COMPOSER_HOME="/var/www/composer" SYMFONY_ENV=prod composer install --no-dev --optimize-autoloader  --no-ansi  --no-interaction --no-progress

Notice the {VERSION} tag, haven't found that documented anywhere (@meolu)

**Comment by Liv1020** [comment]
@Richard87 pre_deploy is before git pull, but I can set this:
```shell
cp .env.dist .env
```
when this hook start, project is not pull

**Comment by meolu** [comment]
@Liv1020 

在pre_deploy里其实也是可以做这样的事情，只是代码都没有检出而已，也就是说没有`.env.dist`。脚本可以优化成这样：
```
cd {WORKSPACE}
cp .env.dist .env
```

 {WORKSPACE}在宿主机代表着检出的目录，也就是：`/home/deploy/prod/project`

另，如果代码是最新的话，流程肯定没有问题的。

**Comment by Liv1020** [comment]
@meolu 我奇怪的是pre_deploy代码没有检出，怎么可以复制文件呢？

**Comment by meolu** [comment]
而且copy成功了？

**Comment by Liv1020** [comment]
重点就是copy成功了

**Comment by meolu** [comment]
@Richard87 

{VERSION} exists target servers only, which is equal to the path of deploying version. English document is lack, I'am sorry for my poor English and time.

**Comment by Richard87** [comment]
I'll see if I can write a couple of lines about it when I get time :/

man. 30. nov. 2015 kl. 15.08 skrev huamanshu <notifications@github.com>:

**Comment by meolu** [comment]
@Liv1020 
你在部署的时候，可以tail着日志（默认在`/tmp/walle`）下，这样就知道发生什么事情了

**Comment by Richard87** [comment]
Yes, also we should change the log writer to "w+" instead of "w" so it
dosn't clear out the log on all new writes...

man. 30. nov. 2015 kl. 15.23 skrev huamanshu <notifications@github.com>:
