### ISSUE TITLE
账户权限方面 能否参考下 syncd ?

### ISSUE THREAD

**Issue by station19** [meolu/walle-web#689]
账户权限方面 能否参考下 syncd ? 默认那么多账户 哪能记得住,而且权限各不相同? 
搞个超级管理员, 然后创建别人的账户 分配对应的权限就好了

**Comment by meolu** [comment]
> 账户权限方面能否参考下 syncd ? 默认那么多账户 哪能记得住,而且权限各不相同?

默认账户是为了方便体验，权限模型思想跟gitlab一致，[http://walle-web.io/docs/permission.html](http://walle-web.io/docs/permission.html)

> 搞个超级管理员, 然后创建别人的账户 分配对应的权限就好了
现在就是这样的。
