### ISSUE TITLE
可以优化一下hook的交互吗

### ISSUE THREAD

**Issue by Liv1020** [meolu/walle-web#69]
![image](https://cloud.githubusercontent.com/assets/5382358/11465125/e165bbcc-9770-11e5-8cb0-107d4d522d18.png)
这个是国外的一个部署工具。仅供参考

**Comment by meolu** [comment]
请问这个是什么部署工具，借鉴学习下

**Comment by Liv1020** [comment]
这个是http://deploybot.com/，除了不可以tag部署，其他的很全面。我也想为walle-web项目寻找实现的方式。

**Comment by meolu** [comment]
嗯，这个一定会实现的，相信以后walle远不止现在这样。

目前的打算是先修完所在已经的问题，保持一个稳定的版本发布1.0，为了目前已经接入的企业可以保证正常的使用。接着开始做websocket，这工作要花上大半个月，将会全面接替现在的无限超时长链接、轮询、console，这过程需要一位前端同学配合，把前端做到极致的精细，到时walle将会成为部署领域的一个重要角色。

**Comment by meolu** [comment]
感谢你的信息，walle可以更多的借鉴和学习优化：）

**Comment by Liv1020** [comment]
不才，想贡献一点力量，但是这个方式不知道是否可以用。
```php
if(strlen($cmd)==0){
    $cmd = "cd /etc && ls -ls";
}
        $stream = ssh2_exec($this->conn,$cmd);
        stream_set_blocking($stream,true);
        while($line =  stream_get_line($stream,1024)){
            echo preg_replace("/\n/i",'<br/>',$line);
        }
        fclose($stream);
```

**Comment by meolu** [comment]
这种方式还真没调研过，得对比下ssh2_exec和exec，不错：）

**Comment by Richard87** [comment]
A challenge is that ssh2_exec is a external library for PHP and will raise the recuirements for the project... BUT it would be great to be able to execute commands individually and provide response pr command instead of all at once...

**Comment by Liv1020** [comment]
@Richard87 You're right , in fact, my first thought is to shell the results displayed hook :)

**Comment by meolu** [comment]
@Richard87 

you say the two sides of this option :+1:  there is a ext lib of git to operate git, as you say.

**Comment by meolu** [comment]
@Richard87 

你会看中文？（看你会这看懂这句不）

**Comment by Richard87** [comment]
Haha, I wish, I am a huge fan of google translate... but I'm sure it misses some of the meaning of your messages...

**Comment by meolu** [comment]
Ok, let me tell you the right answer:

Can you read Chinese? ( Do you understand this sentence )

and so you a picture about the beijing of november
![](http://ww4.sinaimg.cn/bmiddle/60718250jw1eyj5qdjimwj20c10b8t9w.jpg)

The missing building is CCTV Tower.
![](http://ww2.sinaimg.cn/bmiddle/60718250jw1eyj5qe2f3mj20c80iw3z4.jpg)

**Comment by Richard87** [comment]
Nope, can't read chinese (yet! It would be amazing to one day learn ;) )

That is insane, and tragic...

This is my where I live, Bergen, Norway:
http://blogg.bt.no/preik/2013/03/06/bergen-svikter-som-helseby/giftlokket/

A posionus cloud that appears every now and then  when the weather conditions are right:
http://blogg.bt.no/preik/2013/03/06/bergen-svikter-som-helseby/giftlokket/

(wich happens alot in the winter!)

**Comment by meolu** [comment]
Norway is a good place, I will travel to Norway for skateboard and the aurora if time and money is enough.

Enjoy it, Richard

**Comment by Richard87** [comment]
Thank you! Remember to stop by Bergen for a beer if you get the chance ;)
Not many auroras down here, but at least our mountains and the nature
sourounding Bergen is beutiful :)

man. 30. nov. 2015 kl. 16.30 skrev huamanshu <notifications@github.com>:

**Comment by Liv1020** [comment]
going to sleeping, want climb up immediately to going

**Comment by meolu** [comment]
Deal !

I'am waiting a chance, haha. But living in China is not easy, have to consider house, which wastes not only money but my youth, I can't do something I dreaming. Living non-freely : (

**Comment by Richard87** [comment]
Yes, it is very hard :( At least you have chosen an job/career in which you can find a job all over the world, and might be able to move somewhere web-development is more profitable :)

My dreams are running a startup in California and learning to surf :+1:

**Comment by yaochunxu** [comment]
@Richard87  Wow, lol,Norway is really beautiful, http://www.mafengwo.cn/i/996297.html
