### ISSUE TITLE
Docker --link flag is about to be removed

### ISSUE THREAD

**Issue by wi1dcard** [meolu/walle-web#692]
**现存什么问题没有很好被解决**

In the `docker-compose` documentation:

<https://docs.docker.com/compose/compose-file/#links>

> Warning: The --link flag is a legacy feature of Docker. It may eventually be removed. Unless you absolutely need to continue using it, we recommend that you use user-defined networks to facilitate communication between two containers instead of using --link. One feature that user-defined networks do not support that you can do with --link is sharing environmental variables between containers. However, you can use other mechanisms such as volumes to share environment variables between containers in a more controlled way.

But that somehow is still in walle's installation guide:

<https://walle-web.io/docs/installation_docker.html#Prepare-Before-Deploy>

```yml
    links:
      - python
```

**Comment by Alenx58** [comment]
@wi1dcard 这个还没更新
