### ISSUE TITLE
mysql 初始化失败

### ISSUE THREAD

**Issue by zzvv** [meolu/walle-web#70]
环境安装完毕，并且`composer`编译正常， 执行`./yii run/setup` 初始化数据库，被提示需要输入数据库密码，无法连接。已在配置文件中添加有密码相关配置，依然无效  :weary:

**Comment by meolu** [comment]
`config/local.php`里的`db`模块配置下用户名密码，确认这用户名密码可读写数据库？

**Comment by zzvv** [comment]
close
