### ISSUE TITLE
发布上线单的时候如果分支和版本信息为空的时候仍然可发布

### ISSUE THREAD

**Issue by xbw1220** [meolu/walle-web#704]
**问题描述**
在`角色`下，什么页面，什么功能，报错：xx
|在`开发者`角色下，发布上线单的时候如果分支和版本信息为空的时候仍然可发布

**截图**
![tim 20190219155748](https://user-images.githubusercontent.com/30739769/52998906-60ad0500-345f-11e9-8a55-7a3a9155e475.png)
![tim 20190219155801](https://user-images.githubusercontent.com/30739769/52998909-630f5f00-345f-11e9-86ff-bd81e70b761a.png)

**运行环境**
 - OS: [e.g. Centos 7.x]
 - 版本 [e.g. 2.0.0]

**Comment by meolu** [comment]
已开启限制
