### ISSUE TITLE
PROJECT_NAME 有双引号

### ISSUE THREAD

**Issue by Paul0523** [meolu/walle-web#709]
**问题描述**
在`角色`下，什么页面，什么功能，报错：xx
|在`super超管`角色下，项目管理页面，编辑项目成员，提交失败，报错：用户不存在于空间用户组中

**问题描述**
日志堆栈贴上来。
logs/runtime.log
```
runtime...
```
logs/error.log
```
error...
```

**截图**
拖拽到此处即可上传
![image](https://user-images.githubusercontent.com/11917690/53286713-8e6eb280-37ad-11e9-9cfa-fe25e4682f23.png)

**运行环境**
 - OS: [e.g. ubuntu 16]
 - 版本 [e.g. 2.0.0]

**Comment by Paul0523** [comment]
这个是我写的有问题吗？echo 了下变量看到 PROJECT_NAME 前后有引号

**Comment by meolu** [comment]
嗯，这个是为了防止变量失效而为。

但我想到了更好的办法，可以把引号去掉
