### ISSUE TITLE
BUG-dploy阶段,不会清理之前CP出来的项目版本库目录,导致磁盘很快被占满

### ISSUE THREAD

**Issue by xbw1220** [meolu/walle-web#711]
**问题描述**
在`角色`下，什么页面，什么功能，报错：xx
|在`super超管`角色下，项目管理页面，编辑项目成员，提交失败，报错：用户不存在于空间用户组中

**问题描述**
日志堆栈贴上来。
logs/runtime.log
```
runtime...
```
logs/error.log
```
error...
```

**截图**
拖拽到此处即可上传

**运行环境**
 - OS: [e.g. Centos 7.x]
 - 版本 [e.g. 2.0.0]

**Comment by xbw1220** [comment]
![image](https://user-images.githubusercontent.com/30739769/53297769-2c21ba80-385e-11e9-9061-5386c1f23c04.png)
目前只能这样设置deploy前置任务

**Comment by meolu** [comment]
这就修下

**Comment by meolu** [comment]
更新使用，可以把自定义任务删了
