### ISSUE TITLE
BUG-前端代码是否有问题?

### ISSUE THREAD

**Issue by xbw1220** [meolu/walle-web#719]
**问题描述**
在`角色`下，什么页面，什么功能，报错：xx
重新git clone一份代码后,修改HOST和数据库连接打开walle是空白页,后来把之前备份的fe复制到新clone的目录中就显示页面了

**问题描述**
日志堆栈贴上来。
logs/runtime.log
```
runtime...
```
logs/error.log
```
error...
```

**截图**
拖拽到此处即可上传

**运行环境**
 - OS: [e.g. Centos 7.x]
 - 版本 [e.g. 2.0.0]

**Comment by meolu** [comment]
前端更新完成。

**Comment by meolu** [comment]
提前预告下，下一版本的主题侧重于前端，登录页面将会开启全新主题《繁星》

**Comment by xbw1220** [comment]
还是比较关注多人发布这块...
