### ISSUE TITLE
添加新功能

### ISSUE THREAD

**Issue by huangdongliang** [meolu/walle-web#72]
你好：
    我对瓦力这个系统非常看好，并在测试线已经试用，目前功能还不太多。对于我们纯java的项目，部署完成后肯定要重启，我们想知道java启动过程的情况，只能登陆到服务器上去看日志，能不能在页面看弄一个在线实时日志的功能（京东以前就有这样的功能）。另外每个线上的数据库配置肯定不一样，能不能把这些重要的信息直接网页上修改，这个权限优先级最大，部署到目标机器上这个优先生效。对运维来说更安全。而且也方便管理这些敏感信息。

**Comment by meolu** [comment]
第一个功能也是排在todo list的第一位，部署过程的console总是会让人更安心，这需要一段开发时间，请相信我也是着急的。

第二个推荐的做法就是代码库写多份配置`db.test.conf`，`db.stage.conf`，`db.production.conf`，在不同的环境中，在高级任务post_deploy里写行shell切换`mv db.stage.conf db.conf`。不知道我说的跟你说是一个事儿不

**Comment by huangdongliang** [comment]
首先感谢哥们你能回复我，第一个功能确实应该是java项目需要的。
第二个问题是，你的确实也没有做到，我们现在的做法是mvn 中加参数 比如mvn clean package -P prd 这个就是生产环境。 我的意思是，通过网页直接读取到这个配置文件，添加到网页上面，这个每次部署优先生效，它会覆盖每次部署这个文件，如果要想修改了直接修改网页就这个配置文件就可以，如果不用 删除网页这个配置文件就行。

**Comment by meolu** [comment]
我再重复一次第二个需求，确认理解是否一致。

可以确认的是，每次上线编译不会手动去修改编译的参数。在这个前提上，就意味着在不同的环境可以有独立的一份配置，只需要在上线的时候读取该配置做相关的工作，如编译。这个walle可以做到的，直接在项目配置高级任务的时候写即可，比如测试环境的编译可：mvn clean package -P test，这命令可写到一个命名为test-compile.sh里，在post_deploy里`sh test-compile.sh`即可，线上环境：`sh prd-compile.sh`。至于页面上直接配置一些常量或者脚本，这个后面才能支持，也是在todo list中。

**Comment by huangdongliang** [comment]
恩，对的我们的思路都是一样的。不过我说的意思是直接网页上修改配置文件，而这个文件拥有最高的优先级，而不需要脚本干预去使用那个配置文件。更期待你们的更多功能，这个项目是我现在用过的功能比较多的一个自动部署工具。给贴一个我们的post_deploy，
cd {WORKSPACE}-svn/cc-web
/data/server/apache-maven-3.2.2/bin/mvn clean package -P test
unzip {WORKSPACE}-svn/cc-web/target/ROOT.war -d {WORKSPACE}

**Comment by littlehz** [comment]
issue超时关闭
