### ISSUE TITLE
BUG-多人同时发布仍然有问题未解决

### ISSUE THREAD

**Issue by xbw1220** [meolu/walle-web#720]
**问题描述**
在`角色`下，什么页面，什么功能，报错：xx
|在`super超管`角色下，项目管理页面，编辑项目成员，提交失败，报错：用户不存在于空间用户组中

**问题描述**
日志堆栈贴上来。
logs/runtime.log
```
runtime...
```
logs/error.log
```
error...
```

**截图**
![_20190225223008](https://user-images.githubusercontent.com/30739769/53344165-fe676f00-394c-11e9-8e45-a38b0a989271.png)

**运行环境**
walle commit d45813bf
 - OS: [e.g. Centos 7.x]
 - 版本 [e.g. 2.0.0]

**Comment by xbw1220** [comment]
失败的项目启动的是另一个正在发布的项目

**Comment by meolu** [comment]
walle部署页面是用websocket，在多窗口下，后端都会向所有该上线单双向同步。但也仅仅是同步，如果后端停止了，多窗口的前端页面都会收到后端发过来停止的消息。

自测没有问题，看你的截图右边的窗口下面看不到了，按道理下面的内容会跟左侧窗口一样的。

**Comment by meolu** [comment]
看了下你采用的版本：d45813b是我昨晚发布的，有个小问题，建议更新下

**Comment by xbw1220** [comment]
已更新,我让测试那边验证下..

**Comment by xbw1220** [comment]
还未解决变量会被影响的问题,具体的内容在我另一个没有关闭的issue中回复了
