### ISSUE TITLE
关于标准安装nginx配置之后500 像是伪静态有问题

### ISSUE THREAD

**Issue by lvxj** [meolu/walle-web#728]
昨天我用docker安装后，遇到的问题，今天想用标准安装然后拉代码，标准安装一切都搞好了，配置完nginx伪静态就报错500 ，看了nginx报错信息 大概是伪静态错误，我贴出来：

我的nginx报错信息：
2019/02/26 18:35:14 [error] 29095#0: *10 rewrite or internal redirection cycle while internally redirecting to "/index.html", client: 127.0.0.1, server: admin.walle-web.io, request: "GET / HTTP/1.1", host: "admin.walle-web.io"
2019/02/26 18:34:42 [error] 29095#0: *8 rewrite or internal redirection cycle while internally redirecting to "/index.html", client: 192.168.10.251, server: admin.walle-web.io, request: "GET /index.html HTTP/1.1", host: "admin.walle-web.io"

我的nginx配置：
upstream webservers {
    server 0.0.0.0:5000 weight=1; # 负载设置
}
server {
    listen       80;
    server_name  admin.walle-web.io; # 域名设置
    access_log   /usr/local/nginx/logs/walle.log;
    error_log   /usr/local/nginx/logs/walle_error.log;
    index index.html index.htm; # 日志目录

    location / {
        try_files $uri $uri/ /index.html;
	#try_files $uri $uri/ =404;
        add_header access-control-allow-origin *;
        root /walle-web/fe; # 前端代码已集成到walle-web，即walle-web/fe的绝对路径
    }

    location ^~ /api/ {
        add_header access-control-allow-origin *;
        proxy_pass      http://webservers;
        proxy_set_header X-Forwarded-Host $host:$server_port;
        proxy_set_header  X-Real-IP  $remote_addr;
        proxy_set_header    Origin        $host:$server_port;
        proxy_set_header    Referer       $host:$server_port;
    }

    location ^~ /socket.io/ {
        add_header access-control-allow-origin *;
        proxy_pass      http://webservers;
        proxy_set_header X-Forwarded-Host $host:$server_port;
        proxy_set_header  X-Real-IP  $remote_addr;
        proxy_set_header    Origin        $host:$server_port;
        proxy_set_header    Referer       $host:$server_port;
        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;

        # WebScoket Support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}

**Comment by lvxj** [comment]
哦 不好意思 是我SB了 ，项目目录所在路径没有改 解决了  thanks

**Comment by gxjluck** [comment]
2.0版本还是有这个问题
