### ISSUE TITLE
安装提示jquery目录不存在，应该是bower-asset/jquery

### ISSUE THREAD

**Issue by xonze** [meolu/walle-web#73]
Error: The file or directory to be published does not exist: D:\xampp\htdocs\walle-web\vendor\bower/jquery/dist

应该是vendor/bower-asset/jquery/目录

**Comment by meolu** [comment]
win下不支持，转linux服务器去吧

**Comment by xonze** [comment]
ok，原来如此

**Comment by xonze** [comment]
Error: The file or directory to be published does not exist: /data/www/walle-web/vendor/bower/jquery/dist

Linux服务器一样的提示

**Comment by meolu** [comment]
mkdir 不存在的那个目录
