### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by changeyourt** [meolu/walle-web#746]
**问题描述**
角色：空间的Owner
页面：部署管理
功能：回滚
回滚提交人和执行人：空间Owner

报错日志：
![error](https://user-images.githubusercontent.com/45409457/53774526-e33ac780-3f29-11e9-8c08-18d3957a973b.png)

**运行环境**
![image](https://user-images.githubusercontent.com/45409457/53774612-30b73480-3f2a-11e9-9a77-1c9670940dcc.png)

部署形式：容器部署

**Comment by changeyourt** [comment]
另外容器的docker-compose.yml中，有一个路径错了。
/data/walle_home:/opt/walle_home
文档中写成了：/data/walle_home:/opt/walle-web
所以启动时，无法启动。

**Comment by meolu** [comment]
好的，我确认下

**Comment by meolu** [comment]
已更新，谢谢

**Comment by changeyourt** [comment]
前面的回滚报错帮忙看下呗!

**Comment by changeyourt** [comment]
> 已更新，谢谢
前面的回滚帮忙看下呗！
