### ISSUE TITLE
BUG 用户管理和环境管理以及所有列表位置的编辑功能，会产生两条相同的记录，即编辑会新增一条

### ISSUE THREAD

**Issue by gufei** [meolu/walle-web#751]
**问题描述**
用户管理和环境管理以及所有列表位置的编辑功能，会产生两条相同的记录，即编辑会新增一条

**Comment by ZouHongxue** [comment]
> **问题描述**
> 用户管理和环境管理以及所有列表位置的编辑功能，会产生两条相同的记录，即编辑会新增一条

您好，我没有复现这个情况,能给出一些更加详细的信息吗？
