### ISSUE TITLE
回滚报错

### ISSUE THREAD

**Issue by changeyourt** [meolu/walle-web#760]
![default](https://user-images.githubusercontent.com/45409457/53880398-d615f980-404b-11e9-9684-f65b005376f6.png)

修改文件：walle/api/task.py中的

task['id'] = None
        task['name'] = task['name'] + '-回滚此次上线'   # 修改此处即可，把横杠去掉即可
        task['link_id'] = task['ex_link_id']
        task['ex_link_id'] = ''
        task['is_rollback'] = 1
        task['status'] = TaskModel.task_default_status(task['project_id'])

修改后，重启容器walle，即可。
![default](https://user-images.githubusercontent.com/45409457/53880368-c3032980-404b-11e9-918d-743dc8acba9e.png)

**Comment by meolu** [comment]
更新下版本吧，前两天已经做了export中`TASK_NAME`问题
