### ISSUE TITLE
关于百度统计

### ISSUE THREAD

**Issue by DYDYSY** [meolu/walle-web#78]
http://hm.baidu.com/hm.js?5fc7354aff3dd67a6435818b8ef02b52
请问这个是作者的百度统计代码吗？
如果是统计功能，请问为会暴露我们的域名吗？

**Comment by meolu** [comment]
是统计代码，推荐部署内网，即使知道了域名（只有我）也不会有安全问题，如果觉得不想让我知道，可以去了统计代码

**Comment by DYDYSY** [comment]
我知道你不会坑咱们。
但假如这个系统有什么漏洞，然后加上你的百度帐号被黑，那这就麻烦大了。
我觉得加个提醒比较好，毕竟有人可能不知道入口地址可能不是隐私了，说不定密码都没设置。

**Comment by meolu** [comment]
已经在文档和nginx配置里提醒开启内网访问，有时看到外网可访问的域名，都会通知其开启内网访问设置。

后面我加粗提醒，防止粗心同学
