### ISSUE TITLE
新建上线单、上线时间都不变

### ISSUE THREAD

**Issue by ahhbjz** [meolu/walle-web#785]
**问题描述**
每次启动后，项目的创建、发布时间都一样，只有重启才会变一次

**截图**
<img width="1021" alt="WechatIMG3" src="https://user-images.githubusercontent.com/5388422/54348042-32e46600-4683-11e9-8211-e168b4cd56c8.png">

**运行环境**
 - OS: [e.g. Centos 7.4]
 - 版本 [e.g. 2.0.0]

**Comment by ZouHongxue** [comment]
![image](https://user-images.githubusercontent.com/20573881/54356007-7fd13800-4695-11e9-98fa-14da01b45e06.png)
没有复现你的这个情况，有什么前置条件吗

**Comment by ahhbjz** [comment]
没有，就是按照文档安装的，我把walle升级到最新版，还是不行呢

**Comment by ahhbjz** [comment]
![image](https://user-images.githubusercontent.com/5388422/54356887-a7290480-4697-11e9-864e-0d9d11d79e66.png)

**Comment by flying1020** [comment]
> ![image](https://user-images.githubusercontent.com/20573881/54356007-7fd13800-4695-11e9-98fa-14da01b45e06.png)
> 没有复现你的这个情况，有什么前置条件吗

应该是今天水哥说的那个 datatime.now 和 大datatime.now() 的问题.
在 model 中的几个类里的 dict 数据结构中,不能写 datatime.now(),否则在解释的时候,会预处理为常亮.

**Comment by ZouHongxue** [comment]
> 应该是今天水哥说的那个 datatime.now 和 大datatime.now() 的问题.
> 在 model 中的几个类里的 dict 数据结构中,不能写 datatime.now(),否则在解释的时候,会预处理为常亮.
好的，那飞哥你来修复一下呗。

**Comment by ahhbjz** [comment]
时间字段用timestamp加on update自动触发更新时间，不写时间字段也ok的

**Comment by ahhbjz** [comment]
哥们，修复了完了回复下，谢谢哈！

**Comment by meolu** [comment]
@ahhbjz 贴下walle的commit_id

**Comment by ahhbjz** [comment]
我把代码放到自己的git里面了，看不到..

**Comment by qingfenglaike** [comment]
我这边也是这情况，更新时间一直都是启动walle的时间

**Comment by flying1020** [comment]
> 
> 
> > 应该是今天水哥说的那个 datatime.now 和 大datatime.now() 的问题.
> > 在 model 中的几个类里的 dict 数据结构中,不能写 datatime.now(),否则在解释的时候,会预处理为常亮.
> > 好的，那飞哥你来修复一下呗。

我看了下，水哥已经修复了。

**Comment by mrjooz** [comment]
升级前先 git stash 暂存，升级好再弹出，不要直接运行升级。

**Comment by ahhbjz** [comment]
ok了，谢谢

**Comment by flying1020** [comment]
这个问题已经修复，所以及时 close 掉了。如果升级后仍然存在问题，请再  reopen。请随意提交 issue，谢谢。

**Comment by jeftom** [comment]
我的也出现了类似情况，records 表的 create_at 和 update_at 都变成了一样的日期。具体是怎么复制没有留意到
