### ISSUE TITLE
安装疑问

### ISSUE THREAD

**Issue by zzvv** [meolu/walle-web#79]
看示例nginx配置中把请求有upstream 到127.0.0.1:9000这个端口应用上。但是我本地netstatus 查看并没有这个端口启动，是需要怎样手动启动吗？我看了acess.log日志，就是这个链接不能跳转的原因。造成502

**Comment by meolu** [comment]
php-fpm监听socket有两种方式，ip socket 或者 unix socket，看下你的php-fpm.conf 的listen是哪个，如果不是ip:port，那就换成unix:xxx.sock

**Comment by zzvv** [comment]
>
> ; FPM Configuration ; ;;;;;;;;;;;;;;;;;;;;; ;;;;;;;;;;;;;;;;;; ; Global
> Options ; ;;;;;;;;;;;;;;;;;; [global] pid = run/php-fpm.pid error_log =
> log/php-fpm.log log_level = warning emergency_restart_threshold = 30
> emergency_restart_interval = 60s process_control_timeout = 5s daemonize =
> yes ;;;;;;;;;;;;;;;;;;;; ; Pool Definitions ; ;;;;;;;;;;;;;;;;;;;; [www]
> listen = /dev/shm/php-cgi.sock listen.backlog = -1 listen.allowed_clients =
> 127.0.0.1 listen.owner = www listen.group = www listen.mode = 0666 user =
> www group = www pm = dynamic pm.max_children = 46 pm.start_servers = 30
> pm.min_spare_servers = 23 pm.max_spare_servers = 46 pm.max_requests = 2048
> pm.process_idle_timeout = 10s request_terminate_timeout = 120
> request_slowlog_timeout = 0 pm.status_path = /php-fpm_status slowlog =
> log/slow.log rlimit_files = 51200 rlimit_core = 0 catch_workers_output =
> yes ;env[HOSTNAME] = 192.168.202.112 env[PATH] =
> /usr/local/bin:/usr/bin:/bin env[TMP] = /tmp env[TMPDIR] = /tmp




我直接把php-fpm的配置给贴上来了。是否是在127.0.0.1后面需要添加个端口？

**Comment by zzvv** [comment]
😊google到了配置方法，终于见到界面了。。 不过还有报错，我再继续折腾下。暂时不要关闭这个issues

2015-12-17 16:54 GMT+08:00 tory zzcv <2pporg@gmail.com>:

> ; FPM Configuration ; ;;;;;;;;;;;;;;;;;;;;; ;;;;;;;;;;;;;;;;;; ; Global
>> Options ; ;;;;;;;;;;;;;;;;;; [global] pid = run/php-fpm.pid error_log =
>> log/php-fpm.log log_level = warning emergency_restart_threshold = 30
>> emergency_restart_interval = 60s process_control_timeout = 5s daemonize =
>> yes ;;;;;;;;;;;;;;;;;;;; ; Pool Definitions ; ;;;;;;;;;;;;;;;;;;;; [www]
>> listen = /dev/shm/php-cgi.sock listen.backlog = -1 listen.allowed_clients =
>> 127.0.0.1 listen.owner = www listen.group = www listen.mode = 0666 user =
>> www group = www pm = dynamic pm.max_children = 46 pm.start_servers = 30
>> pm.min_spare_servers = 23 pm.max_spare_servers = 46 pm.max_requests = 2048
>> pm.process_idle_timeout = 10s request_terminate_timeout = 120
>> request_slowlog_timeout = 0 pm.status_path = /php-fpm_status slowlog =
>> log/slow.log rlimit_files = 51200 rlimit_core = 0 catch_workers_output =
>> yes ;env[HOSTNAME] = 192.168.202.112 env[PATH] =
>> /usr/local/bin:/usr/bin:/bin env[TMP] = /tmp env[TMPDIR] = /tmp
>
>
>
>
> 我直接把php-fpm的配置给贴上来了。是否是在127.0.0.1后面需要添加个端口？
>

**Comment by zzvv** [comment]
`/data/wwwroot/walle/vendor/bower/jquerry `

我看了下我的vendor目录，貌似没有这个bower文件夹。是因为包没下载全的原因？



2015-12-17 17:00 GMT+08:00 tory zzcv <2pporg@gmail.com>:

> 😊google到了配置方法，终于见到界面了。。 不过还有报错，我再继续折腾下。暂时不要关闭这个issues
>
> 2015-12-17 16:54 GMT+08:00 tory zzcv <2pporg@gmail.com>:
>
>> ; FPM Configuration ; ;;;;;;;;;;;;;;;;;;;;; ;;;;;;;;;;;;;;;;;; ; Global
>>> Options ; ;;;;;;;;;;;;;;;;;; [global] pid = run/php-fpm.pid error_log =
>>> log/php-fpm.log log_level = warning emergency_restart_threshold = 30
>>> emergency_restart_interval = 60s process_control_timeout = 5s daemonize =
>>> yes ;;;;;;;;;;;;;;;;;;;; ; Pool Definitions ; ;;;;;;;;;;;;;;;;;;;; [www]
>>> listen = /dev/shm/php-cgi.sock listen.backlog = -1 listen.allowed_clients =
>>> 127.0.0.1 listen.owner = www listen.group = www listen.mode = 0666 user =
>>> www group = www pm = dynamic pm.max_children = 46 pm.start_servers = 30
>>> pm.min_spare_servers = 23 pm.max_spare_servers = 46 pm.max_requests = 2048
>>> pm.process_idle_timeout = 10s request_terminate_timeout = 120
>>> request_slowlog_timeout = 0 pm.status_path = /php-fpm_status slowlog =
>>> log/slow.log rlimit_files = 51200 rlimit_core = 0 catch_workers_output =
>>> yes ;env[HOSTNAME] = 192.168.202.112 env[PATH] =
>>> /usr/local/bin:/usr/bin:/bin env[TMP] = /tmp env[TMPDIR] = /tmp
>>
>>
>>
>>
>> 我直接把php-fpm的配置给贴上来了。是否是在127.0.0.1后面需要添加个端口？
>>
>
>

**Comment by meolu** [comment]
```mkdir -p /data/wwwroot/walle/vendor/bower/jquerry```

**Comment by zzvv** [comment]
手动添加后还算报错，我看到composer.json中有一段代码是
    "extra": {
        "asset-installer-paths": {
            "npm-asset-library": "vendor/npm",
            "bower-asset-library": "vendor/bower"
        }

是不是需要重新composer再下载一次包？或者直接把您百度盘的包丢进去？

2015-12-17 17:07 GMT+08:00 huamanshu <notifications@github.com>:

**Comment by zzvv** [comment]
`Error: The file or directory to be published does not exist: /data/wwwroot/walle-web/vendor/bower/jquery/dist` 


但是真实路径是


`/data/wwwroot/walle-web/vendor/bower-asset/jquery/dist/jquery.js`

**Comment by zzvv** [comment]
手动修改路径 copy代码过去后，终于看到login界面了，太不容易

**Comment by meolu** [comment]
额，难为你了，可以直接下载我准备好的vendor，这样更方便你

**Comment by zzvv** [comment]
默认一般php-fpm安装完毕会使用 `unix:xxx.sock`作为监听方式.需要调整`php/etc/`下php-fpm配置文件中关于`[www]`的配置为
```shell 
 [www]
  #listen = /dev/shm/php-cgi.sock
  listen=127.0.0.1:9000
```
