### ISSUE TITLE
BUG  CentOS 6.9中 source /etc/os-release  获取系统名称错误

### ISSUE THREAD

**Issue by dodosong** [meolu/walle-web#795]
**问题描述**
使用root进行sh admin.sh安装时报错： “admin.sh: line 37: /etc/os-release: 没有那个文件或目录”

**原因及解决方案**
Centos 6.9中不存在/etc/os-release文件，需要使用 cat /etc/centos-release 获取

**运行环境**
 - OS: [e.g. Centos 6.9]

**Comment by ZouHongxue** [comment]
手动执行下  source /etc/os-release   有问题吗？
这句话是在admin.sh中的，不行就注释掉执行。

**Comment by ZouHongxue** [comment]
> 解决方案
> cat /etc/centos-release

nice，把这个Issue标签改为helps吧

**Comment by dodosong** [comment]
Centos6下手动安装相关依赖
`sudo yum install -y mysql-devel gcc gcc-c++ python-devel MySQL-python`
然后注掉[第18行](https://github.com/meolu/walle-web/blob/f8a02033b2e0b807d121cac829c4c3219f74a03f/admin.sh#L18)SystemName后再执行 sh admin.sh init

**Comment by jkpeng** [comment]
先执行命令 查看自己是什么系统：
`cat /proc/version`

我是`centos`执行命令：
`sudo sh -c "echo 'ID=centos' >/etc/os-release"`
接下来就可以执行
`sudo sh admin.sh init`
