### ISSUE TITLE
网站的安装教程什么时候能更新，没写明白，怎么装都失败！

### ISSUE THREAD

**Issue by liaogx** [meolu/walle-web#798]
按照这个教程[https://walle-web.io/docs/installation.html](https://walle-web.io/docs/installation.html)，也就只有开发者自己能安装成功了

**Comment by flying1020** [comment]
非常抱歉，请问在哪一步失败了呢？

**Comment by ruoge3s** [comment]
试试我搭建了compose版的吧。https://github.com/ruoge3s/release

**Comment by mrjooz** [comment]
这个教程很清楚啊，一步一步走，基本没什么问题。
