### ISSUE TITLE
FastCGI Primary script unknown

### ISSUE THREAD

**Issue by xiyoulaoyuanjia** [meolu/walle-web#8]
2015/10/13 23:54:44 [error] 18064#0: *201 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 127.0.0.1, server: 127.0.0.1, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "127.0.0.1"

server {
    listen       80;
    server_name  127.0.0.1; # 改你的host
    root /home/test/Desktop/walle-web/web;
    index index.php;

    # 建议放内网
    allow 127.0.0.1;
    deny all;

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_pass   unix:/var/run/php5-fpm.sock;
        fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
        include        fastcgi_params;
    }
}

＃＃＃＃＃相关环境

$ /usr/sbin/nginx -v      
nginx version: nginx/1.4.6 (Ubuntu)
$ 

$ /usr/sbin/php5-fpm -v
PHP 5.5.9-1ubuntu4.13 (fpm-fcgi) (built: Sep 29 2015 15:28:48)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with XCache v3.1.0, Copyright (c) 2005-2013, by mOo
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
    with XCache Optimizer v3.1.0, Copyright (c) 2005-2013, by mOo
    with XCache Cacher v3.1.0, Copyright (c) 2005-2013, by mOo
    with XCache Coverager v3.1.0, Copyright (c) 2005-2013, by mOo
$

**Comment by meolu** [comment]
php 监听用的是socket方式，还是端口？fastcgi_pass /var/run/php5-fpm.sock 是活跃的？

这个nginx 1.4版本有点低，不知道有没有什么兼容性问题

**Comment by xiyoulaoyuanjia** [comment]
1. nginx 升级到了1.8了,还是不行
$ /usr/sbin/nginx -v
nginx version: nginx/1.8.0
$ 
２．　php 监听方式不管是socket, 9000端口都尝试了，还是不行．

**Comment by xiyoulaoyuanjia** [comment]
晕，可能还是权限的问题，最后搞定方式:

nginx , php 都是root 用户运行．．

其中　php root 运行 修改　/etc/php5/fpm/pool.d/www.conf　文件
[www]
user = root
group = root

sudo php5-fpm -R

**Comment by meolu** [comment]
亲，不建议用root哦，不安全，可以起一个nobody/www之类的来跑就好：）

**Comment by xiyoulaoyuanjia** [comment]
恩，这个是的，这里只是调试了下，感谢哈！
