### ISSUE TITLE
缺失初始化项目的目录

### ISSUE THREAD

**Issue by zhongjimax** [meolu/walle-web#80]
代码分支：master
下载日期：昨天（2015-12-17）
问题：初始化项目缺失（./yii migrate/up）
尝试的方法：1、参考FAQ（无解）。2、参考【issue】（无解）

具体描述如下：
安装至【php composer install --prefer-dist --no-dev --optimize-autoloader –vvvv】，当需要初始化的时候，参考【README.md】里的提示并没有找到相关信息【migrate/up】。

以下是代码的目录：
drwxr-xr-x 2 root root  4096 12月 17 15:30 assets
drwxr-xr-x 2 root root  4096 12月 17 15:30 components
-rw-r--r-- 1 root root   948 12月 17 15:30 composer.json
-rw-r--r-- 1 root root 21537 12月 18 09:45 composer.lock
drwxr-xr-x 2 root root  4096 12月 18 09:56 config
drwxr-xr-x 3 root root  4096 12月 17 15:30 console
drwxr-xr-x 2 root root  4096 12月 17 15:30 controllers
drwxr-xr-x 2 root root  4096 12月 17 15:30 docs
-rw-r--r-- 1 root root 10255 12月 17 15:30 LICENSE
drwxr-xr-x 3 root root  4096 12月 17 15:30 mail
drwxr-xr-x 3 root root  4096 12月 17 15:30 messages
drwxr-xr-x 2 root root  4096 12月 17 15:30 migrations
drwxr-xr-x 5 root root  4096 12月 17 15:30 models
-rw-r--r-- 1 root root  4757 12月 17 15:30 README.md
drwxr-xr-x 2 root root  4096 12月 17 15:30 runtime
drwxr-xr-x 2 root root  4096 12月 17 15:30 screenshots
drwxr-xr-x 3 root root  4096 12月 17 15:30 tests
drwxr-xr-x 9 root root  4096 12月 18 09:45 vendor
drwxr-xr-x 8 root root  4096 12月 17 15:30 views
drwxr-xr-x 5 root root  4096 12月 17 15:30 web
drwxr-xr-x 2 root root  4096 12月 17 15:30 widgets
-rwxr-xr-x 1 root root   893 12月 17 15:30 yii

找不到初始化项目的目录，下一步该如何走？

**Comment by meolu** [comment]
看目录已经有vendor，表示你composer安装完，如果没有的话，可以直接下载我准备好的vendor。

修改下你的数据库连接句柄```config/local.php```的db模块。

接下来就是``` ./yii run/setup``` 即可初始化完毕。

如果没有报错，也配好nginx，就可以浏览器打开了

**Comment by zhongjimax** [comment]
不好意思，请问作者提供的【vendor】在哪里下载？

**Comment by meolu** [comment]
见[文档](http://doc.huamanshu.com/%E7%93%A6%E5%8A%9B/2.%E5%AE%89%E8%A3%85/%E5%AE%89%E8%A3%85.html)安装部分[vendor](http://pan.baidu.com/s/1c0wiuyc)
