### ISSUE TITLE
项目检测通不过,求助

### ISSUE THREAD

**Issue by lobber1987** [meolu/walle-web#81]
[error内容]
宿主机代码检出检测出错，请确认php进程用户www有代码存储仓库/var/htdocs/deploy/from读写权限，并且把ssh-key加入git的deploy-keys列表。详细错误：

目录权限已是777，ssh-key已加入git服务器的keys列表，在目标机器上能够正常git操作。

请问是什么原因呢？

**Comment by lobber1987** [comment]
检测发现component/Git.php的updateRepo方法中执行的git命令前面都有/usr/bin/env，导致component/command/Command.php的runLocalCommand方法中的exec函数返回状态127，请问这个是神马原因？

**Comment by meolu** [comment]
tail -f /tmp/walle/当天日志，如果没有修改配置中日志的目录。然后重新检查，看报的具体错误，贴上来，我帮看下
