### ISSUE TITLE
后台服务未启动

### ISSUE THREAD

**Issue by 2804337402** [meolu/walle-web#820]
**问题**：错误信息
访问web页面，提示后台服务未启动

**解决**：
怎么解决？？？？

**Comment by flying1020** [comment]
1. 检查后台启动成功了吗？有没有报错？
2. 如果 1 为 true，检查后台服务启动的时候相应的参数有没有修改正确，尤其是绑定的 host  和 port。
3. 如果 2 没问题，请检查 nginx 配置。
如果有问题，再反馈，谢谢。

**Comment by 2804337402** [comment]
错误信息：
fe/api/general/info（fe目录下都没有api这个文件，walle目录下就有api这个文件）
[root@docker-k8s-node001 walle-web]# more logs/error.log 
[root@docker-k8s-node001 walle-web]# more logs/info.log 
[root@docker-k8s-node001 walle-web]# more logs/runtime.log 
Server initialized for gevent.
Server initialized for gevent.
more /var/log/nginx/error.log
2019/03/27 22:58:53 [error] 16008#0: *2 open() "/root/soft/install/walle-web/fe/api/general/menu" failed (2: No such file or directory), client: 192.168.238.1, server:
 192.168.238.10, request: "GET /api/general/menu HTTP/1.1", host: "192.168.238.10", referrer: "http://192.168.238.10/"
2019/03/27 22:58:53 [error] 16008#0: *2 open() "/root/soft/install/walle-web/fe/404.html" failed (2: No such file or directory), client: 192.168.238.1, server: 192.168
.238.10, request: "GET /api/general/menu HTTP/1.1", host: "192.168.238.10", referrer: "http://192.168.238.10/"
2019/03/27 22:58:53 [error] 16005#0: *1 open() "/root/soft/install/walle-web/fe/api/general/info" failed (2: No such file or directory), client: 192.168.238.1, server:
 192.168.238.10, request: "GET /api/general/info HTTP/1.1", host: "192.168.238.10", referrer: "http://192.168.238.10/"
2019/03/27 22:58:53 [error] 16005#0: *1 open() "/root/soft/install/walle-web/fe/404.html" failed (2: No such file or directory), client: 192.168.238.1, server: 192.168
.238.10, request: "GET /api/general/info HTTP/1.1", host: "192.168.238.10", referrer: "http://192.168.238.10/"

**Comment by 2804337402** [comment]
nginx配置
[root@docker-k8s-node001 walle-web]# more /etc/nginx/nginx.conf
# For more information on configuration, see:
#   * Official English Documentation: http://nginx.org/en/docs/
#   * Official Russian Documentation: http://nginx.org/ru/docs/

user root;
worker_processes auto;
error_log /var/log/nginx/error.log;
pid /run/nginx.pid;

# Load dynamic modules. See /usr/share/nginx/README.dynamic.
include /usr/share/nginx/modules/*.conf;

events {
    worker_connections 1024;
}

#upstream webservers {
#    server 0.0.0.0:5000 weight=1; # 负载设置
#}

http {
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile            on;
    tcp_nopush          on;
    tcp_nodelay         on;
    keepalive_timeout   65;
    types_hash_max_size 2048;

    include             /etc/nginx/mime.types;
    default_type        application/octet-stream;

    # Load modular configuration files from the /etc/nginx/conf.d directory.
    # See http://nginx.org/en/docs/ngx_core_module.html#include
    # for more information.
    include /etc/nginx/conf.d/*.conf;

    server {
        listen       80 default_server;
        listen       [::]:80 default_server;
        server_name  192.168.238.10;
        #root         /usr/share/nginx/html;
        root         /root/soft/install/walle-web/fe;

        # Load configuration files for the default server block.
        include /etc/nginx/default.d/*.conf;

        location / {
        }

        error_page 404 /404.html;
            location = /40x.html {
        }

        error_page 500 502 503 504 /50x.html;
            location = /50x.html {
        }
    }

# Settings for a TLS enabled server.
#
#    server {
#        listen       443 ssl http2 default_server;
#        listen       [::]:443 ssl http2 default_server;
#        server_name  _;
#        root         /usr/share/nginx/html;
#
#        ssl_certificate "/etc/pki/nginx/server.crt";
#        ssl_certificate_key "/etc/pki/nginx/private/server.key";
#        ssl_session_cache shared:SSL:1m;
#        ssl_session_timeout  10m;
#        ssl_ciphers HIGH:!aNULL:!MD5;
#        ssl_prefer_server_ciphers on;
#
#        # Load configuration files for the default server block.
#        include /etc/nginx/default.d/*.conf;
#
#        location / {
#        }
#
#        error_page 404 /404.html;
#            location = /40x.html {
#        }
#
#        error_page 500 502 503 504 /50x.html;
#            location = /50x.html {
#        }
#    }

}

[root@docker-k8s-node001 walle-web]# more /etc/nginx/conf.d/default.conf 
upstream webservers {
    server 0.0.0.0:5000 weight=1;
}

server {
    listen       80;

    location / {
        root /root/soft/install/walle-web/fe; # 前端代码
        try_files $uri $uri/ /index.html;
        add_header access-control-allow-origin *;
    }

    location ^~ /api/ {
        add_header        access-control-allow-origin *;
        proxy_pass        http://webservers;
        proxy_set_header  X-Forwarded-Host $host:$server_port;
        proxy_set_header  X-Real-IP  $remote_addr;
        proxy_set_header  Origin        $host:$server_port;
        proxy_set_header  Referer       $host:$server_port;
    }

    location ^~ /socket.io/ {
        add_header        access-control-allow-origin *;
        proxy_pass        http://webservers;
        proxy_set_header  X-Forwarded-Host $host:$server_port;
        proxy_set_header  X-Real-IP  $remote_addr;
        proxy_set_header  Origin        $host:$server_port;
        proxy_set_header  Referer       $host:$server_port;
        proxy_set_header  Host $http_host;
        proxy_set_header  X-NginX-Proxy true;

        # WebScoket Support
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection "upgrade";
    }

}

walle配置
[root@docker-k8s-node001 walle-web]# more walle/config/settings_prod.py
# -*- coding: utf-8 -*-
"""
    walle-web
    Application configuration.
    注意: 带了 @TODO 的地方可能需要你的调整

    :copyright: © 2015-2019 walle-web.io
    :created time: 2018-11-24 07:05:35
    :author: wushuiyong@walle-web.io
"""

import os
from walle.config.settings import Config


class ProdConfig(Config):
    """Production configuration."""
    ENV = 'prod'
    DEBUG = False
    SQLALCHEMY_ECHO = False

    # 服务启动 @TODO
    # HOST 修改为与 nginx server_name 一致.
    # 后续在web hooks与通知中用到此域名.
    HOST = '192.168.238.10'
    PORT = 5000
    # https True, http False
    SSL = False

    # 数据库设置 @TODO
    SQLALCHEMY_DATABASE_URI = 'mysql://root:root@192.168.238.10:3306/walle?charset=utf8'

    # 本地代码检出路径（用户查询分支, 编译, 打包） #TODO
    CODE_BASE = '/tmp/walle/codebase/'

    # 日志存储路径 @TODO
    # 默认为walle-web项目下logs, 可自定义路径, 需以 / 结尾
    # LOG_PATH = '/var/logs/walle/'
    LOG_PATH = os.path.join(Config.PROJECT_ROOT, 'logs')
    LOG_PATH_ERROR = os.path.join(LOG_PATH, 'error.log')
    LOG_PATH_INFO = os.path.join(LOG_PATH, 'info.log')
    LOG_FILE_MAX_BYTES = 100 * 1024 * 1024

    # 邮箱配置 @TODO
    MAIL_SERVER = 'smtp.exmail.qq.com'
    MAIL_PORT = 465
    MAIL_USE_SSL = True
    MAIL_USE_TLS = False
    MAIL_DEFAULT_SENDER = 'service@walle-web.io'
    MAIL_USERNAME = 'service@walle-web.io'
    MAIL_PASSWORD = 'Ki9y&3U82'

**Comment by flying1020** [comment]
应该是配置不正确。nginx 的 api 转发的配置是转发到了 http://webservers。但是在 walle 的启动配置中，监听的却是·HOST = '192.168.238.10'；PORT = 5000· 这样是不行的。请求 http://webservers 的话，walle 后端服务不会收到的。
如果首次安装，建议先逐步按照官网给的来，等记住了几个关键的参数并且明白了这几个参数的意思后，再改成自己想要的。
我们也会考虑修改这个安装方式，确实有不少用户因此而困惑，感谢提供反馈。
有问题请随意回复，谢谢。

**Comment by bocweb** [comment]
执行下  sh admin.sh upgrade，如果有报python错误哪个包版本低，就pip install安装下，我之前也碰到过，这样操作下就好了
