### ISSUE TITLE
BUG：在post release阶段使用$VERSION变量造成回滚失败

### ISSUE THREAD

**Issue by gufei** [meolu/walle-web#827]
**问题描述**
如果在自定义任务中使用了$VERSION变量，发布完成后 回滚，会回滚失败，报目录文件不存在

例如使用 cd ${CURRENT_RELEASE}/${VERSION}

**Comment by flying1020** [comment]
已经提交代码，问题暂时关闭。如果发现没能修复，再 reopen 即可。
谢谢反馈，请随意提交任何 issue。
