### ISSUE TITLE
好大的坑。安装老是出问题，安装完报各种语法错误

### ISSUE THREAD

**Issue by Osub** [meolu/walle-web#83]
好大的坑。安装老是出问题，安装完报各种语法错误。总之，不能顺利使用。

**Comment by meolu** [comment]
哦？你遇到的问题在帮助手册应该都会有相应的提示和引导

>安装出问题
国内coompser网络环境不好，可以直接下载vendor包

>安装完报语法错误
是因为要求php 5.4+
