### ISSUE TITLE
创建上线单，无法选取分支

### ISSUE THREAD

**Issue by yulrosy** [meolu/walle-web#830]
**问题描述**
在`Owner`角色下，上线单创建页面，无法选取分支
已经建立宿主机和repo的ssh-key信任，在宿主机手动拉取代码是ok的
**问题描述**
walle-python | 66806bb17b234234beecc2f160b59480: Received packet MESSAGE data 2/walle,["commits",{"branch":"master"}]
walle-python | received event "commits" from 66806bb17b234234beecc2f160b59480 [/walle]
walle-python | emitting event "commits" to 2 [/walle]
walle-python | 66806bb17b234234beecc2f160b59480: Sending packet MESSAGE data 2/walle,["commits",{"data":{"message":""},"event":"error"}]

**截图**
![image](https://user-images.githubusercontent.com/5822190/55458013-464d7600-561e-11e9-9e15-f4e67a7d200e.png)

**运行环境**
 - OS: [ubuntu 16 LTS]
 - 版本 [2.0.0]

**Comment by Yellowpal** [comment]
我也遇到这问题了。。。

**Comment by chengjun2018** [comment]
情况和你差不多
![image](https://user-images.githubusercontent.com/35955748/55552738-d2d86100-5710-11e9-82eb-7129ec613617.png)
![image](https://user-images.githubusercontent.com/35955748/55552755-db309c00-5710-11e9-9160-fc35ef7aad5e.png)

daa56769adf84ef5a934adb67373357c: Sending packet MESSAGE data 2/walle,["branches",{"data":{"message":""},"event":"error"}]
daa56769adf84ef5a934adb67373357c: Received packet MESSAGE data 2/walle,["branches"]
received event "branches" from daa56769adf84ef5a934adb67373357c [/walle]
emitting event "branches" to 20 [/walle]
daa56769adf84ef5a934adb67373357c: Sending packet MESSAGE data 2/walle,["branches",{"data":{"message":""},"event":"error"}]
daa56769adf84ef5a934adb67373357c: Received packet PING data None
daa56769adf84ef5a934adb67373357c: Sending packet PONG data None

**Comment by Reshared** [comment]
情况一样，重装也是这样，求解决方法~

**Comment by Yellowpal** [comment]
这里好像是有个坑还是我不会用的问题，用http协议拉取代码是不行的，后来我换了用git协议就好了，需要注意的是公钥也要放一份到git服务器上。这是我踩到的这个坑目前的解决方案。

**Comment by yulrosy** [comment]
> 这里好像是有个坑还是我不会用的问题，用http协议拉取代码是不行的，后来我换了用git协议就好了，需要注意的是公钥也要放一份到git服务器上。这是我踩到的这个坑目前的解决方案。

我是用的ssh

**Comment by Reshared** [comment]
有个坑，不知道大家有没有。
第一次用的时候不太懂，用过sudo sh admin.sh start 
然后/tmp/walle/codebase就由root用户创建了
然后发现不用root权限以后，就直接启动了admin.sh
于是乎，pythonGit写入/tmp...时，就没权限了，而且这个是没有报错的。。。
解决方法：
1、重新用sudo方式，启动后台进程；
2、sudo rm -rf /tmp/walle  让系统重新去生成这个文件夹；
弥陀佛。。。

**Comment by xyggun** [comment]
我也遇到这个问题，在服务器上先拉一遍代码就有数据了

**Comment by yulrosy** [comment]
> 我也遇到这个问题，在服务器上先拉一遍代码就有数据了

我在服务器上拉过了

**Comment by ZouHongxue** [comment]
> 我在服务器上拉过了

项目非常大吗？公开项目的话能否贴下项目地址。

**Comment by yulrosy** [comment]
> > 我在服务器上拉过了
> 
> 项目非常大吗？公开项目的话能否贴下项目地址。

公司内部项目，托管在bitbucket

**Comment by chengjun2018** [comment]
这个问题，我已经规避了 。我的解决办法是删除 项目管理-中的对应的项目，（copy）一份再删除。 这样新建上线单应该可以获取到分支信息了！

**Comment by mniya** [comment]
有办法了吗

**Comment by chengjun2018** [comment]
解决办法是删除 
项目管理-中的对应的项目，（copy）一份 再 删除旧的项目。将copy的项目修改一下 即可 
这样新建上线单应该可以获取到分支信息了！

**Comment by cute-angelia** [comment]
> 解决办法是删除
> 项目管理-中的对应的项目，（copy）一份 再 删除旧的项目。将copy的项目修改一下 即可
> 这样新建上线单应该可以获取到分支信息了！

虽然这样能解决问题, 但是几十个项目, 每个还要分配权限,这操作都要疯掉了

**Comment by chen2gou** [comment]
TOT 相同问题

**Comment by liugaohua** [comment]
我的是centos7 各位的方法都试了，么有用啊。
`root      9052  0.0  0.0  21104   596 pts/1    Sl   17:49   0:00 git clone -v git@47.88.158.89:giikin/goms3.git /tmp/walle/codebase/2
root      9053  1.3  0.0  75380  1600 pts/1    S    17:49   0:17 ssh git@47.88.158.89 git-upload-pack 'giikin/goms3.git'
root      9055  0.7 16.0 356324 302076 pts/1   S    17:49   0:09 git index-pack --stdin --fix-thin --keep=fetch-pack 9052 on localhost.localdomain
root      9690  0.0  0.0 112708  1008 pts/1    S+   18:10   0:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn git
{19-08-09 18:10}localhost:/ root# cd /tmp/walle/codebase 
{19-08-09 18:10}localhost:/tmp/walle/codebase root# ll
总用量 4.0K
drwxr-xr-x 3 root root 4.0K 8月   9 17:49 2
`

**Comment by liugaohua** [comment]
我的是centos7 各位的方法都试了，么有用啊。
![image](https://user-images.githubusercontent.com/3156139/62772059-28fb4d80-bad1-11e9-9796-e50fc459a56c.png)

**Comment by Jerrywgl** [comment]
通过重启服务，这个问题可以临时解决。但是过一会儿又会出现
