### ISSUE TITLE
上线单无法获取分支

### ISSUE THREAD

**Issue by youbuwei** [meolu/walle-web#849]
**问题描述**
在上线单页面，点击同步分支按钮，有如下报错
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/1303345/56076990-6a246f00-5e09-11e9-8217-1e70d6b88b4b.png">

**问题描述**
没有日志和网络请求

logs/runtime.log
```
runtime...
```
logs/error.log
```
error...
```

**运行环境**
walle 版本           2.0.0
walle commit     0db48e3f
服务器信息    Linux-3.10.0-957.1.3.el7.x86_64-x86_64-with-centos-7.6.1810-Core
Python           2.7.5

**Comment by commissarster** [comment]
同样的问题，docker 安装

**Comment by hmgero** [comment]
遇到同样的问题，没法部署了！！！！

**Comment by commissarster** [comment]
我的问题解决了，因为walle默认是root用户安装docker。 
如果你也是安装docker的walle，可以将[官方文档](http://walle-web.io/docs/installation_docker.html)的第34行改成如下内容就可以了。

```
      - /你的用户路径/.ssh:/root/.ssh/
```

**Comment by youbuwei** [comment]
我的不是docker安装的，是本地部署

**Comment by youbuwei** [comment]
https://github.com/meolu/walle-web/issues/830

**Comment by mniya** [comment]
有办法了吗
