### ISSUE TITLE
spring boot启动BUG

### ISSUE THREAD

**Issue by SXScode** [meolu/walle-web#893]
**问题描述**
我启动spring boot的脚本命令是nohup java -XX:MetaspaceSize=512m -XX:MaxMetaspaceSize=512m -Xms2048m -Xmx2048m -Xmn512m -Xss256k -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005,suspend=n -jar /home/work/spring-cloud/boots/transfer-cloud-api-0.0.1-SNAPSHOT.jar --spring.profiles.active=release >/home/work/spring-cloud/boots/nohup.out

这个命令不是后台执行。
然后页面就卡在这，过一会就说部署失败，请修改后重新部署。
<img width="708" alt="WeChat034302f2b755a6f205a89da113ebd622" src="https://user-images.githubusercontent.com/15102017/56889945-8fbca400-6aaa-11e9-999d-076ffdf6b755.png">
虽然页面是卡在这，但是实际上我启动成功了。。。

然后我把脚本命令改成后台启动  nohup java -jar  >/dev/null 2>&1 & 这种格式的话，页面没问题，如下图。
<img width="873" alt="WeChat9ea7d87b4992ad05b3b2b919c3229bd8" src="https://user-images.githubusercontent.com/15102017/56890038-e32ef200-6aaa-11e9-8b42-e03b2409dab8.png">
页面显示成功了，但是实际上没有启动成功，这是为啥啊

**问题描述**
日志堆栈贴上来。
logs/runtime.log
```
runtime...
```
logs/error.log
```
error...
```

**截图**
拖拽到此处即可上传

**运行环境**
 - OS: [e.g. Centos 7.x]
 - 版本 [e.g. aba77b36] walle首页信息处显示

**Comment by EndlessFighting** [comment]
nohup java -XX:MetaspaceSize=512m -XX:MaxMetaspaceSize=512m -Xms2048m -Xmx2048m -Xmn512m -Xss256k -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005,suspend=n -jar /home/work/spring-cloud/boots/transfer-cloud-api-0.0.1-SNAPSHOT.jar --spring.profiles.active=release >/home/work/spring-cloud/boots/nohup.out

上面这段写成shell脚本
然后在walle 用nohup启动shell脚本
不要问为什么，我也不知道

**Comment by xbw1220** [comment]
脚本不需要nohup，只要脚本中启动jar包的那个命令加nohup commond &这样写就行了，然后脚本需要引入环境变量

**Comment by SXScode** [comment]
问题解决了，应该是远程调用脚本的时候确实不用能nohup在脚本中，会和ssh链接冲突。具体原因还不太理解。
nohup ${SPRING_BOOT}/api.sh >/dev/null 2>&1 &   在walle项目配置中这样配置解决。

**Comment by SXScode** [comment]
> 脚本不需要nohup，只要脚本中启动jar包的那个命令加nohup commond &这样写就行了，然后脚本需要引入环境变量

多谢

**Comment by SXScode** [comment]
> nohup java -XX:MetaspaceSize=512m -XX:MaxMetaspaceSize=512m -Xms2048m -Xmx2048m -Xmn512m -Xss256k -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005,suspend=n -jar /home/work/spring-cloud/boots/transfer-cloud-api-0.0.1-SNAPSHOT.jar --spring.profiles.active=release >/home/work/spring-cloud/boots/nohup.out
> 
> 上面这段写成shell脚本
> 然后在walle 用nohup启动shell脚本
> 不要问为什么，我也不知道

多谢
