### ISSUE TITLE
远程机postRelease 任务执行时机是否可以调整到软链接建立之后？

### ISSUE THREAD

**Issue by itbeihe** [meolu/walle-web#9]
目前测试后看代码发现,先执行post release任务，再建立项目软链接。

/walle-web/controllers/WalleController.php 
"""
$this->_postRelease();
$this->_link($this->task->link_id);
$this->_cleanUp($this->task->link_id);
"""
实际部署时候，大部分更愿意代码部署完成后，再执行服务器重启脚本，执行针对机器的处理脚本。
今天尝试部署的时候，比如想部署完成，通过post release，进行项目配置文件的替换，脚本里，只能从版本库多个文件夹中取出最新的，不能通过软件的目录直接进入项目目录。略坑。
另外是否考虑引入生产机部署前任务，可以实现部署代码前，停掉相关应用。

**Comment by meolu** [comment]
嗯，想法是正确的：）昨晚已经开发好了，正在写单测，通过之后再发布

**Comment by meolu** [comment]
```
$this->_preRelease();
$this->_link($this->task->link_id);
$this->_postRelease();
$this->_cleanUp($this->task->link_id);
```

**Comment by meolu** [comment]
但其实，pre-release、link、post-release任务已经改为打包到一起到服务器逐台机器执行

**Comment by itbeihe** [comment]
禅师辛苦了。坐等新功能发布，目前已经说服运维同学，准备在新项目用瓦力来进行测试机和生产机的部署管理。

**Comment by meolu** [comment]
哈哈，好啊，之前已经有一个做服务行业的公司在用了，当然我们公司自己也在用，如在使用过程有任何问题，欢迎反馈，会尽快处理的：）
