### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by hdjahs** [meolu/walle-web#912]
[root@www walle]# sh admin.sh start
                                                                                            
----------------
admin.sh: line 81: ./venv/bin/activate: 没有那个文件或目录
[root@www walle]# python
Python 2.7.7 (default, Nov 30 2018, 10:11:46) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()

**Comment by ZouHongxue** [comment]
init 执行不成功，请参照安装文档重新执行 第五步 init。
如果没有成功，请参考第五步注释部分执行。

**Comment by shijunti19** [comment]
@ZouHongxue 这一步明显是3吧，怎么先设置nginx，如果是老用户，重新部署，nginx是不需要再配置的
