### ISSUE TITLE
docker-compose 搭建成功后,ssh免登配置

### ISSUE THREAD

**Issue by gengsende** [meolu/walle-web#927]
docker-compose 搭建成功后,ssh免登配置需在"walle-python"容器中生成执行"ssh-keygen -t rsa"配置和远程目标集群的远程登录.

**Comment by Alenx58** [comment]
@gengsende walle是用root的免密目录，如果用其他用户进行ssh时需更改docker-compose中volumes:/root/.ssh:/root/.ssh/
