### ISSUE TITLE
高级任务配置的命令都执行错误

### ISSUE THREAD

**Issue by pandaxba** [meolu/walle-web#93]
#### 在pre_deploy、post_deploy等高级任务中配置的命令，都不能正确执行。
*  在pre_deploy中配置了一个`echo 'test'`,发布的时候报错如下图： 
![a](https://cloud.githubusercontent.com/assets/4688875/12414611/7d557e78-bed1-11e5-8bb1-0d65a2228a6c.png)

* 如果不配置任何命令，发布流程就能正常走完。

**Comment by pandaxba** [comment]
执行命令返回127，我把`Task`里面的这行代码注释掉就好了。
`$cmd = ['source /etc/profile'];`

**Comment by meolu** [comment]
`source /etc/profile`返回错误

是什么情况？是不存在文件，还是配置文件`/etc/profile`有问题？

**Comment by pandaxba** [comment]
文件存在，没有问题

**Comment by meolu** [comment]
```
source /etc/profile
echo $?
```
看下什么情况？

**Comment by littlehz** [comment]
用户默认shell是 /bin/sh 就会出现这个问题 source: not found。 source 是 bash 内置命令 ba5b0a428689ab7007311970b7b484756d04c7e9

**Comment by meolu** [comment]
哦，原来是这原因
