### ISSUE TITLE
文档手册中有不合理的命令

### ISSUE THREAD

**Issue by duanzhanling** [meolu/walle-web#96]
在安装依赖时，建议使用如下命令：
yum install php56w php56w-cli php56w-common php56w-gd php56w-ldap php56w-mbstring php56w-mcrypt php56w-mysql php56w-pdo
这样yum在安装时会自动选择对应的版本号，而目前的手册上命令是针对64bit的

**Comment by meolu** [comment]
列下？

**Comment by duanzhanling** [comment]
yum install php56w.x86_64 php56w-cli.x86_64 php56w-common.x86_64 php56w-gd.x86_64 php56w-ldap.x86_64 php56w-mbstring.x86_64 php56w-mcrypt.x86_64 php56w-mysql.x86_64 php56w-pdo.x86_64   这个是目前手册上的命令
