### ISSUE TITLE
回滚BUG

### ISSUE THREAD

**Issue by happy-wgx** [meolu/walle-web#963]
**问题描述**
在上线完成之后进行回滚，回滚完成之后再次点击上线的时候是从第四步Release前置任务开始，
但是在最后的时候要删除tgz文件，因为没有进行前面的deploy步骤，就没有生成对应的文件，导致上线失败
‘’‘

**截图**

![image](https://user-images.githubusercontent.com/52312217/60325571-2ed21f00-99ba-11e9-83e6-bb62952eff0a.png)

**Comment by phcast** [comment]
请问这个有解决办法吗
