### ISSUE TITLE
BUG Mac 下安装异常

### ISSUE THREAD

**Issue by xmlijian** [meolu/walle-web#967]
**问题描述**
Mac下安装 提示 
Initing walle
----------------
admin.sh: line 48: /etc/os-release: No such file or directory

**截图**
拖拽到此处即可上传

**运行环境**
 - OS:  10.14.5 
 - 版本: walle 2.0

**Comment by xmlijian** [comment]
已修改admin.sh安装成功

**Comment by wangkechen** [comment]
怎么修改的？能把代码贴出来吗？

**Comment by ZouHongxue** [comment]
> 怎么修改的？能把代码贴出来吗？

直接注释掉那一行，不推荐使用Mac，建议docker安装
