### ISSUE TITLE
v1.0.0的tar.gz压缩包有问题，是一个BUG

### ISSUE THREAD

**Issue by duanzhanling** [meolu/walle-web#97]
v1.0.0的tar.gz压缩包有问题
安装完毕后，启动后报错提示找不到 Error: The file or directory to be published does not exist: /usr/local/walle/vendor/bower/jquery/dist

在安装包中发现有bower-asset这个目录，把这个目录修改为bower，可以正常访问了。

很明显是一个BUG，赶快修复吧
！！！

**Comment by devtoby** [comment]
mkdir -p /usr/local/walle/vendor/bower/jquery/dist 就好了，跟yii模块的机制有一定关系

**Comment by meolu** [comment]
在walle初始化的时候，我添加一个检查vendor/bower/jquery/dist，不存在则新建，并设置权限即可

**Comment by meolu** [comment]
#139
