### ISSUE TITLE
你看下面的图片，失败了也不终止，我都无法关闭，无法删除

### ISSUE THREAD

**Issue by shijunti19** [meolu/walle-web#986]
**问题描述**
在`角色`下，什么页面，什么功能，报错：xx
|在`super超管`角色下，项目管理页面，编辑项目成员，提交失败，报错：用户不存在于空间用户组中

**问题描述**
日志堆栈贴上来。
logs/runtime.log
```
runtime...
```
logs/error.log
```
error...
```

**截图**
拖拽到此处即可上传
![image](https://user-images.githubusercontent.com/5392211/62458273-11f5ec00-b7af-11e9-814f-60f89a6cf720.png)
![image](https://user-images.githubusercontent.com/5392211/62458283-191cfa00-b7af-11e9-9c7b-59e6e615a02a.png)

**运行环境**
 - OS: [e.g. Centos 7.x]
 - 版本 [e.g. aba77b36] walle首页信息处显示

**Comment by x1zbin** [comment]
这已经是终止了的，主要是你项目的配置出现了问题，看下输出有什么错误，你只需要将你项目的配置调整好再重新开始即可

**Comment by shijunti19** [comment]
@x1zbin  我重新发布他又好了，我现在想要的是，我不想修复，想直接关了这条或者删了，你少了这种操作
