### ISSUE TITLE
BUG 在 CentOS 中使用 `mv -fT` 提示 ’non-directory‘

### ISSUE THREAD

**Issue by Android-AwesomeRoy** [meolu/walle-web#989]
**问题描述**
如标题和截图所示。

**截图**
![Snipaste_2019-08-07_10-31-39](https://user-images.githubusercontent.com/19187129/62590483-17fae280-b8ff-11e9-8388-66c2f4cf51e7.png)

**运行环境**
 - OS: Centos 7.5
 - 版本 72cfa73

**Comment by ZouHongxue** [comment]
提示很清楚，请确认/data/wwwroot/default/TYOA/release/current-tmp-4是否以文件夹形式存在

**Comment by Android-AwesomeRoy** [comment]
> 提示很清楚，请确认/data/wwwroot/default/TYOA/release/current-tmp-4是否以文件夹形式存在

但是这里面有一个问题就是，生成 `current-tmp-4` 的过程是由 walle 来完成的，而不是我手动创建的。
我是通过找到源码，把 “T” 从执行命令中去掉了以后才可以正常自动化操作。
