### ISSUE TITLE
头一次使用瓦力，遇到一个问题不会解决

### ISSUE THREAD

**Issue by ayamzh** [meolu/walle-web#998]
**问题描述**
在OWNER角色下，点创建上线单，无法拉取到分支名，RUNTIME.LOG报admin.walle-web.io:80 is not an accepted origin

**问题描述**

**截图**
拖拽到此处即可上传
![微信图片_20190819185821](https://user-images.githubusercontent.com/20828679/63260375-5b683000-c2b3-11e9-9d11-2e7f8370a303.png)

**运行环境**
centos 7

**Comment by ayamzh** [comment]
![微信图片_20190819191833](https://user-images.githubusercontent.com/20828679/63261508-42ad4980-c2b6-11e9-8fcf-ce1991e07fd3.png)  在那个页面 报了些400错误

**Comment by yyccyangchao** [comment]
@ayamzh 在init的时候，你有出现“安装/更新可能缺少的依赖: mysql-community-devel gcc gcc-c++ python-devel" ，但实际去安装的时候，是有的，且是当前yum源最新的安装包。

**Comment by ayamzh** [comment]
@yyccyangchao 不是这个问题 我安装过程中都没报错

**Comment by hustcsxg** [comment]
@ayamzh 请看我的pull request

**Comment by 562236839** [comment]
我也遇到了同样的问题    分支取不到，还找不到解决办法，楼主搞定了吗？

**Comment by viruskingkk** [comment]
這裡有解 https://github.com/meolu/walle-web/issues/997#issue-481492322

**Comment by linux724** [comment]
我刚安装的时候也遇到各种问题，不过我现在已经换成另外一个开源平台了。https://github.com/openspug/spug

**Comment by LIANjoe** [comment]
看我pull request 修改walle/service/extensions.py文件最后一行 为 socketio = SocketIO(engineio_logger=True, logger=True, cors_allowed_origins=[])
 别人的答案，亲测有效
